### ISSUE TITLE
Not an issue but just info

### ISSUE THREAD

**Issue by clownix** [prplfoundation/prplMesh#1]
Cloonix can emulate wlan as well as lan network.
For wlan it uses the mac80211_hwsim of the kernel, an agent is launched in the vm to manage the signal and the cloonix infra carries the signal from vm to vm, this may make a good test tool. See cloonix/quickstart/mac80211_hwsim in the cloonix github for a use-case of wlan interface.
I am ready to help if you want to build a test platform for your software.
clownix.

**Comment by arnout** [comment]
This issue was moved to prplfoundation/prplMesh1905#1
