### ISSUE TITLE
tlvf - fix CMakeLists.txt to only regenerate modified files

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#10]
We want to re-run the generator (tlvf.py) when yaml files change like we do today.
What we don't want is for tlvf.py to re-generate *all* yaml files, including the ones which didn't change. 

tlvf.py firsts read the autogenerated file if it exists, compares it to what's about to be written, and if they are identical, skips it.

However, the cmake build systems sees a single dependency between all of the input files and all of the generated files. So when any of the input changes, it will consider all of the outputs to be regenerated.

Fix CMakeLists.txt to avoid this issue.

**Comment by LiorAmram** [comment]
This is already implemented.
starting from line 1364 of tlvf.py:
```
        if not self.compareFile(file_path, lines):
            f = open(file_path, "w+")
            for line in lines:
                if not self.conf_debug_keep_source_marker:
                    if line.find("//~") != -1: continue
                f.write(line + "\n")
            f.close()
```
the method `compareFile` does exactly what you described - it's comparing the content of the file (if exists) to the text that's about to be written. if it returns false, the text is not written.

**Comment by tomereli** [comment]
> This is already implemented.
> starting from line 1364 of tlvf.py:
> 
> ```
>         if not self.compareFile(file_path, lines):
>             f = open(file_path, "w+")
>             for line in lines:
>                 if not self.conf_debug_keep_source_marker:
>                     if line.find("//~") != -1: continue
>                 f.write(line + "\n")
>             f.close()
> ```
> 
> the method `compareFile` does exactly what you described - it's comparing the content of the file (if exists) to the text that's about to be written. if it returns false, the text is not written.

So it is implemented but doesn't work as it should - I verified this by changing a single yaml file and see that all files are recompiled since cmake senses they have been changed.
Then I changed in CMakeLists.txt so that tlvf.py won't run if yaml file is changed, touched one of the autogenerated files (the one that matches the yaml I changed before), ran cmake and it recompiled this file only.

**Comment by arnout** [comment]
The problem is in the CMakeLists.txt:
```cmake
add_custom_command(
    COMMAND ${TLVF_COMMAND}
    DEPENDS ${TLVF_DEPENDENCIES} ${TLVF_DIR}/tlvf.py ${TLVF_DIR}/tlvf_conf.yaml
    OUTPUT ${TLVF_OUTPUTS}
    COMMENT "Generating the tlvf files."
)
```
DEPENDS means that if any of those dependencies changes, the command will be run again to generate all of the OUTPUTs.
What you need to do, is to restructure it so that each run takes just one input and one output. I believe there is also a way to tell cmake that several outputs can be generated by one run, but I don't know exactly how that works.

I'll update the description to reflect the above.

**Comment by vitalii-komisarenko** [comment]
The TLV generator did notice a newly created tlv.*.yaml file on my machine.
All old files were unchanged; maybe it confused the code generator.
