### ISSUE TITLE
[TASK] move the load_steer_on_vaps from the beerocks_controller.conf.in config file to the UCI

### ISSUE THREAD

**Issue by adam1985d** [prplfoundation/prplMesh#1015]
## Description
This task is created after an investigation performed as part of #1008 

The load_steer_on_vaps is required to be platform-specific and hence need to be moved to the UCI

## Exit criteria

- [x] add load_steer_on_vaps to UCI
- [x] add infrastructure for reading the load_steer_on_vaps from UCI
- [x] read and use the load_steer_on_vaps from UCI
- [x] remove load_steer_on_vaps from controller config file structs read implementation
- [x] remove load_steer_on_vaps from beerocks_controller.conf.in file

for prplWrt:
- [x] add load_steer_on_vaps to UCI
https://github.com/prplfoundation/prplMesh/pull/1040
- [ ] update FEED_PRPL of prplmesh to latest
moved to #1083 

CI:
- [ ] update the PRPL_FEED to latest prplWrt for all openWrt platforms
moved to #1083 

test optimal_path_task on following platforms:
- [x] UGW
- [x] RDKB
- [x] RAX40 (with certification enabled)

test_flows:
- [x] Linux

documents:
- [x] add test document describing how to test optimal_path_task
https://github.com/prplfoundation/prplMesh/wiki/Optimal-Path-Testing

**Comment by arnout** [comment]
To be honest, I don't understand why there is a config option at all for this. Is there any reason to not just consider all the VAPs with the same SSID?

**Comment by tomereli** [comment]
> To be honest, I don't understand why there is a config option at all for this. Is there any reason to not just consider all the VAPs with the same SSID?

It is a legacy feature we support in Intel. I think it was requested by one of the customers originally.
I'm trying to remember why it is needed and I can't think of anything :/
I thought initially about guest access, but I assume that guest VAP will have a different credentials than a non guest VAP so anyway steering will fail, so its probably not that...
