### ISSUE TITLE
Remove meaningless labels once PR is merged

### ISSUE THREAD

**Issue by mariomaz** [prplfoundation/prplMesh#1021]
Labels like "ready for merge" or "help wanted" are meaningless and can even lead to confusion once the PR has been approved and merged, thus they should be removed.

**Comment by arnout** [comment]
Any ideas for possibilities of automating this? If it needs to be done manually, it ain't gonna happen.

**Comment by ghost** [comment]
@arnout Could this be done using Mergify?

**Comment by arnout** [comment]
> @arnout Could this be done using Mergify?

Good one! https://doc.mergify.io/actions.html#label
