### ISSUE TITLE
[TASK] Use Multi-AP information elements in beacons and WPS exchange

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#1070]
For onboarding and wireless backhaul AP support, hostapd needs some additional information elements in association request/response messages and WPS credentials. This requires:

- making sure that hostapd has the relevant commits (currently not the case in prplWrt);
- configure hostapd.conf appropriately.

Relevant commits from hostapd:
- 9c06f0f6aed26c1628acaa74df0232dd7b345e9a
- 5abc7823bd01f69b8afbe1fd19f65fff86137c44
- 7488e0ade6dffb6df4c1fb6526a9f3ede0eb18ef
- 0dab477335d9ea8d71bdb631aab7483542ed1bd0
- bfcdac1c8bb7189310d0797b9bdf19d92d0414f3
- cb3c156e7bb057d84f1f62264134892262f25e5d
- 56a2d788f9dea36c32eebb3c54081ecea29766d4
- 83ebf558654615e02beb3be7011e63307bf328b7
- 66819b07b5fc95d0ffe6defafdb9526427c1955b
- 8682f384cee6a8499c7c04793d1998dd3f82e418
- b1daf498a14934c5b0f85d5373998e5c9e7bbdb4
- 1415d4b82d5eab4c8edf2c2b32200137ae0178c3
- 1d9cff86bd04c52fb448a4a83ee18a094613abff

(not all of these are strictly required, e.g. tests and some of the bugfixes).

Required additions to hostapd.conf:
```
# Enable Multi-AP functionality
# 0 = disabled (default)
# 1 = AP support backhaul BSS
# 2 = AP support fronthaul BSS
# 3 = AP supports both backhaul BSS and fronthaul BSS
#multi_ap=0

# Multi-AP backhaul BSS config
# Used in WPS when multi_ap=2 or 3. Defines "backhaul BSS" credentials.
# These are passed in WPS M8 instead of the normal (fronthaul) credentials
# if the Enrollee has the Multi-AP subelement set. Backhaul SSID is formatted
# like ssid2. The key is set like wpa_psk or wpa_passphrase.
#multi_ap_backhaul_ssid="backhaul"
#multi_ap_backhaul_wpa_psk=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
#multi_ap_backhaul_wpa_passphrase=secret passphrase
```

**Comment by tomereli** [comment]
The Multi-AP patches were not ported to Intel hostapd. Instead, there is what we call "mesh mode" - which allows setting either bAP or fAP, but not both.
Configuration of bAP is done as follows:
```
mesh_mode=bAP
sFourAddrMode=1
max_num_sta=1
```
This will reject any STA which does not include the mAP IE in the association frame.
Regarding setting the mAP IE in the beacon - this needs to be tested.
