### ISSUE TITLE
[TASK] Port test_initial_ap_config to boardfarm for dockerized device

### ISSUE THREAD

**Issue by abelog** [prplfoundation/prplMesh#1071]
### Description
As part of migration to boardfarm testing, we need to port `test_initial_ap_config` of `test_flows.py` to boardfarm for "dummy" docker device.

### Exit criteria
In order to complete the task, we have to complete:

- [ ] Integrate all classes in environment.py with boardfarm classes
- [x] Turn this into a boardfarm plugin
- [x] Make sure that `RadioDocker.wait_for_log` still works
- [x] Create a prplMesh testsuite for boardfarm
- [x] Create InitialApConfig test case for boardfarm
- [ ] Run bft from gitlab-ci.yml
- [ ] Document the boardfarm integration in documentation/boardfarm-testing.md based on the UML classes structure and relations in #1032.

**Comment by oponomar** [comment]
To be able use boardfarm without installation it is necessary to add __init__.py to make Python treat the boardfarm directory contains packages for import.
Created PR to prplfoundation/boardfarm:
https://github.com/prplfoundation/boardfarm/pull/10

Updated main PR: #1136
