### ISSUE TITLE
Port test_ap_config_renew to boardfarm for Dockerized mode

### ISSUE THREAD

**Issue by abelog** [prplfoundation/prplMesh#1073]
### Description
As part of migration to boardfarm testing, we need to port `test_ap_config_renew` of `test_flows.py` to boardfarm for "dummy" docker device.

### More details
In order to complete the task, we have to achieve:
- [] Add relevant for test fields and methods
- [] Port test
UML with classes structure and relations can be checked here (#1032)

### Acceptance criteria
- Relevant boardfarm infrastructure code to handle the test is done
- Result of test is same (as in `test_flows.py`)

**Comment by arnout** [comment]
Restructured the work breakdown so this task is no longer relevant.
