### ISSUE TITLE
[TASK] Boardfarm test template

### ISSUE THREAD

**Issue by MuteSpirit** [prplfoundation/prplMesh#1080]
## Description

As part of migration to Boardfarm testing we need to know how to place Boarfarm tests, test setup configs, devices classes and so on in prplmesh repo

Parent EPIC is #1074 

## Exit criteria

- There are next code inside prplmesh repo:
  - prplmesh Boardfarm test suite
  - prplmesh initial_ap_config test case (but without any test, it just passes)
  - Boardfarm device class for prplMesh docker
  - Boardfarm test setup config for DUT in docker
  - README file with info needed for developers who will migrate `test_flows.py` to Boardfarm

## Detailed description

Use the same folder structure as in Boardfarm repo
Use "boardfarm.plugins" mechanism to show Boardfarm the tests inside prplmesh repo
Use stub test that's just run and return success
Use dockerized DUT in test setup config

**Comment by taurha** [comment]
Added draft PR: https://github.com/prplfoundation/prplMesh/pull/1108
**WIP:** working on dockerized device example.
