### ISSUE TITLE
[BUG] RAX40 fails to attach to wlan0 hostapd due to read TxPower in GetRadioInfo

### ISSUE THREAD

**Issue by adam1985d** [prplfoundation/prplMesh#1084]
**Describe the bug** -
In RAX40 the `GetRadioInfo` fails to read TxPower. As a result, the attach to wlan0 fails and the attach process is restarted - this loops endlessly.

## Steps to reproduce

1. Flash RAX40 with latest prplWrt image and prplmesh hash changed to latest prplmesh 
2. Run certification_mode controller
3. tail -F /tmp/beerocks/logs/beerocks_agent_wlan0.log

Note:
if WiFi fails to load properly use the `wifi down` then `wifi up` repeatedly until wifi is up and all vap interfaces are available.
## Expected behavior
prplmesh should reach operational

## Screenshots
```
INFO 01:21:55:722 <1986284792> ap_manager_thread.cpp[343] --> waiting to attach to wlan0
INFO 01:21:56:123 <1986284792> ap_manager_thread.cpp[343] --> waiting to attach to wlan0
INFO 01:21:56:524 <1986284792> ap_manager_thread.cpp[343] --> waiting to attach to wlan0
INFO 01:21:56:926 <1986284792> ap_manager_thread.cpp[343] --> waiting to attach to wlan0
INFO 01:21:57:327 <1986284792> ap_manager_thread.cpp[343] --> waiting to attach to wlan0
INFO 01:21:57:728 <1986284792> ap_manager_thread.cpp[343] --> waiting to attach to wlan0
DEBUG 01:21:58:129 <1986284792> base_wlan_hal_dwpal.cpp[396] --> DWPAL FSM wlan0 Attach State: Init
INFO 01:21:58:130 <1986284792> ap_manager_thread.cpp[343] --> waiting to attach to wlan0
DEBUG 01:21:58:532 <1986284792> base_wlan_hal_dwpal.cpp[542] --> dwpal_hostap_interface_attach() success for: wlan0
DEBUG 01:21:58:533 <1986284792> base_wlan_hal_dwpal.cpp[151] --> dwpal_driver_nl_attach() success for: wlan0, nl_context = 0x7671cb70
INFO 01:21:58:534 <1986284792> beerocks_state_machine.h[53] --> 'Init': Overriding destination for 'Attach' from 'Attach' to 'GetRadioInfo'
DEBUG 01:21:58:535 <1986284792> base_wlan_hal_dwpal.cpp[396] --> DWPAL FSM wlan0 Attach State: GetRadioInfo
INFO 01:21:58:535 <1986284792> ap_manager_thread.cpp[343] --> waiting to attach to wlan0
ERROR 01:21:58:938 <1986284792> base_wlan_hal_dwpal.cpp[769] --> Failed reading parsed parameter 2 ==> Abort
INFO 01:21:58:939 <1986284792> beerocks_state_machine.h[53] --> 'GetRadioInfo': Overriding destination for 'Attach' from 'AttachVaps' to 'Detach'
DEBUG 01:21:58:939 <1986284792> base_wlan_hal_dwpal.cpp[350] --> dwpal_fsm_state::Detach
INFO 01:21:58:939 <1986284792> base_wlan_hal_dwpal.cpp[354] --> Call DWPAL socket close
```

## Additional context

the parameter that DWPAL fails to parse is `TxPower` and change was introduced to prplmesh as part of commit hash `a12f9bb5a2f77cf15709bf4dbd8b8baef9c8d072`

**Comment by tomereli** [comment]
@adam1985d we have a solution, please add link to the wiki and close

**Comment by adam1985d** [comment]
The issue was raised due to residual configuration on the DUT.
after running `firstboot` command for clearing the overlay the issue (as well as other issues) didn't reproduce.

added the `firstboot` command to the Nighthawk description in the Wiki
