### ISSUE TITLE
[BUG] agent: backhaul: 1905 forward on fail mechanism

### ISSUE THREAD

**Issue by RanRegev** [prplfoundation/prplMesh#1085]
**Description**
Currently 1905 messages are handled in the backhaul in this manner:
calling a ```bool handle_1905_xxx()``` function and looking on the return value:
when true: the function handled the message, processing terminates.
when false: the function didn't handle the message, processing continues to agents.

The problem is that inside these functions, if error occurs they return `false`, therefore processing, in an error flow, is forwarded to the agents.

**Comment by tomereli** [comment]
@morantr please comment

**Comment by morantr** [comment]
Yes, it is bad implementation. Fortunately, I'm working on a unified Agent so this whole message forwarding mechanism will be removed.
I suggest closing this issue.

**Comment by arnout** [comment]
Let's instead say that this will be fixed by #1082.
