### ISSUE TITLE
[TASK] Add optimal path test to test_flows

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#1086]
## Description

Add a test of the controller's optimal_path algorithm to test_flows. This helps to make sure that changes in controller code don't break this algorithm.

There was such a test before, but it wasn't working, so it was removed.

**Comment by morantr** [comment]
Why did you remove it and not open a task to fix it?

**Comment by arnout** [comment]
> Why did you remove it and not open a task to fix it?

It was either remove it or fix it, and I didn't have time to fix it. Keeping the half-working code around was making my progress on #1031 slower.
