### ISSUE TITLE
[BUG] No Topology Response message found

### ISSUE THREAD

**Issue by CoralMalachi** [prplfoundation/prplMesh#1097]
**Describe the bug** -
I found out that if I rebase my side branch on the master, the test I'm working on [4.6.2] is flailing with the following error:

![image](https://user-images.githubusercontent.com/38204874/78569383-374e6480-782c-11ea-8a2a-d876c59b5eb5.png)

it is important to note that before the last rebase the test passed, and the rebase did not ask for any merge conflicts.
Therefore, I have decided to check if the master is broken, and I found out that the same error occurs in every test which involves triggering of the CTT Controller to send Topology Query to MAUT:

![image](https://user-images.githubusercontent.com/38204874/78568163-61068c00-782a-11ea-8df3-ae0c5803d99e.png)
https://gitlab.com/prpl-foundation/prplMesh/-/jobs/500319964

## Steps to reproduce
run test 4.4.2 on the master.
You can also take a look at my logs: https://gitlab.com/prpl-foundation/prplMesh/pipelines/133287916

## Expected behavior

The test fails with the error message : 
No Topology Response message found

### Casuse of the bug
The last time we ran the certification tests on master version was on `ce6709cae467e48c754f47a6068a3454f0906c0f` commit,  and the test passed.
After that, the following PRs were merged to master: 

- #1053 
- #1060
- #1068 
- #1043
- #1029

So one of them must be the cause of the problem.

**Comment by rmelotte** [comment]
Also important to note that it happens on both testbeds at the same time, so it's unlikely to be a setup issue: https://ftp.essensium.com/owncloud/index.php/apps/files/?dir=/prplmesh/certification/Nightly/agent_certification/netgear-rax40/2020-04-06_23-30-01/FAIL/MAP-4.4.2_ETH_FH24G&fileid=856884

**Comment by rmelotte** [comment]
[MAP-4.4.2_ETH_FH24G](https://gitlab.com/prpl-foundation/prplMesh/-/jobs/500319964/artifacts/browse/logs/FAIL/MAP-4.4.2_ETH_FH24G/dut_netgear-rax40/) has the following lines:
```
DEBUG 11:41:18:706 <1992207608> backhaul_manager_thread.cpp[2206] --> Received TOPOLOGY_QUERY_MESSAGE , mid=33
ERROR 11:41:18:707 <1992207608> backhaul_manager_thread.cpp[2327] --> Unable to compute media type for interface wlan0
```

**Comment by rmelotte** [comment]
Reopening because the issue is still present on master: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/502121246
```
ERROR 12:40:41:274 <1996967160> backhaul_manager_thread.cpp[2328] --> Unable to compute media type for interface wlan2
```

**Comment by rmelotte** [comment]
Passing test: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/503734888
