### ISSUE TITLE
[TASK] CI: add a local shell wrapper for flake8

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#1117]
## Description

At the moment, running tools like flake8 and cppcheck in the same way as what is done in CI requires some manual work (to run the correct docker image, with the same commands).

It would be nice to have a script for each tool that would run exactly what is run in CI, with the same version of each tool.

This is especially important for tools for which the result is highly dependent on the version being used.

As a first step, this task is only about flake8.

In the end, if in CI there is a `flake8` job, the goal is that anyone can either:
- run `tools/docker/flake8.sh` to run the flake8 job using the same docker image as in CI, running the same commands.
- run `tools/flake8.sh`, should the developer want to use tools from its local environment instead (this is required since in CI we run within docker images directly, and could also be useful for developers to quickly test other versions of a tool).

This task would also make it easier to later have a single script that reports issues within any code file (C++, python, shell, ...) in a single invocation, or to have another one to format the code in one go throughout the repository (using for example clang-format for C++, autopep8 for python, etc)

## Exit criteria

For the `flake8` and `flake8-diff` jobs:
- a new Dockerfile is added under `tools/docker/static-analysis/flake8/`, and the corresponding image is pushed to the Gitlab registry
- the Dockerfile contains the `script` part of the job that is specific to the docker image (currently only the `apk add...` part) 
-  the `script` section that is not specific to the docker image is moved as is to a separate file under `tools/<job_name>.sh`
- the job in `.gitlab-ci.yml` uses the new image from the Gitlab registry, and only calls `tools/<job_name>.sh.
- a shell script is added: `tools/docker/<job_name>.sh`. It only runs the new docker image (by pulling it from the Gitlab registry if necessary) and calls `tools/<job_name>.sh`.

**Comment by MuteSpirit** [comment]
I think that "flake8" also very usable in view of IDEs plugins and reconfigure them for custom script in prplMesh maybe complicated.
What do you think about idea to add all flake8 options into `.flake8` config file and force "flake8" IDE/editors on developers PC follow them on checking code?

**Comment by arnout** [comment]
The problem is that flake8 is like cppcheck: newer versions catch more issues. So the older version that is in Ubuntu 18.04 will not catch some things that are caught in CI.

However, is it really worth to create a script that simply does `sudo docker run -it -v $PWD:$PWD pipelinecomponents/flake8:f087c4c flake8 "$@"` ?
