### ISSUE TITLE
[TASK] boardfarm: add interface for querying status

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#1124]
## Description

In current test_flows.py, quite a lot of check_log calls actually verify the current status of the entity, e.g. `self.check_log(env.agents[0].radios[0], r"Received credentials for ssid: Multi-AP-24G-1 .* bss_type: 2")` really wants to verify that a VAP was created with that SSID and bss type. This should be replaced with abstract methods to check the status.

## Exit criteria

- [ ] `Radio.get_channel()` interface is used in test cases.
- [ ] `Radio.get_power_limit()` interface is used in test cases.
- [ ] `Radio.get_vap(ssid)` interface is used in test cases. It returns a VirtualAP object or None.
- [ ] `VirtualAP.get_bss_type()` interface is used in test cases.
- [ ] All of the above is implemented for prplWrt device.
- [ ] All of the above is implemented for docker device. Note that this may require changes in dummy bwl.
- [ ] documentation/boardfarm_testing.md is updated if necessary.

Note: This is quite a big task, it may need to be split up.

**Comment by tomereli** [comment]
I don't think this is the right direction - we should use the be able to use #1020 and imitate the exact tests that are done by the UCC. So, to get the tx power limit, channel, bss_type, etc - we should parse the appropriate CMDU.

**Comment by arnout** [comment]
This is about being able to test that the bwl works correctly, by querying the actual wireless state, *not* about checking which packets are sent over the network.

In certification, this is mostly done by letting an agent connect, but that is difficult to implement with dummy. Currently we use check_log for these cases, but check_log doesn't work for non-dummy bwl.

So, to have a unified approach, the idea is that the Radio and VirtualAP classes will implement their own way of checking status. For the -Docker cases, this can still be check_log. For the physical ones, it can be done with `iw`, for instance.
