### ISSUE TITLE
[TASK] Automatically update a google sheet with the test status

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#1130]
## Description

Right now, a lot of time is wasted looking at the current certification test status in CI, and making a spreadsheet showing the evolution of the tests.
This should be done automatically at the end of the nightly test run.

## Exit criteria

- [ ] The state of the test run is automatically updated in google sheets
- [ ] This has been checked for accuracy
- [ ] The format of the sheet closely matches the previous manually entered sheet
- [ ] New data doesn't overwrite old data, but is appended nicely to the start of the sheet

## Detailed description

- **Problem statement**

Progress in passing flows is the key metric used to keep track of project completion, and so it is essential that everyone is kept up to date on the evolution towards this goal, both in positive sense (new tests are passing), and especially of regressions (test that used to pass that now fail).
In this context, a spreadsheet was created and maintained listing test status and evolution over time Because this relied on manual updating, which is tedious and time-consuming, this spreadsheet is incomplete and a big time sink.

- **Possible solutions**
We could have continued with the manual updating, but the disadvantage is that it ties up a significant amount of time from someone better used writing new tests, extending test infrastructure or implementing/debugging new features.

The solution that was chosen is a script that automatically updates a google spreadsheet through the relevant google API for this. This API is easy to use and integrates easily with existing scruipts as it's available in python.

- **Components affected** 
CI runners with a certification test setup are affected. The main source and flow tests are not affected.
- **Build considerations**
None. The only changes are in scripts.
- **Dependencies** 
The changes might introduce stricter version requirements for python. In addition, it requires installing new python modules for working with google sheets:
`pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib`

**Comment by tomereli** [comment]
@fvbogaert so this means that we don't need Amrita to work on this? Or should she wait till you provide something basic and enhance it?

**Comment by ghost** [comment]
The current solution is probably good enough for now. Closing this issue.

For future enhancements/fixes, we can open a new issue
