### ISSUE TITLE
[TASK] Add BML to test operational status

### ISSUE THREAD

**Issue by LiorAmram** [prplfoundation/prplMesh#1158]
## Description

Currently, prplmesh_utils.sh status returns an operational status determined by parsing the logs.
This creates 2 problems:
1. Any bug in the logs (for example, truncated logs as a result of early roll) might deliver a wrong result.
2. Operational status might be updated in DB and not be reflected in the status check.

Proposed Solution:
beerocks_cli command to test operational status in real-time.
The command will trigger a topology query that will update the DB value, and then BML will check this value to get an updated result.

PR #1194

## Detailed description

![fPDHIyCm58NV-ol2dbhOP3xuO1nZtIXbsAspdGz3vP9beHJJLfCKzDzxku7DWZB4bzB2ETyzzwIPQSEKQIlfZQPaBuHg-Ai6BajwzaL6d3pNWtqbeH06cZUXc2cRcaaoOOMe3J095UFJWNTkSw7u0AHGwc00SvWMHKnAeNoc2Xty3tLaN6cZohe8yVLf_7A9sArdWvGeIcs40hxtkVaOzYD](https://user-images.githubusercontent.com/43096199/79459730-674ff180-7ffc-11ea-94e3-e1c288627e81.png)

**Comment by tomereli** [comment]
Looking good to me. @arnout any comment before starting implementation?

**Comment by arnout** [comment]
What is not clear from the UML: will every topology response trigger an ACTION_BML_TOPOLOGY_RESPONSE or only if it was triggered by BML to begin with? (I vote for the former)

Also not clear is which parameters the ACTION_BML_TOPOLOGY_RESPONSE will have.

**Comment by arnout** [comment]
(Otherwise LGTM of course)
