### ISSUE TITLE
[BUG] run-tests (test_flows.py) occasionaly fails on master (client_capability_query and client_steering_dummy)

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#1164]
It was first noticed by @RanRegev  [on his branch](https://gitlab.com/prpl-foundation/prplMesh/-/jobs/513883964), and today it happened on master.
Logs are available here:
https://gitlab.com/prpl-foundation/prplMesh/-/jobs/515794163

We know it doesn't happen for every run. Here is a second (passing) run on the same commit as the one above: 
https://gitlab.com/prpl-foundation/prplMesh/-/jobs/515886112

**Comment by arnout** [comment]
Another occurrence: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/519062541

**Comment by rmelotte** [comment]
Unfortunately we hit it again with the changes that closed the issue, so re-opening: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/525396180
