### ISSUE TITLE
[TASK] Port upload_to_owncloud.sh to python

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#1185]
## Description

There is a shell script right now to upload all of the logs generated by the certification tests to owncloud automatically.
As part of our efforts to clean up our scripts and workflow for certification tests, we need this to be refactored into a python script.

## Exit criteria

- [ ] A python script exists that uploads logs to owncloud
- [ ] The functionality of the script mirrors that of the existing shell script
- [ ] The script has been tested, and is verified to work

## Detailed description

Please use https://pypi.org/project/webdavclient3/ to do it.

Suggested approach:
1. Install the python module:
`pip install webdavclient3`
2. Make sure you have the correct credentials (bug Frederik, Tomer or Arnout for them)
3. Make a script that connects to our owncloud and uploads a sample file to a new directory.
The shell script reads the credentials from ~/.netrc, you will need to use a different approach:
```python
from webdav3.client import Client
options = {
 'webdav_hostname': "https://ftp.essensium.com/owncloud/remote.php/dav/files",
 'webdav_login':    "login",
 'webdav_password': "password"
}
client = Client(options)
```
Make sure to test that it works by running everything on your own computer. Keep testing whenever you make a change.
4. Now that you know how everything works, restructure the code so that it's nice and readable, with a good division between functions (documented with docstrings), and prepare a PR. See the CONTRIBUTING.md file for how to do that.
It's also a good idea to move configuration (URLs and pathnames) into its own file,so it's easy to edit.
4b. run `flake8` on your code and fix anything that flake8 complains about `flake8 --config <prplmesh_repo>/.flake8 myscript.py`
5. Submit the PR, and we'll do our best to review it :-)
Don't forget to link the PR to this issue

**Comment by tomereli** [comment]
I disagree about using anything other than ~/.netrc. Even if `webdav` doesn't provide an easy way to work with ~/.netrc, it is still a better approach than using a dedicated configuration file. We can simply parse ~/.netrc file to get the password if no password and use were given as arguments.
Regarding the other configuration options, these should be parsed from a yaml file, something like we do in OpenWRT for feeds configuration:
We store `owncloud.options.default` with the default options (minus the credentials ofcourse) - this is part of prplmesh repository.
If a file named `owncloud.options` exists, we use it instead. This allows us the flexibility for testing new options, such as different public links for example, without modifying the script.
