### ISSUE TITLE
[TASK] power_cycle.py: add an "unconditional reboot" feature

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#1186]
## Description

This task is about the power_cycle.py script in [the easymesh_cert repository](https://git.prpl.dev/prplmesh/wfa-certification/easymesh_cert).

At the moment `power_cycle.py` checks if all the configured devices are available, and if not power cycle them using hardware relays.

It happens however that some devices stay reachable, but cannot be used for the certification anymore until they are rebooted.
 
For this reason, we would like to be able to also unconditionally reboot all the devices. Since they remain reachable, we can try to soft-reboot them instead of using the relays.

## Exit criteria

- power_cycle.py has an new option to reboot all the devices no matter if they are reachable or not.

When the option is used:
- the script attempts to connect to each device in parallel, and issue a reboot command. Some devices will have to be accessed using telnet, others using ssh.
- (optional) if the soft-reboot failed for a device and the hardware relay is available, it's rebooted using the relays.

**Comment by abelog** [comment]
[PR](https://git.prpl.dev/prplmesh/wfa-certification/easymesh_cert/-/merge_requests/14/commits) is created.
