### ISSUE TITLE
Dynamic Channel Selection: Scan all available channels

### ISSUE THREAD

**Issue by itayx** [prplfoundation/prplMesh#1216]
The Dynamic Channel Selection feature scans a list of given channels (set by the user), and returns the scan results.
Currently the user must supply the requested channels, but we want to add the option to scan ALL available / supported channels  for a given radio.

To do this we need to add an option when setting the supported channels to also set the channel pool to all supported channels, then when a scan is request be it a single scan or a continuous scan.

After looking into the code, I found two options to add this feature:
1) In the DB function `set_channel_scan_pool`, add a condition that will check the given channel pool and in case the pool contains a single channel with a value of `0` all supported channels will be set as the current channel pool.
2) In the son_managment segments where we set the channel pool (during `SET_CONTINUOUS_PARAMS_REQUEST` & `START_SCAN_REQUEST`) check the requested channel pool and if the channel pool contains a single channel with a value of `0` set the new channel pool in the DB to all the radio's supported channels
3) in the DCS task, when checking the channel pool from the DB the task will check if the channel pool contains a single channel with a value of `0`, in that case the task will then send as part of the scan request all the supported channels for that radio.

Using options (1) and (3) will result in the least amount of code changed.
Using option (1) and (2) will result in the DB containing all supported channels in the DB, while in option (3) the channel pool stored in the DB will be the "All Channels" channel pool, but without the actual channels

I believe that using option (3) is the best solution.
When checking the channel pool it will show that the user intended that all supported channels are to be used in the upcoming scan.

**Comment by arnout** [comment]
(1) and (3) sound equally appropriate to me. Since the supported channels list doesn't change over the lifetime of a node, I think it's appropriate to set the channel pool explicitly in the db. So personally I'd have a slight preference for (1), but I don't think it matters much.

Regardless of the chosen approach, I have one other remark: why not use an empty channel pool as the "marker" for all channels, instead of the fake channel 0? I think that
- an empty channel pool has no other meaning;
- it's more intuitive;
- it's much more easy to check.

**Comment by itayx** [comment]
> (1) and (3) sound equally appropriate to me. Since the supported channels list doesn't change over the lifetime of a node, I think it's appropriate to set the channel pool explicitly in the db. So personally I'd have a slight preference for (1), but I don't think it matters much.
> 
> Regardless of the chosen approach, I have one other remark: why not use an empty channel pool as the "marker" for all channels, instead of the fake channel 0? I think that
> 
> * an empty channel pool has no other meaning;
> * it's more intuitive;
> * it's much more easy to check.
@arnout 

The reason being that, currently on initialization the channel pool starts empty.
If we request a scan before setting the channel pool (though it **will** require to set the dwell time), the scan will trigger on all channels seeing as the initial pool is empty.
This is incorrect as we want the user to actively choose to scan on all channels by setting it to a designated identifier, and fail to scan if no channel pool is set.
