### ISSUE TITLE
[BUG] wireless configuration is not reset between runs

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#1221]
At the moment we don't reset the wireless configuration of the rax40 in-between different test runs. If a branch breaks the configuration, it's going to stay in a broken state until something or someone resets it. 

In a product, we can't just delete the user wireless configuration, so we can't do that from the ipk install script.
In our case however, we're not interested in keeping the existing configuration, so we could delete and re-create it from our deploy_ipk.sh script for example.

**Comment by arnout** [comment]
Unfortunately, we have the eternal problem that over time, we may require different configuration on the device. So somehow we should keep the configuration in sync with the source...

The easiest way to do that would be to store the uci config for wireless and prplmesh in `ci/netgear-rax40`. That is, assuming that there is no device-specific config in there (e.g. MAC addresses). Then the deploy script can copy it from there.

But maybe that's exactly what you propose here :-)

**Comment by rmelotte** [comment]
It's not strictly needed for now, so I've put it back in the backlog.
