### ISSUE TITLE
[TASK] Add gitlab schedules for restarting testbeds

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#1226]
## Description

- Separate schedule for every testbed
- Requires modification to the .gitlab-ci.yml file

**3 SPs**

## Exit criteria

Each testbed (BLR, Belgium) has a schedule which restarts the testbed once a day.

**Comment by arnout** [comment]
Maybe better do it as a cron job on the certification testbed itself. It would first stop the runner, then reboot all devices, then start the runner again. Disadvantage is that it would kill any running job (which may be a good thing, actually). Also you won't get logs for it in gitlab-ci. Advantage is that it's easier to control when this happens.

If it is done in gitlab-ci.yml, I propose to do that in a separate branch which only has gitlab-ci.yml and perhaps any supporting scripts. The schedule can refer to a branch so no worry there. With a branch, we can bypass PRs, and we can make it a protected branch to which only a few people have direct commit access. The branch could even be on gitlab.com only.
