### ISSUE TITLE
[TASK] Add support for enforcing testbed on PR

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#1229]
## Description

Add additional tag to **both** testbeds:
**certs-tests-intel-1**
**certs-tests-essensium-1**

This will allow developers to change the .gitlab-ci.yml to enforce a specific testbed for debugging.

**2 SPs**

**Comment by arnout** [comment]
Done for certs-tests-essensium-1 (cfr. https://gitlab.com/prpl-foundation/prplMesh/runners/1479637).

Moved to #1228 for certs-tests-intel-1 (setting the tags is a command-line option of gitlab-runner while registering the runner).
