### ISSUE TITLE
[TASK] Enable PPA acceleration for RAX40

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#1239]
## Description

Due to the bug described in #1220, prplmesh init script includes `ppacmd exit` which disables acceleration every time prplmesh is started.
As part of rebase to prplwrt, this should be reverted. In addition, in order for acceleration to work, when setting bridged mode, we need also to set it in `/etc/config/ppa` (which does not exist in the prplwrt version we have now).

Repeater mode (WAN bridged mode):
```
uci set network.lan.ifname='eth1 eth0_1 eth0_2 eth0_3 eth0_4'
uci set network.wan.ifname=''
uci commit network
uci set ppa.lan.ifname='eth1 eth0_1 eth0_2 eth0_3 eth0_4'
uci set ppa.wan.ifname=''
uci commit ppa
/etc/init.d/network reload
/etc/init.d/ppa restart
``` 

Gateway mode (normal WAN):
```
uci set network.lan.ifname='eth1 eth0_1 eth0_2 eth0_3 eth0_4'
uci set network.wan.ifname=''
uci commit network
uci set ppa.lan.ifname='eth1 eth0_1 eth0_2 eth0_3 eth0_4'
uci set ppa.wan.ifname=''
uci commit ppa
/etc/init.d/network reload
/etc/init.d/ppa restart
```

## Exit criteria

Verify that with the above configuration in repeater mode, 4.2.3 test variants pass 20/20 times! The bug was hard to find, one time pass is not enough!

**Comment by ghost** [comment]
@rmelotte Could you test whether PPA acceleration works again with the new prplWrt?
