### ISSUE TITLE
[BUG] [UGW] monitor crash after client association

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#1241]
spotted on c960f8288198e4ce3b2caba73cf258b19b8547b2

steps to reproduce:

1. flash a version with latest prplmesh
2. configure SSID
3. print bml-conn-map**
4. connect a client 

expected behavior:
steps 1-4 are successful

actual behavior:
steps 1-3 are successful
step 4 results with a beerocks-agent crash
attached logs of /var/log/messaged (UGW) and beerocks logs

update:
the issue was introduced as part of the following PR - need to understand what change in the PR caused it:
https://github.com/prplfoundation/prplMesh/pull/888/commits

[prplmesh_logs.tar.gz](https://github.com/prplfoundation/prplMesh/files/4592143/prplmesh_logs.tar.gz)

**Comment by tomereli** [comment]
Triggered a manual pipeline to see if this issue is reproduced on RAX40 on master: https://gitlab.com/prpl-foundation/prplMesh/pipelines/143617662

Result - PASS. This doesn't happen on latest master on RAX40.

**Comment by arnout** [comment]
Would it be possible to attach the beerocks logs of the failure? All of them please.

**Comment by adam1985d** [comment]
> Would it be possible to attach the beerocks logs of the failure? All of them please.

done

**Comment by tomereli** [comment]
Please also provide `/opt/prplmesh/scripts/prplmesh_utils.sh status` output after the issue occured.

**Comment by adam1985d** [comment]
> Please also provide `/opt/prplmesh/scripts/prplmesh_utils.sh status` output after the issue occured.

in UGW the mechanism works as such that in case any of the following processes is closed -the rest of processes are killed as well (to prevent multiple controller processes and such):
controller
main agent
agent wlan0/2

so the result is that no process is up

**Comment by itayx** [comment]
The SSIDs were configured to TEST_SSID_B611_24G & TEST_SSID_B611_5G for each radio.
When connecting to the 2.4G SSID the client connected with no issues
but when I tried connecting to the 5G SSID I noticed the crush

### Initial status & bml_conn_map
```
root@ugwcpe:/# /opt/prplmesh/scripts/prplmesh_utils.sh status
/opt/prplmesh/scripts/prplmesh_utils.sh: status
8739 /opt/prplmesh/bin/beerocks_controller
8740 /opt/prplmesh/bin/beerocks_agent
8833 /opt/prplmesh/bin/beerocks_agent
8835 /opt/prplmesh/bin/beerocks_agent
20460 /opt/prplmesh/bin/beerocks_monitor
21750 /opt/prplmesh/bin/beerocks_monitor
OK Main agent operational
OK wlan0 radio agent operational
OK wlan2 radio agent operational
root@ugwcpe:/# /opt/prplmesh/bin/beerocks_cli -c bml_conn_map
bml_connect: return value is: BML_RET_OK, Success status
bml_nw_map_query: return value is: BML_RET_OK, Success status

GW_BRIDGE: name: GW_MASTER, mac: 02:9a:96:fb:20:b1, ipv4: 192.168.1.1
    ETHERNET: mac: 02:9a:96:fb:20:b2
    RADIO: wlan0 mac: ac:9a:96:fb:20:b4, ch: 6, bw: 20, freq: 2437MHz
        fVAP[0]: wlan0.0 bssid: ac:9a:96:fb:20:b5, ssid: TEST_SSID_B611_24G
    RADIO: wlan2 mac: ac:9a:96:fb:20:b7, ch: 44, bw: 160H, freq: 5220MHz
        fVAP[0]: wlan2.0 bssid: ac:9a:96:fb:20:b8, ssid: TEST_SSID_B611_5G
bml_disconnect: return value is: BML_RET_OK, Success status
```
### After connecting to the 2.4G SSID
```
root@ugwcpe:/# /opt/prplmesh/scripts/prplmesh_utils.sh status
/opt/prplmesh/scripts/prplmesh_utils.sh: status
8739 /opt/prplmesh/bin/beerocks_controller
8740 /opt/prplmesh/bin/beerocks_agent
8833 /opt/prplmesh/bin/beerocks_agent
8835 /opt/prplmesh/bin/beerocks_agent
20460 /opt/prplmesh/bin/beerocks_monitor
21750 /opt/prplmesh/bin/beerocks_monitor
OK Main agent operational
OK wlan0 radio agent operational
OK wlan2 radio agent operational
root@ugwcpe:/# /opt/prplmesh/bin/beerocks_cli -c bml_conn_map
bml_connect: return value is: BML_RET_OK, Success status
bml_nw_map_query: return value is: BML_RET_OK, Success status

GW_BRIDGE: name: GW_MASTER, mac: 02:9a:96:fb:20:b1, ipv4: 192.168.1.1
    ETHERNET: mac: 02:9a:96:fb:20:b2
    RADIO: wlan0 mac: ac:9a:96:fb:20:b4, ch: 6, bw: 20, freq: 2437MHz
        fVAP[0]: wlan0.0 bssid: ac:9a:96:fb:20:b5, ssid: TEST_SSID_B611_24G
            CLIENT: mac: 78:92:9c:f7:fb:11, ipv4: 0.0.0.0, name: N/A, ch: 6, bw: 20, rx_rssi: -34
    RADIO: wlan2 mac: ac:9a:96:fb:20:b7, ch: 44, bw: 160H, freq: 5220MHz
        fVAP[0]: wlan2.0 bssid: ac:9a:96:fb:20:b8, ssid: TEST_SSID_B611_5G
bml_disconnect: return value is: BML_RET_OK, Success status
```
### After connecting to the 5G radio
```
root@ugwcpe:/# /opt/prplmesh/scripts/prplmesh_utils.sh status
/opt/prplmesh/scripts/prplmesh_utils.sh: status
FAIL Main agent operational
FAIL wlan0 radio agent operational
FAIL wlan2 radio agent operational
root@ugwcpe:/# /opt/prplmesh/bin/beerocks_cli -c bml_conn_map
ERROR 14:12:07:188 <2008738256> bml_internal.cpp[342] --> Failed connecting to Beerocks Platform Manager: connect() to /tmp/beerocks/uds_platform_manager failed: Connection refused
ERROR 14:12:07:189 <2008738256> bml_internal.cpp[215] --> connect - connect_to_platform failed!
ERROR 14:12:07:191 <2008738256> bml.cpp[50] --> bml_connect - pBML->connect failed
bml_connect: return value is: BML_RET_CONNECT_FAIL, Connection to Beerocks failed
cli_bml: Can't connect to master, exit...
root@ugwcpe:/# 
```
### Connecting to the 5G from the start
After relaunching the prplMesh
I tried to join the 5G SSID again, and managed to connect without issues
'''
root@ugwcpe:/# /opt/prplmesh/scripts/prplmesh_utils.sh status
/opt/prplmesh/scripts/prplmesh_utils.sh: status
23467 /opt/prplmesh/bin/beerocks_controller
23468 /opt/prplmesh/bin/beerocks_agent
23479 /opt/prplmesh/bin/beerocks_agent
23481 /opt/prplmesh/bin/beerocks_agent
23577 /opt/prplmesh/bin/beerocks_monitor
23582 /opt/prplmesh/bin/beerocks_monitor
OK Main agent operational
OK wlan0 radio agent operational
OK wlan2 radio agent operational
root@ugwcpe:/# /opt/prplmesh/bin/beerocks_cli -c bml_conn_map
bml_connect: return value is: BML_RET_OK, Success status
bml_nw_map_query: return value is: BML_RET_OK, Success status

GW_BRIDGE: name: GW_MASTER, mac: 02:9a:96:fb:20:b1, ipv4: 192.168.1.1
    ETHERNET: mac: 02:9a:96:fb:20:b2
    RADIO: wlan0 mac: ac:9a:96:fb:20:b4, ch: 6, bw: 20, freq: 2437MHz
        fVAP[0]: wlan0.0 bssid: ac:9a:96:fb:20:b5, ssid: TEST_SSID_B611_24G
    RADIO: wlan2 mac: ac:9a:96:fb:20:b7, ch: 44, bw: 160H, freq: 5220MHz
        fVAP[0]: wlan2.0 bssid: ac:9a:96:fb:20:b8, ssid: TEST_SSID_B611_5G
            CLIENT: mac: 78:92:9c:f7:fb:11, ipv4: 0.0.0.0, name: N/A, ch: 44, bw: 160H, rx_rssi: -29
bml_disconnect: return value is: BML_RET_OK, Success status
```
Then when I tried changing the SSID to the 2.4G I got the same crush as before
```
root@ugwcpe:/# /opt/prplmesh/scripts/prplmesh_utils.sh status
/opt/prplmesh/scripts/prplmesh_utils.sh: status
FAIL Main agent operational
FAIL wlan0 radio agent operational
FAIL wlan2 radio agent operational
root@ugwcpe:/# 
root@ugwcpe:/# /opt/prplmesh/bin/beerocks_cli -c bml_conn_map
ERROR 14:52:55:851 <1999669712> bml_internal.cpp[342] --> Failed connecting to Beerocks Platform Manager: connect() to /tmp/beerocks/uds_platform_manager failed: Connection refused
ERROR 14:52:55:853 <1999669712> bml_internal.cpp[215] --> connect - connect_to_platform failed!
ERROR 14:52:55:855 <1999669712> bml.cpp[50] --> bml_connect - pBML->connect failed
bml_connect: return value is: BML_RET_CONNECT_FAIL, Connection to Beerocks failed
cli_bml: Can't connect to master, exit...
```

**Comment by arnout** [comment]
As mentioned orally in the sync meeting, it looks like the remove-during-iteration problem:
```
void backhaul_manager::remove_client_from_all_radios(sMacAddr &client_mac)
{
    for (const auto &slave : slaves_sockets) {
        const auto &associated_clients_map = slave->associated_clients_map;
        for (const auto &client : associated_clients_map) {
            if (client.second.find(client_mac) != client.second.end()) {
                slaves_sockets.remove(slave);
            }
        }
    }
}
```
Although it's remove() here and not erase(), I assume it still invalidates the iterator from the outer loop.

However, now I see this code, it is completely bogus anyway: it will remove the *slave* if the client was associated with it, rather than removing the client...

I suspect this really should have been
```
void backhaul_manager::remove_client_from_all_radios(sMacAddr &client_mac)
{
    for (const auto &slave : slaves_sockets) {
        const auto &associated_clients_map = slave->associated_clients_map;
        for (const auto &clientmap : associated_clients_map) {
            auto it = clientmap.second.find(client_mac);
            if (it != clientmap.second.end()) {
                clientmap.second.erase(it);
           }
        }
    }
}
```

@CoralMalachi please comment.

**Comment by arnout** [comment]
@itayx Please double-check that #1254 fixes it.
