### ISSUE TITLE
[BUG] test_flows.py : beacon metrics query

### ISSUE THREAD

**Issue by RanRegev** [prplfoundation/prplMesh#1272]
**Bug Descrition**
There *might* be inconsistency between the specification and the way beacon metrics query is implemented.

Here we have two tlvs for 0x8011:
* according to the SPEC.
* as implemented

The one that is according to the spec does not work, it fails somewhere along the way.
The incorrect one works.

Investigation is needed.

The probably correct tlv according to the spec:
                tlv(0x99, 0x0016, "{11:22:33:44:55:66 0x73 0xFF 0XFFFFFFFFFFFF 0x02 0x00 0x01 0x02 0x73 0x24 0x30 0x00}"))

This is what is sent (please verify against test_flow.py code):
                tlv(0x99, 0x0014,
                    associated: "{11:22:33:44:55:66}
                    op class: 0x73
                    channel:  0xff
                    bssid: 0xffffffffffff
                    reporting detail: 0x02
                    ssid length: 0x00
                    ap-channel-report-list-len: 0x01
                    inner-channel-report-list-len: 0x02
                    operating class: 0x73
                    channels: 0x24 0x30
                    number of element id: 0"))

**Comment by arnout** [comment]
The problem was that `0XFF` was used in the string, and ucc_listener only supports `0x`.
