### ISSUE TITLE
[TASK] update prplmesh_utils.sh to use bml_get_device_operational_radios

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#1303]
prplmesh_utils.sh status returns an operational status determined by parsing the logs.
In some platforms logs wrap around could return "fail" status although system is operational state.  
Currently, prplmesh_utils.sh status returns an operational status determined by parsing the logs.

when https://github.com/prplfoundation/prplMesh/pull/1194 gets merged, need to update update prplmesh_utils.sh to use new api  bml_get_device_operational_radios instead\

sub tasks:

- [x] use in beerocks_utiils.sh
- [x] use in UTAF (internal intel repos)
- [ ] tests/openwrt/test_status.sh
- [ ] tools/docker/README.md
- [ ] tools/docker/test.sh

try using something like this:
`docker exec bash -it gateway-${USER} "${INSTALL_DIR}/bin/beerocks_cli -c  bml_get_device_operational_radios ${MAC}"`

**Comment by itayx** [comment]
After syncing with @kantera800 & @vitalybu we agreed on the following:
The BML cannot be used on repeaters seeing as there is no controller, therefore the BML cli would not exist.
So to verify the operational status, first we need to check if the BML cli is present
If it is, then the BML command `bml_get_device_operational_radios` can and should be used to determine the operational status.
If there is not BML cli, meaning the platform acts as a repeater, we should default to the logs, to verify the operational status.

**Comment by arnout** [comment]
>  If there is not BML cli, meaning the platform acts as a repeater, we should default to the logs, to verify the operational status.

That's really annoying...

However, for now, I don't think we ever have a situation where we don't have a prplmesh controller.
- In UTAF, controller and gateway run on the same device.
- In test_flows / boardfarm, there's always a prplmesh controller in docker.
- In openwrt test_status, controller and gateway run on the same device.
- In certification testbed, there's no need for checking status.

So I think we should simply replace all the calls to `prplmesh_utils.sh status`, and then remove that function from the script. Current instances:
- UTAF (if not already removed)
- tests/openwrt/test_status.sh
- tools/docker/README.md
- tools/docker/test.sh

The latter script should be removed entirely, and instead its callers tests/boardfarm_plugins/boardfarm_prplmesh/devices/prplmesh_docker.py and tests/test_gw_repeater.sh should be replaced.
