### ISSUE TITLE
[BUG] son slave: potentially use of nullptr as a reference

### ISSUE THREAD

**Issue by RanRegev** [prplfoundation/prplMesh#1304]
**Describe the bug** -
`sd` is used in [this line](https://github.com/prplfoundation/prplMesh/blob/master/agent/src/beerocks/slave/son_slave_thread.cpp#L380) without checking it is not pointing to nullptr.
This change was [introduced](https://github.com/prplfoundation/prplMesh/commit/761b0e2fdf21b5a43882543c09f1523cf5d8684a#diff-f3dcf05057f5ecc09b7bc39daa3fe7f2R341) as result of an oral discussion that stated that it is better to have a [reference](https://github.com/prplfoundation/prplMesh/commit/761b0e2fdf21b5a43882543c09f1523cf5d8684a#diff-4b5d800f00b53363beb354fbdc27bd75R136) in the function declaration instead of a pointer in the function declaration and immediately return when the pointer is nullptr in the function's body. It means also that it leaves the responsibility of supplying a real object to the caller.
However this responsibility, introduced in the same commit, was not taken.

## Expected behavior
Add an `if statement` before dereferencing `sd`.

**Comment by arnout** [comment]
The function you point to starts with the following code, which asserts that sd != nullptr:
```
if (master_socket == nullptr) {
        LOG(WARNING) << "master_socket == nullptr";
        return true;
    } else if (master_socket != sd) {
        LOG(DEBUG) << "Unknown socket, cmdu message type: " << int(cmdu_message_type); //TODO:
    }
```
Well, the `return false` is missing in the second branch, so maybe that's the problem?

**Comment by RanRegev** [comment]
Well, it appears that you are right, the only missing part is the `return` statement.
logically there is no way that sd is `null` if there were a return there.
*However* this is badly stated, from maintainability and readability point of view it is very hard to see. One have to create a truth table for both variables to expose this fact.

> To do: add a return statement
