### ISSUE TITLE
[feature] agent: backhaul: sRadioInfo refactoring

### ISSUE THREAD

**Issue by RanRegev** [prplfoundation/prplMesh#1305]
**Current Situation** -

`struct sRadioInfo` is not self explanatory and therefore is hard to maintain.
Farther data constructions ([slaves_sockets](https://github.com/prplfoundation/prplMesh/blob/master/agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h#L183), [slave_iface_socket](https://github.com/prplfoundation/prplMesh/blob/master/agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h#L168))  built on it makes it even harder to understand and maintain a coherent, once written, debugged code. One must be an _expert_ in this data structure and the constructions on top it to get required information.

**Prefferred Situation** -
Turn `sRadioInfo` structure and the structures on top of it into separated, standalone, classes with clear and concise interfaces. Via these interfaces one is able to query any information with a clear and simple function call. All future data queries required from these data structures will be implemented internally, leaving the user unaware of the internal complexity.

**Comment by tomereli** [comment]
This is not a bug, but an enhancement.
