### ISSUE TITLE
Implement using C

### ISSUE THREAD

**Issue by mingshentu** [prplfoundation/prplMesh#1311]
Is there any prplMesh project implemented by C language ? It's not convenient to do porting current C++ implemented project to my router, because I would not like to support C++ library. 
Thanks in advance.

**Comment by ghost** [comment]
Hi @mingshentu, 
Unfortunately, the prplmesh project is developed mostly in C++. This was a design decision at the start of the project that can't be changed now.
There is no alternative C implementation, nor are there any plans to "port" the code to C.

Usually, there *is* a way to get a c++ cross-compiler for a router, most BSPs include them. So unless it's a really exotic architecture, you should be able to port prplmesh to it.
If you need help, please ask about this in slack.
Thank you.

**Comment by mingshentu** [comment]
@fvbogaert I'll try it on my router, thanks a lot.
