### ISSUE TITLE
[TASK] Refactor AP metrics response collection

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#1328]
## Description

The AP metrics query/response flow requires sending the query to several radios, collecting the responses from the radios, and finally sending out all the responses in a single message.

#1231 implemented that, but it has a few shortcomings:
- MID is not stored;
- response is not properly checked against expected responses;
- if several BSSIDs are queried, there is one query per BSSID -> redundant messages;
- corner cases could be checked better;
- instead of collecting responses in structures, it might be better to construct a cmdu_tx directly;
- #1388 introduced a special case for responses that are generated directly by the monitor, which means that a request with that "magic MID" will not work correctly.

**Comment by mariomaz** [comment]
Provided solution must consider also the cases in which AP Metrics Response message must be sent not as a response to a previous AP Metrics Query message, but when an internal event occurs; like when periodic reporting metrics interval has elapsed or when channel utilization crosses configured threshold value.

**Comment by VladyslavTupikin** [comment]
Plan for refactoring is:

1. handle_ap_metrics_query should just fill up expected_bssid vector and forward the query.
   -- save mid
   -- clear expected_bssid
   -- clear response (just do new message creation)

2. For certification 4.7.5 create 1 big ap metric query and send it to all slaves.
   -- save mid
   -- clear expected_bssid
   -- clear response (just do new creation)
   -- //UINT16_MAX should be changed on 0, remove comment above 

3. For handle_slave_ap_metrics_response
   -- check received mid with saved:
        if (mid != saved_mid) {
            if (mid == 0) 
               forward it to the controller;
               return;
            else 
               drop;
        }
   -- create tlvs according to the information from cmdu_rx
   -- remove all useless structures

Commits:
1st create stuff from UML and modify handle_ap_metrics_query
2nd Modifying send_slave_ap_metric_query_message, also add condition if (mid != saved_mid)
3rd Change structures to the cmdu_tx in handle_slave_ap_metrics_response
4th Remove all structures

**Comment by VladyslavTupikin** [comment]
![image](https://user-images.githubusercontent.com/61505283/84124014-4f687d00-aa43-11ea-9afa-3729e6ba887f.png)

**Comment by arnout** [comment]
@mariomaz @RanRegev Please review the design posted by @VladyslavTupikin

**Comment by mariomaz** [comment]
> For certification 4.7.5 create 1 big ap metric query and send it to all slaves.

Please clarify what "create 1 big ap metric query" means.

Step 2 is executed when periodic reporting interval time elapses. If this happens while a previously received AP Metrics Query message is still in progress, such message will never be replied.

Step 3 of plan has a flaw: saved_mid can be 0 if the mid of received AP Metrics Query message was 0. This will happen on each mid value wrap-around.

**Comment by VladyslavTupikin** [comment]
"create 1 big ap metric query" means need to create 1 query with 1 tlv which includes all BSSIDs instead of creating 1 query for 1 BSSID.

For step 2 we have a timeout between messages 600ms. it is enough for processing the ap metrics message.

**Comment by mariomaz** [comment]
> For step 2 we have a timeout between messages 600ms. it is enough for processing the ap metrics message.

Periodic reporting interval might elapse just 1 ms after AP Metrics Query message has been received. The opposite is also true: while in the middle of processing a periodic reporting event, agent could receive an AP Metrics Query  message. In both cases, saved mid will be overwritten.

**Comment by arnout** [comment]
About mixing periodic reporting and an explicit query: I believe the controller simply shouldn't do that.
If we would want to support this use case, we would need two separate instances of the expected_response structure: one for the periodic reporting, and a separate one for the explicit query. Still, I don't think we should bother doing that. In practice, if the controller configures us for periodic reporting, it would be stupid to also ask for an explicit one, so we can assume that this won't happen. Also, in case it happens, the only result that one of the responses (either the periodic one or the requested one) doesn't come. This is no worse than if the packet was simply lost in the network, which is a situation that the controller should be able to handle as well.

Regarding the flaw of mid 0 handling: this issue exists for all requests for which we send a response. Cfr. #1391. So it doesn't need to be handled as part of this issue. Also, again, the worst that happens is that a packet with the wrong MID is sent, which has the same effect as not sending it at all.

**Comment by mariomaz** [comment]
To allow periodic reporting and explicit queries, a std::map<MID, sExpectedApMetricsResponse>  would do the job and it shouldn't be very difficult to implement. 

There are two different issues with MID 0: the one described in #1391 and another one due to using 0 (or UINT16_MAX) as a special value when it's not. #1391 will not solve the second issue so it should be handled here.

BTW, UINT16_MAX is used instead of 0 to distinguish the response messages sent by slave. Slave sends AP Metrics Response messages in response to AP Metrics Query messages and also because channel utilization crosses a threshold. In the first case, backhaul manager has to wait until all slaves have sent their responses whilst in the second case, message must be forwarded as is to the controller.

**Comment by arnout** [comment]
> To allow periodic reporting and explicit queries, a std::map<MID, sExpectedApMetricsResponse> would do the job and it shouldn't be very difficult to implement.

Well... to make it robust, you should also handle the case when the expected responses never come, and add some timeout or something...


> There are two different issues with MID 0: the one described in #1391 and another one due to using 0 (or UINT16_MAX) as a special value when it's not. #1391 will not solve the second issue so it should be handled here.
> 
> BTW, UINT16_MAX is used instead of 0 to distinguish the response messages sent by slave. Slave sends AP Metrics Response messages in response to AP Metrics Query messages and also because channel utilization crosses a threshold. In the first case, backhaul manager has to wait until all slaves have sent their responses whilst in the second case, message must be forwarded as is to the controller.

If the channel utilization is crossed (i.e. 4.7.6) at the time we are not in the middle of a periodic reporting (4.7.5), there is no problem (MID 0 is not the current expected one). If it *is* crossed while we're in the middle of a periodic reporting, there is also no problem: we will get two responses. The first one (which could be due to the periodic reporting or due to the treshold crossing, doesn't matter) will be included in the periodic report, and the second one will be forwarded as is. Which one was triggered by channel utilization crossing and which one was triggered by periodic doesn't matter.

**Comment by RanRegev** [comment]
I don't feel comfortable with "it will be ok". Also I think the code does not support it.
Looking at the code of `agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp` from #1412 I am not sure there is no mixing/clearing of the bssid _during_ handling of the responses.
it means that this flow would be wrong:
* receiving response for direct request
* receiving response for periodic
* receiving response for direct request
But I might be wrong here.
