### ISSUE TITLE
[BUG] dwpal: driver reports wrong channel in VHT80

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#1352]
After the update to the UGW 8.4.1 release, the driver is reporting an invalid operating channel in VHT80 mode.
```
DEBUG 09:49:20:652 <2009627040> son_slave_thread.cpp[4732] --> Current channel 140 bw 3 oper_class 0
```
bw 3 is 80MHz, so operating class should be 128 instead of 0. However, in that operating class, the allowed center frequencies are 42, 56, 106, 122, 138, 155. The reported channel is the starting channel instead of the center frequency, so for 80MHz that would be channel 132, not 140.

Example of failing certification test that triggers this: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/569918816

As a workaround, we now configured the radio to use HT only.

**Comment by arnout** [comment]
Note that in the supported channel list, we have this:
```
 ch = 36 | dfs = 30 | bw = 80 | tx_pow = 0 | noise = 0 [dbm] | bss_overlap = 0
 ch = 40 | dfs = 30 | bw = 80 | tx_pow = 0 | noise = 0 [dbm] | bss_overlap = 0
 ch = 44 | dfs = 30 | bw = 80 | tx_pow = 0 | noise = 0 [dbm] | bss_overlap = 0
 ch = 48 | dfs = 30 | bw = 80 | tx_pow = 0 | noise = 0 [dbm] | bss_overlap = 0
 ch = 52 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 56 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 60 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 64 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 100 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 104 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 108 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 112 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 116 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 120 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 124 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 128 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 132 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 136 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 140 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 144 | dfs = 24 | bw = 80 | tx_pow = 1 | noise = 0 [dbm] | bss_overlap = 0
 ch = 149 | dfs = 30 | bw = 80 | tx_pow = 0 | noise = 0 [dbm] | bss_overlap = 0
 ch = 153 | dfs = 30 | bw = 80 | tx_pow = 0 | noise = 0 [dbm] | bss_overlap = 0
 ch = 157 | dfs = 30 | bw = 80 | tx_pow = 0 | noise = 0 [dbm] | bss_overlap = 0
 ch = 161 | dfs = 30 | bw = 80 | tx_pow = 0 | noise = 0 [dbm] | bss_overlap = 0
 ch = 165 | dfs = 30 | bw = 80 | tx_pow = 0 | noise = 0 [dbm] | bss_overlap = 0
```

So *all* channels are added to the supported channels list, even the ones which don't exist in 80MHz.

I don't think this is related however.

**Comment by arnout** [comment]
This one looks interesting:
```
TRACE 09:47:38:505 <1999768824> ap_wlan_hal_dwpal.cpp[1714] --> process_dwpal_event - opcode: |DFS-CAC-COMPLETED|
DEBUG 09:47:38:505 <1999768824> ap_wlan_hal_dwpal.cpp[2351] --> <3>DFS-CAC-COMPLETED wlan2 success=1 freq=5700 ht_enabled=0 chan_offset=0 chan_width=3 cf1=5690 cf2=0 timeout=60
DEBUG 09:47:38:506 <1999768824> ap_wlan_hal_dwpal.cpp[2386] --> numOfValidArgs[2]= 1 success= 1
DEBUG 09:47:38:507 <1999768824> ap_wlan_hal_dwpal.cpp[2388] --> numOfValidArgs[3]= 1 freq= 5700
DEBUG 09:47:38:507 <1999768824> ap_wlan_hal_dwpal.cpp[2390] --> numOfValidArgs[4]= 1 timeout= 60
DEBUG 09:47:38:507 <1999768824> ap_wlan_hal_dwpal.cpp[2392] --> numOfValidArgs[5]= 1 chan_width= 3
```
cf1=5690 is the center frequency (which is not parsed by us). 5690 is channel 138, so it is correct. I don't know why it reports freq=5700 (= channel 140).

**Comment by arnout** [comment]
Looking at the iwlwav hostapd source code, this is where the event data is set:
```c
static void nl80211_radar_event(struct wpa_driver_nl80211_data *drv,
				struct nlattr **tb)
{
...
	data.dfs_event.freq = nla_get_u32(tb[NL80211_ATTR_WIPHY_FREQ]);
...
	/* Get VHT params */
	if (tb[NL80211_ATTR_CHANNEL_WIDTH])
		data.dfs_event.chan_width =
			convert2width(nla_get_u32(
					      tb[NL80211_ATTR_CHANNEL_WIDTH]));
	if (tb[NL80211_ATTR_CENTER_FREQ1])
		data.dfs_event.cf1 = nla_get_u32(tb[NL80211_ATTR_CENTER_FREQ1]);
	if (tb[NL80211_ATTR_CENTER_FREQ2])
		data.dfs_event.cf2 = nla_get_u32(tb[NL80211_ATTR_CENTER_FREQ2]);
...
}
```

So it looks like the information is coming straight from the driver.

**Comment by yaniv-yitzhak** [comment]
freq=5700 is the primary frequency, where the beacons are sent.

**Comment by michael-vassernis** [comment]
Hi @arnout ,
on our system (and I think also all other), when we sit on 80mhz, for example ch 132-144 cf1=138, the actual definition of the channel is primary + bw, not cf1 + bw.
the primary (in your above comments) was 140, which means we beacon on this frequency, and also all management goes on this channel.
this could've also been 132, 136, 140 & 144. but not 138.

when a client that wishes to connect to our AP scans for our SSID, it goes over all channel 32 ... 132, 136, 140, 144, .....
it will find us when it jumps to channel 140, and either catches our beacon or sends us a probe request. it doesn't jump to 138.

please see: https://en.wikipedia.org/wiki/List_of_WLAN_channels

BR,
Michael

**Comment by michael-vassernis** [comment]
if you do "iw phy", you will see:
                Frequencies:
                        * 5180 MHz [36] (30.0 dBm)
                        * 5200 MHz [40] (30.0 dBm)
                        * 5220 MHz [44] (30.0 dBm)
                        * 5240 MHz [48] (30.0 dBm)
                        * 5260 MHz [52] (24.0 dBm) (no IR, radar detection)
                        * 5280 MHz [56] (24.0 dBm) (no IR, radar detection)
                        * 5300 MHz [60] (24.0 dBm) (no IR, radar detection)
                        * 5320 MHz [64] (24.0 dBm) (no IR, radar detection)
                        * 5500 MHz [100] (24.0 dBm) (no IR, radar detection)
                        * 5520 MHz [104] (24.0 dBm) (no IR, radar detection)
                        * 5540 MHz [108] (24.0 dBm) (no IR, radar detection)
                        * 5560 MHz [112] (24.0 dBm) (no IR, radar detection)
                        * 5580 MHz [116] (24.0 dBm) (no IR, radar detection)
                        * 5600 MHz [120] (24.0 dBm) (no IR, radar detection)
                        * 5620 MHz [124] (24.0 dBm) (no IR, radar detection)
                        * 5640 MHz [128] (24.0 dBm) (no IR, radar detection)
                        * 5660 MHz [132] (24.0 dBm) (no IR, radar detection)
                        * 5680 MHz [136] (24.0 dBm) (no IR, radar detection)
                        * 5700 MHz [140] (24.0 dBm) (no IR, radar detection)
                        * 5720 MHz [144] (24.0 dBm) (no IR, radar detection)
                        * 5745 MHz [149] (30.0 dBm)
                        * 5765 MHz [153] (30.0 dBm)
                        * 5785 MHz [157] (30.0 dBm)
                        * 5805 MHz [161] (30.0 dBm)
                        * 5825 MHz [165] (30.0 dBm)

**Comment by arnout** [comment]
I created #1395 for a full solution. I don't think we need to fix this issue individually, so closing.
