### ISSUE TITLE
[BUG] client's IP no updated in monitor after  DHCP NOTIFICATION 

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#1371]
**Describe the bug** -
In case client DHCP notification arrives after start monitoring client request  event , then client's IP will not be updated and remain 0.0.0.0 .

13:17:47:952780 debug: beerocks_agent_wlan0: <1924551744> son_slave_thread.cpp[524] --> **START_MONITORING_REQUEST**: mac=ca:e4:dc:90:10:54 ip=**0.0.0.0** bridge_4addr_mac=00:00:00:00:00:00
13:17:48:726366 debug: beerocks_agent_wlan0: <1924551744> son_slave_thread.cpp[1526] --> **ACTION_DHCP_LEASE_ADDED_NOTIFICATION** mac ca:e4:dc:90:10:54 ip = **192.168.0.168** name=Galaxy-S10

As a result monitor rssi will always send ARP request to zero target IP without getting any answer and will stuck in endless timeout loop.

## platform

RDKB

## Steps to reproduce

1. Build
2. Run controller & agent
3. connect client to one of the APs radios
4. See in monitor logs that ARP requests are sent with destination IP 0.0.0.0

13:20:59:291415 info: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[255] --> state IDLE --> SEND_ARP, LAST_CHANGE_TIMEOUT ip=0.0.0.0 mac=ca:e4:dc:90:10:54 sending arp
13:20:59:548453 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:00:567651 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:01:580003 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:02:566742 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:03:335853 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:04:353524 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:05:366411 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:06:378974 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:07:396310 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:08:408474 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:09:422480 debug: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[331] --> state: SEND_ARP -> WAIT_REPLY, arp_iface = brlan0, arp_iface_ipv4 = 192.168.0.1, arp_iface_mac = 02:50:f1:20:e3:87, is_4addr_client = 0, sta_mac = ca:e4:dc:90:10:54, dest_ip = 0.0.0.0, dst_mac = ca:e4:dc:90:10:54
13:21:10:187554 info: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[277] --> state WAIT_REPLY|WAIT_FIRST_REPLY --> IDLE, arp_retry_count > MONITOR_ARP_RETRY_COUNT
13:21:10:188614 info: beerocks_monitor_wlan0: <1749114816> monitor_rssi.cpp[290] --> arp_recv_count == 0, max arp retry no recv, send > NO_ACTIVITY_NOTIFICATION

**Comment by arnout** [comment]
I wonder: if #1368 works well, do we even need the DHCP monitor? Being able to work without it would be nice, because:
- the DHCP monitor is tricky (it relies on the specific DHCP server on OpenWrt);
- it only works with a prplmesh controller;
- it comes a bit late (when a new station connects, it's better to steer it as quickly as possible, before it starts traffic).
