### ISSUE TITLE
[BUG] [UGW] DHCP monitor fails to start 

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#1372]
**Describe the bug** -
DHCP monitor fails to start in slave init .
DHCP events not received for new client association and client's IP not be updated (0.0.0.0).
As a result monitor rssi will always send ARP request to zero target IP without getting any answer and will be stuck in endless timeout loop.

## platform
UGW: AX3000, AX6000, probably also rax40(same chip)  

## Steps to reproduce

1. Build
2. Run controller & agent
3. See in main agent logs:

/tmp/beerocks/logs/beerocks_agent.log
ERROR 16:05:12:768 <2000862592> platform_manager_thread.cpp[1474] --> Failed starting DHCP monitor: -1
ERROR 16:05:12:769 <2000862592> platform_manager_thread.cpp[837] --> can't start DHCP monitor

**Comment by itayx** [comment]
After examining the issue with the help of @adam1985d & @vitalybu
It seems like the issue is that in the UGW
the unbus namespace `dhcp_event` is gone, while in the RDKB it is still present

the namespace `dhcp_event` is used by the dhcp BPL & by the script `dhcp_notify_event.sh`
And since it is not longer preset in the `ubus list` it would explain why the error message `Failed starting DHCP monitor: -1` shows because the prpl is unable to register to a non-existing ubus namespace

There is a namespace named `dhcp`, need to check if we can replace calls to `dhcp_event` to `dhcp` instead

**Comment by itayx** [comment]
When listening to the UBUS traffic vis 'ubus monitor | grep -i DHCP`
on RDKB this is the resulting output
```
<- 3fe0ee38 #00000000         lookup: {"objpath":"dhcp_event"}
-> 3fe0ee38 #00000000           data: {"objpath":"dhcp_event","objid":-1225073873,"objtype":1203546423,"signature":{"dhcp_event":{"op":3,"mac":3,"ip":3,"hostname":3}}}
<- 3fe0ee38 #b6fadb2f         invoke: {"objid":-1225073873,"method":"dhcp_event","data":{"op":"old","mac":"34:f6:4b:32:16:da","ip":"192.168.0.127","hostname":"CHDWiFisetup2"}}
-> 5885d7c5 #3fe0ee38         invoke: {"objid":-1225073873,"method":"dhcp_event","data":{"op":"old","mac":"34:f6:4b:32:16:da","ip":"192.168.0.127","hostname":"CHDWiFisetup2"},"user":"root","group":"root"}
<- b03f222c #00000000         lookup: {"objpath":"dhcp_event"}
-> b03f222c #00000000           data: {"objpath":"dhcp_event","objid":-1225073873,"objtype":1203546423,"signature":{"dhcp_event":{"op":3,"mac":3,"ip":3,"hostname":3}}}
<- b03f222c #b6fadb2f         invoke: {"objid":-1225073873,"method":"dhcp_event","data":{"op":"old","mac":"34:f6:4b:32:16:da","ip":"192.168.0.127","hostname":"CHDWiFisetup2"}}
-> 5885d7c5 #b03f222c         invoke: {"objid":-1225073873,"method":"dhcp_event","data":{"op":"old","mac":"34:f6:4b:32:16:da","ip":"192.168.0.127","hostname":"CHDWiFisetup2"},"user":"root","group":"root"}
```
While in UGW when monitoring the `dhcp` no such events are seen

Need to check why the UGW no longer has the `dhcp_event` namespace

**Comment by vitalybu** [comment]
> When listening to the UBUS traffic vis 'ubus monitor | grep -i DHCP`
> on RDKB this is the resulting output
> 
> ```
> <- 3fe0ee38 #00000000         lookup: {"objpath":"dhcp_event"}
> -> 3fe0ee38 #00000000           data: {"objpath":"dhcp_event","objid":-1225073873,"objtype":1203546423,"signature":{"dhcp_event":{"op":3,"mac":3,"ip":3,"hostname":3}}}
> <- 3fe0ee38 #b6fadb2f         invoke: {"objid":-1225073873,"method":"dhcp_event","data":{"op":"old","mac":"34:f6:4b:32:16:da","ip":"192.168.0.127","hostname":"CHDWiFisetup2"}}
> -> 5885d7c5 #3fe0ee38         invoke: {"objid":-1225073873,"method":"dhcp_event","data":{"op":"old","mac":"34:f6:4b:32:16:da","ip":"192.168.0.127","hostname":"CHDWiFisetup2"},"user":"root","group":"root"}
> <- b03f222c #00000000         lookup: {"objpath":"dhcp_event"}
> -> b03f222c #00000000           data: {"objpath":"dhcp_event","objid":-1225073873,"objtype":1203546423,"signature":{"dhcp_event":{"op":3,"mac":3,"ip":3,"hostname":3}}}
> <- b03f222c #b6fadb2f         invoke: {"objid":-1225073873,"method":"dhcp_event","data":{"op":"old","mac":"34:f6:4b:32:16:da","ip":"192.168.0.127","hostname":"CHDWiFisetup2"}}
> -> 5885d7c5 #b03f222c         invoke: {"objid":-1225073873,"method":"dhcp_event","data":{"op":"old","mac":"34:f6:4b:32:16:da","ip":"192.168.0.127","hostname":"CHDWiFisetup2"},"user":"root","group":"root"}
> ```
> 
> While in UGW when monitoring the `dhcp` no such events are seen
> 
> Need to check why the UGW no longer has the `dhcp_event` namespace

DHCP Server calls the `dhcp_notify_event.sh` script?

**Comment by kantera800** [comment]
I did observe the following errors in RDKB

7761 Mar  5 11:56:34 2020 puma7-atom daemon.err dnsmasq: #############   XDNS : reload_servers()     read file :   /etc/resolv.conf    #############
7766 Mar  5 11:56:34 2020 puma7-atom daemon.err dnsmasq: **failed to execute /opt/prplmesh/scripts/dhcp_notify_event.sh: No such file or directory**

**Comment by arnout** [comment]
I suppose that's the script that was removed in b3a2c29a7d83a891919b48c2a459964379c81fbe? It was never installed by anything, so I don't know how it ever used to work.

**Comment by adam1985d** [comment]
> I suppose that's the script that was removed in [b3a2c29](https://github.com/prplfoundation/prplMesh/commit/b3a2c29a7d83a891919b48c2a459964379c81fbe)? It was never installed by anything, so I don't know how it ever used to work.

in the link provided the removed script is `dhcp.sh` and not `dhcp_notify_event.sh` - was it renamed at some point?
