### ISSUE TITLE
[BUG] Request with MID 0 is not handled correctly

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#1391]
The MID value 0 is handled specially in the transport (possibly in other places as well): it means "generate a new, unique MID". This mechanism is needed because different components (agent, controller) can generate CMDUs independently from each other, and the MIDs should be generated sequentially.

However, MID 0 is a valid MID according to the 1905.1 specification. Thus, it is possible that we get a request with MID 0, and thus that we should reply with MID 0 as well. That won't happen at the moment, the transport will generate a new MID instead.

The solution is probably to use more than 16 bits internally for the MID, or use an extra flag to indicate that the MID should be generated.

**Comment by RanRegev** [comment]
> the MIDs should be generated sequentially

why?

> use an extra flag to indicate that the MID should be generated

Do you mean in the `create()` function? if yes, then the simplest is to overload `create()` without `mid` as a parameter.

**Comment by mariomaz** [comment]
From IEEE Std 1905.1, Section "7.8 Message identifier values":
"If a 1905.1 management entity generates a message whose requirements mandate a new MID value, then it shall set the new MID value to the previously generated new MID value incremented by one, modulo 2^16. "

Is not as simple as overloading `create()` because the MID is not computed at agent/controller, but at a different process called ieee1905_transport.

**Comment by RanRegev** [comment]
> From IEEE Std 1905.1, Section "7.8 Message identifier values":
> "If a 1905.1 management entity generates 

What is a managment entity? If there is more than one then how do you sync the last generated MID value between them? 

> Is not as simple as overloading `create()` because the MID is not computed at agent/controller, but at a different process called ieee1905_transport

I truly don't understand who is responsible for creating the MIDs. If we need a 'MID generator' facility to support the requirments, then we should implement it. If we already have it, we should use it inside  'create()'.

**Comment by arnout** [comment]
I guess we need to insert an architecture lesson here...

The IEEE1905.1 standard specifies an "AL Entity" == "management entity". The Multi-AP specification defines two roles within an entity: controller and agent. An entity may perform both roles at the same time. An entity can be identified with its AL-MAC address. Both specs kind of assume that an entity corresponds to a "device".

prplmesh splits the AL Entity functionality over 4 processes: controller, agent, transport and the local bus to tie them together. (There are also the agent slaves and agent monitors that run in separate processes, but let's ignore those for the moment.) So everything in prplmesh really forms a single AL Entity, with a single AL-MAC address.

Within prplMesh, processes communicate with the same CMDUs that are also sent to other devices. Since the internal communication is fully reliable, the MID is not really used internally.

However, when a CMDU is sent to the outside world, it needs to have a valid MID. The CMDU itself is generated by either the controller or the agent, then sent to the transport, and the transport puts it on the network. Since we need to make sure that each CMDU has a unique MID, and we don't want to synchronize controller and agent to agree on what is the next MID, the MIDs are not generated by the controller or agent, but by the transport.

Except of course that for CMDUs which are replies to another CMDU, you need to use the same MID value. Therefore, the CMDU that is created by controller or agent *does* have a MID value set, but it is set to 0 to indicate that it's the transport's responsibility to generate a new MID.

So:

> how do you sync the last generated MID

That's why the MID is generated by the transport.

> If we already have it, we should use it inside 'create()'

That's not possible, since it requires sync between controller and agent.

**Comment by RanRegev** [comment]
Sorry, this answer still confuses me, and I guess this is because I don't have enough specification understanding.
I'll explain what I understand and the gaps that I have:
- Regardless of how prplMesh creates and manages MIDs: how does the standard guarantee that MIDs are sequential if they may be generated in different AL Entities?
- (specification question: Why is it important to have a sequential MIDs?)
- Assuming that the standard has its way to synchronize - why don't we follow this way and implement accordingly?
- Can we separate internal communication from the external one? do we _want_ such a separation?

**Comment by arnout** [comment]
It's important that the standard is not always logical and consistent...

> * Regardless of how prplMesh creates and manages MIDs: how does the standard guarantee that MIDs are sequential if they may be generated in different AL Entities?

Every sender (distinguished by the source AL-MAC address) has its own sequence. So it's the sender's responsibility to make sure it generates sequential numbers.

> * (specification question: Why is it important to have a sequential MIDs?)

It's not really important IMO, the spec just says "If a 1905.1 management entity generates a message whose requirements mandate a new MID value, then it shall set the new MID value to the previously generated new MID value incremented by one, modulo 2^16." However, it doesn't say anything about checking that values are sequential (which you can't do anyway).

What is important, however, is that there is a sufficiently long time before a MID is reused. If two packets with the same MIDs are coming closely after each other, one will be considered as a duplicate by the receiver.


> * Assuming that the standard has its way to synchronize - why don't we follow this way and implement accordingly?

The standard assumes that agent and controller are one single thing, not split up over two components.

**Comment by arnout** [comment]
> Can we separate internal communication from the external one? do we want such a separation?
I don't think we want such a separation - at least, towards the controller, we don't want to distinguish between a prplmesh controller and a generic controller.

We could say that internal communication between different agent threads/processes should use VS messages only. I was the one who proposed to switch to standard messages, where appropriate, even for internal communication. But maybe that was a bad idea.
