### ISSUE TITLE
prplMesh-old - prplMesh Intel Openwrt compatibility

### ISSUE THREAD

**Issue by StanOnix** [prplfoundation/prplMesh#14]
Hello,

We were using the prplMesh EasyMesh implementation on openwrt that is now archived. We want to know what are the requirements to use this new implementation on openwrt as the whole architecture changed. The prplmesh-openwrt is still pointing on this repo but that does not seem to work in openwrt environment.

Thanks in advance for your clarifications

**Comment by arnout** [comment]
Indeed, the prplmesh-openwrt repo should point to prplmesh-old. But anyway the versions specified in there were no longer up-to-date. Feel free to update the Makefile in your fork.

The new prplMesh repo has no integration in OpenWrt yet. We first want to get some features working in emulation (using mac80211_hwsim) before going for OpenWrt integration.

prplmesh-old only implemented the autoconfiguration flow. This feature is still under development in the new prplMesh repo (cfr. #9) and is hopefully finished in a few weeks.
