### ISSUE TITLE
[TASK] Add docker automated flows test script

### ISSUE THREAD

**Issue by Galvien** [prplfoundation/prplMesh#146]
## Description

Creating scripts for the purpose of automating the tests detailed in chapter 5: 'MCUT tests' of the EasyMesh Test Plan v1.0.

Subtasks:

- [x] Update CONTRIBUTING.md

Tests to be added:

- [x] 5.3 Discovery Tests
- [x] 5.4.1 Initial AP configuration
- [ ] 5.4.2 AP configuration renew
- [ ] 5.4.3 AP configuration BSS Tear Down
- [ ] 5.5 Channel Selection
- [x] 5.6.1 AP capability info reporting
- [ ] 5.6.2 Client capability info reporting
- [ ] 5.7 Combined Infrastructure Metrics test
- [ ] 5.8.1 Client Steering for Steering Mandate and Steering Opportunity
- [ ] 5.8.2 Setting Client Steering Policy
- [ ] 5.8.3 Client Association Control Message
- [ ] 5.10.1 Higher layer data payload over 1905 trigger
- [ ] 5.10.2 Higher layer data payload over 1905

## Exit criteria

All test are automated, all tests for flows that are not yet implemented will be stub, for the purpose of TDD

## Detailed description

- **Problem statement** - Automated tests are quicker to execute and are more reliable, test-driven development allows for a more organized workflow and easier understanding of the progress towards certification.
- **Possible solutions** - Automating the test flows through scripts.
- **Components affected** None
- **Build considerations** - None
- **Dependencies** - Docker

**Comment by tomereli** [comment]
Script is done and working in the CI, done in #145.
Closing, since every new flow will have its own task and the exit criteria is to add implementation to test_flows.sh + update CI to run it.
