### ISSUE TITLE
[BUG] prplmesh_utils.sh: "stop" should really stop all processes

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#1473]
Since #1454 processes are killed with SIGTERM instead of SIGKILL. However, that means that they keep on running if the TERM didn't work (e.g., in case of #1472).

A KILL should be sent after some time to make sure the process is really dead.

Normally we'd use start-stop-daemon for that, but we can't be sure that it's available on all platforms.

**Comment by tomereli** [comment]
I think we can add this as a prplmesh requirement - and always use `start-stop-daemon`.
