### ISSUE TITLE
[TASK] TLVF dynamic/variable length lists of STD types getter to return buffer pointer

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#156]
## Description

Currently, only `char` types lists (dynamic/variable length) include a getter function to return a pointer to the buffer. For any other list type, the getter function returns a tuple with reference to the element. In case of STD types, normally they are simple buffers - so this getter function forces the user to write complex code to get the job done:

```
//data is a list of uint8_t members
auto data_tuple = request->data(0);
memset(&std::get<1>(data_tuple), 0, size_left);
```
Instead of a much simpler code:

```
memset(request->data(), 0, request->data_length());
```
## Exit criteria

- Update TLVF to generate getter function which returns the buffer pointer in case of STD types
- Remove the getter function which returns tuple
- Update rest of the code which used the tuple API
- Update the tlvf_test to test this (can change one of the lists to uint8_t instead of  char)

**Comment by arnout** [comment]
TBH I find the tuples to be inconvenient in general. Normally, I would simply raise an exception if you try to access an offset that doesn't exist - just like std::vector::at(). Except, of course, that we don't use exceptions...
