### ISSUE TITLE
[TASK] Controller shouldn't trigger tasks for non-Intel agents

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#162]
## Description

We should remove the trigger for tasks which are intel specific in the controller for non-Intel agents.

We need to distinguish between Intel and non-Intel agents in the topology database - either with a new type, or with a flag. The conn_map should show this difference.

## Exit criteria

* Non-Intel agents are visible in conn_map.
* Non-Intel agents are marked differently in conn_map.
* No tasks are started for non-Intel agents, unless they can be done with the already-implemented EasyMesh flows.

## Detailed description

The current controller ("master") implementation assumes the agents are Intel agents, and follow the Intel protocol with Vendor-Specific messages. We want to reuse the existing implementation but still support non-Intel agents. Some of the tasks may be able to function without the Intel Vendor-Specific messages, but until they do, it makes no sense to start these tasks for non-Intel agents.

We want a simple way to have an operational controller with as much functionality as possible even if non-Intel agents exist in the network.

Therefore, non-Intel agents should be indicated as such in the database, and tasks should skip over them if they don't work standard Multi-AP messages.

**Comment by ghost** [comment]
@arnout @morantr Is this issue still unfinished? If it's finished (or no longer needed), please close it.
If it's not yet fully completed, but the missing pieces are not needed for wired certification, please change the milestone.
If any work remains for this milestone, we need to know ASAP

**Comment by arnout** [comment]
It is not done, but I think the current state is good enough - at least no VS messages are sent to non-Intel agents. So closing.
