### ISSUE TITLE
5.3.1 Supported Discovery

### ISSUE THREAD

**Issue by c0dingn0mad** [prplfoundation/prplMesh#186]
## Description

The prplMesh controller needs to pass the test case as defined in 5.3.1 

## Exit criteria

The flow is completed once the controller passes this test in the scenario and testbed described in the upstream definition.

- [x] #187
- [x] #241
- [x] #190

**Comment by tomereli** [comment]
Add a task for testbed setup to come before #190 
Should something like "bring up testbed with CTT Agent1 as Mediatek + sniffer"

**Comment by Mila-Sh** [comment]
The test MAP-5.3.1 passed 
commit hash: ba99b55
Configuration as required in test plan v1.0:
MCUT : prplmesh
Agent1 : Mediatek
Agent2 : None
CCT STA : None
Logs:
https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ?path=%2Fprpl%20controller%20tests%2FPASS%2FMAP-5.3.1_PRPLMESH_MEDIATEK
