### ISSUE TITLE
[Task] complete development needed for flow 5.4.1

### ISSUE THREAD

**Issue by c0dingn0mad** [prplfoundation/prplMesh#191]
## Description

Implement all code required to complete perform flow 5.4.1

## Exit criteria

The task will be complete when the test script has been properly written, and necessary components have been implemented, running the corresponding test in test_flows.sh returns an OK, and .travis.yml has been updated accordingly.

- [x] #71 
- [x] #126 
- [ ] #134 
- [ ] #171 
- [ ] #162 
- [ ] #227

**Comment by arnout** [comment]
Replaced by subtasks directly in #193
