### ISSUE TITLE
5.4.1 Initial AP configuration

### ISSUE THREAD

**Issue by c0dingn0mad** [prplfoundation/prplMesh#193]
## Description

The prplMesh controller needs to pass the test case as defined in 5.4.1 

## Exit criteria

The flow is completed once the controller passes this test in the scenario and testbed described in the upstream definition.

- [X]  #71
- [X] #126
- [x] #134
- [ ] #171
- [ ] #162
- [x] #227
- [x] #274 
- [x] #192

**Comment by tomereli** [comment]
Remaining tasks are not mandatory to pass the test which we already passed. So closing.
