### ISSUE TITLE
5.5.1 Channel Preference Query

### ISSUE THREAD

**Issue by c0dingn0mad** [prplfoundation/prplMesh#202]
## Description

The prplMesh controller needs to pass the test case as defined in 5.5.1

## Exit criteria

The flow is completed once the controller passes this test in the scenario and testbed described in the upstream definition.

- [x] #200 
- [x] #201

**Comment by Mila-Sh** [comment]
MAP-5.5.1 PASS
commit hash: ba99b55
Configuration as required in test plan v1.0:
MCUT : prplMesh
Agent1 : Mediatek-AP
Agent2 : None
CTT STA : None
Logs:
https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ?path=%2Fprpl%20controller%20tests%2FPASS%2FMAP-5.5.1_PRPLMESH_MEDIATEK
