### ISSUE TITLE
5.10.1 Higher layer data payload over 1905 trigger

### ISSUE THREAD

**Issue by c0dingn0mad** [prplfoundation/prplMesh#222]
## Description

The prplMesh controller needs to pass the test case as defined in xxx 

## Exit criteria

The flow is completed once the controller passes this test in the scenario and testbed described in the upstream definition.

- [x] #166 
- [x] #221

**Comment by Mila-Sh** [comment]
MAP-5.10.1 PASS
commit hash: ba99b55
Configuration as required in test plan v1.0:
MCUT : prplMesh
Agent1 : Marvell-AP
Agent2 : None
CTT STA : None
https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ?path=%2Fprpl%20controller%20tests%2FPASS%2FMAP-5.10.1_PRPLMESH_MARVELL
