### ISSUE TITLE
5.10.2 Higher layer data payload over 1905 test

### ISSUE THREAD

**Issue by c0dingn0mad** [prplfoundation/prplMesh#225]
## Description

The prplMesh controller needs to pass the test case as defined in 5.10.2 

## Exit criteria

The flow is completed once the controller passes this test in the scenario and testbed described in the upstream definition.

- [x] #223 
- [x] #224

**Comment by Mila-Sh** [comment]
MAP-5.10.2 PASS
commit hash: ba99b55
Configuration as required in test plan v1.0:
MCUT : prplMesh
Agent1 : Mediatek-AP
Agent2 : None
CTT STA : None
Logs:
https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ?path=%2Fprpl%20controller%20tests%2FPASS%2FMAP-5.10.2_PRPLMESH_MEDIATEK
