### ISSUE TITLE
[Feature] Handling WFA-CA command "DEV_SET_CONFIG"

### ISSUE THREAD

**Issue by morantr** [prplfoundation/prplMesh#229]
### **Introduction**
To pass EasyMesh certification, the system is required to be able to receive various commands from TestSuit(UCC) application.
Current design focus on the command "DEV_SET_CONFIG" which is used to configure a device (Agent) with its configuration parameters.

### **Sequence Diagram**

![dev_set_config](https://www.plantuml.com/plantuml/png/0/dLF9Ri8m4Br7oZzONDfAB89Z54M442fKbef0UqGc66AHsf7j2FZxZhD025tKvZHvC_FytepTbmeBbNx4fc4Q2OGqf0bc2gqyxnRmE5E2np4Ht-73mMt6tHEcDAzf01jgEPLQ2mtzj_N23_pbUkYFtDLaQHhNj2w67Wk1F9NAfZUVlaxyfVy3bsRovhFH-BcvaN9DsOwlkvUmrsots_13yyJ9D1XN1CLa1meHV8rBqwc1Gk36b4cqEICkjd14NcHdbjoORfq2c2T4O4NPteknb2KQ1EDX6RkfYg29Xb36sVASa3BZir2Sapew8-h8nU65d4jaWCD3bE9uS3rW941XXDC28soBj1yzdjiXLhTZeTBZWzGMTtHVcMTcxSkrt1TKPwt5WP1cBXEYmenfP0trLTcwmJf6L177VMt1T7Wk9HNPW510i0WZD2LIuZsnExhUgTigjFnAjY0ouKoIExh_gdiFl98BJRiLkkgWwwpvKNPsRx8TQCwwfT9JusyQUiWEUSo59SZMUIp9d-nEXZeLXNsu9V3GFm40 "dev_set_config")

### **Command Syntax**

Name | Description | Value
-- | -- | --
Backhaul | Set a single backhual interface to Ethernet or Wi-Fi. For Wi-Fi, a RUID associated with its frequency band (2.4GHz, 5GHz Low, 5GHz High) is provided. For Ethernet, the device should return status,COMPLETE until it completes Ethernet onboarding.</br><span style="color:red">NOTE: This argument is only relevant, when UCC send the command to the agent.</span>| String: EthRUID
BSS_Info1 | BSS initialization data used by controller to configure agent's fronthaul radio. The value is a list of fields separated by space that stands for: </br>WTS_REPLACE_DEST_ALID,operating class, SSID, authentication type (WPA2-PSK), encryption type(AES-CCMP),network key, bit 6 of Multi-AP IE's extension attribute, bit 5 of Multi-AP IE's extension attribute. To clear the BSS info stored for a specific operating class, only the deviceALID and operating class are retained.</br><span style="color:red">NOTE: This argument is only relevant when UCC send the command to the controller.</span>| String: WTS_REPLACE_DEST_ALID 8x Multi-AP-2G-1 0x00200x0008 maprocks1 0 1
BSS_Info2 | |String: WTS_REPLACE_DEST_ALID8x Multi-AP-2G-2 0x00200x0008 maprocks2 0 0
BSS_InfoN | |String: WTS_REPLACE_DEST_ALID8x Multi-AP-2G-n 0x00200x0008 maprocksn 0 0
Name | Device name. | String: For Ex.: dev1
Program | Program name | String: MAP

##### **BSS_info components by order:**
1. Destination Agent ALID
2. Operating Class - if '8x' - '2.4G', else '5G'.
3. SSID - Will be filled on sWscAttrKeyWrapAuthenticator as part of M2 message.
4. Authentication type - Will be filled on sWscAttrKeyWrapAuthenticator as part of M2 message. This value is in hex notation which presented by eWscAuth Enum.
5. Encryption type - Will be filled on sWscAttrEncryptionType as part of M2 message. This value is in hex notation which presented by eWscEncr Enum.
6. Network key - Will be filled on sWscAttrNetworkKey as part of M2 message.
7. Bit 6 of Multi-AP IE's extension attirbute - Means 'Backhaul BSS' which will be filled on sWscAttrVendorExtension as part of M2 message.
8. Bit 5 of Multi-AP IE's extension attirbute - Means 'Fronthaul BSS' which will be filled on sWscAttrVendorExtension as part of M2 message.

### **Design**

Each DEV_SET_CONFIG command will be parsed, and its parameters will be stored in controller DB (not inside DB node), in list container.
**Note: This configuration will have to be cleared on DEV_RESET_DEFAULT command.**
When the controller will receive M1 and create M2 message, it will take the configuration from the DB and fill it inside M2.

**Problem**
"DEV_SET_CONFIG" could have multiple devices configuration on the command with the same ALID. When filling M2, how could the controller choose which configuration to use for each RUID? 
It is possible to match operating class on AP capabilities from M1 to the operating class in the configuration to know to which configuration to use in M2:
if operating class is '8x' - '2.4G', else '5G'.

**Opens**
If there will be multiple configurations with operating class that match AP capabilities, it will be impossible to fill M2.

[dev_set_config.zip plantuml files](https://github.com/prplfoundation/prplMesh/files/3540291/dev_set_config.zip)

**Comment by tomereli** [comment]
Well done, let's discuss this on the next daily meeting.

**Comment by arnout** [comment]
Regarding the "Problem": indeed, the specification requires that you match the radio band with the configured radio bands and provide an M2 for each matching SSID. Note that there may be multiple M2s in the WSC response.
