### ISSUE TITLE
[BUG] tlvf: check struct size for dynamic-length members

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#234]
tlvf generates an `init()` function for classes that parses the class's substructures. This function has an initial check for the minimum length:

```
    if (getBuffRemainingBytes() < kMinimumLength) {
        TLVF_LOG(ERROR) << "Not enough available space on buffer. Class init failed";
        return false;
    }
```

However, there is no such check for subsequent dynamic/variable length substructures. Therefore, parsing an invalid packet may lead to an out-of-bounds read.

## Steps to reproduce

This can easily be reproduced with the M1 and M2 WSC TLVs, since they have the same type but different internal structure. Thus, if an M2 message is interpreted as an M1 or vice versa, havoc will result.

1. Run controller & agent for the gateway
2. Add a non-Intel agent that puts the M1 WSC TLV before the AP Radio Basic Capabilities TLV.
3. Start AP Autoconfig from the non-Intel agent
4. With a bit of luck, the beerocks agent on the gateway crashes

## Proposed solution

Instead of checking getBuffRemainingBytes only at the beginning of init(), do it before each substructure that is parsed, including the fixed-length substructures. It is also needed for fixed-length substructures because a fixed-length structure coming after a dynamic-length substructure may be the one that triggers the overflow.

Note that the reproducer would also be fixed by checking the correctness of const_value substructures, because we'd immediately recognise that it's in fact not an M2 message. However, we still want to fix the fundamental issue to protect against intentionally misconstructed packets.

**Comment by Galvien** [comment]
To reproduce the issue, use the [prplMesh-old - hack to work with new prplMesh ](https://github.com/prplfoundation/prplMesh-old/commit/3c8aa01ec258df4dc6e831eed1eb438606936271#diff-8bebfa070a7947ba07bc4a5f9c16b65cL799) branch.
Installation and running instructions are in the thread.
