### ISSUE TITLE
[TASK] Pass flow 5.3.1 test in testbed with reference controller

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#241]
## Description

bring up all needed components to pass  5.3.1 test in testbed with reference controller
DUT: qualcom
Agent1:  MediaTek
Agent2: not connected
SNFe: Fedora
SNFw: not connected
STA: not connected

## Exit criteria
5.3.1 test pass in UCC

**Comment by arnout** [comment]
[Passed with MCUT Marvell_W8964 and CTTAgent1 Qualcomm_IPQ4019](https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ?path=%2FCertified%20controller%20tests%2F9-9-2019%2FPASS%2FMAP-5.3.1_Sep-10-2019__16-08-57).
