### ISSUE TITLE
[BUG] controller: autoconfig search parse fail with reference agent

### ISSUE THREAD

**Issue by CoralMalachi** [prplfoundation/prplMesh#274]
**Describe the bug** -
While testing with reference CTT agent in the testbed, it turned out that
one of the golden unit agents sends the autoconfig search CMDU in a different order than what the prplMesh controller expects - autoconfig freq band TLV  comes last when the controller expects it to be third, which caused the prplMesh controller to fail on parsing.

Fix that in the controller by adding support for any order of TLVs in autoconfig search message.

1. in `main_thread::send_autoconfig_search_message` change the current order of addClass TLV, for example, move  the `addClass<ieee1905_1::tlvAlMacAddressType>()` action to be last.
2. Build
3. Run controller only (./test_gw_repeater.sh -f --gateway-only) and expect failure.
4. See in the controller's logs : "TLV type mismatch".

## Expected behavior
test_gw_repeater failed. 

## Screenshots
![image](https://user-images.githubusercontent.com/38204874/64528374-fb443700-d310-11e9-9ba4-fd603a5b56c4.png)

**Comment by tomereli** [comment]
What is the "planned" label?

**Comment by tomereli** [comment]
Fixed in #277
