### ISSUE TITLE
[TASK] test_flows: more precise matching of log check

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#280]
## Description

Many of the tests in test_flows.sh search in the log file for some string to determine if a message was correctly received. However, it is possible that the same message occurs several times in the log file, coming from different tests. E.g. several tests check for ACK_MESSAGE.

The matching should be made more precise, to avoid false success.

## Exit criteria

Correctness is proven by adding a failing test, e.g. checking an ACK_MESSAGE that was generated by a previous test but not by this one. Obviously, this commit is removed from the PR before merging.

## Detailed description

This can be implemented in several ways.

1. Include the MID in the search pattern. This will require parsing out the MID from the WFA_CA return value. However, this only works for replies to a DEV_SEND_1905.
2. Mark the log file before the test starts (e.g. count the number of lines before the test, and skip that many lines before grepping).
3. Completely restart prplMesh for every test.
4. Instead of writing to the log file, keep a state file and check that. This only works for some cases, e.g. checking autoconfig results.
5. ... Probably other alternatives exist.

**Comment by tomereli** [comment]
I think that for ACKs, matching the MID is the correct approach since we might have multiple ACKs in a single flow.
For the rest, we can simply delete the logs before running each test (option 6).

**Comment by ghost** [comment]
Several steps have been taken in this area as part of test flows refactoring and board farm migration, so closing this issue.
The new recommended approach is to inspect packets (which are captured by the test infrastructure) instead of log files.
If log file inspection is necessary, this can now be done incrementally as well.
