### ISSUE TITLE
[BUG] wf_ca: parse_bss_info with 1 parameters not handled

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#310]
**Describe the bug** -
Currently in code when handling DEV_SET_CONFIG capi command with bss_info we expect 8 parameters .
We need to add support to cases with 2 parameters, see "Wi-Fi_Test_Suite_Control_API_Specification_v10.7.0" spec

PR #311

## Found 
while debugging  UCC test 5.4.3 

## Steps to reproduce
build prplmesh
.../prplmesh_utils.sh restart
../beerocks_cli -u 5000

from other terminal:
sudo nc <bridge_ip> 5000

dev_set_config,program,map,bss_info1,62:99:12:5f:b1:9e 8x

## current behavior
DEBUG 10:56:07:963 <139878951185280> wfa_ca.cpp[357] --> Received ACTION_BML_WFA_CA_CONTROLLER_REQUEST, command="dev_set_config,program,map,bss_info1,62:99:12:5f:b1:9e 8x"
ERROR 10:56:07:963 <139878951185280> wfa_ca.cpp[652] --> missing configuration on bss_info1

## expected  behavior
--> received 1905.1 cmdu message

**Comment by arnout** [comment]
This is in fact documented in the Control API Specification. In section 10.10, description of BSS_Info1, the last sentence says: "To clear the BSS info stored for a specific operating class, only the device
ALID and operating class are retained."
