### ISSUE TITLE
[BUG] <controller>: teardown sent due to wrong al-mac address in DB

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#334]
Describe the bug -

It looks like there is in fact no config in the database for that al-mac address.
the ruid is empty .
controller is sending a teardown to the Broadcom agent.

Found
while debugging UCC test 5.4.1 24G

logs:
https://ftp.essensium.com/owncloud/index.php/apps/files?dir=/prplmesh/certification/prpl%20controller%20tests/FAIL/MAP-5.4.1_ETH_FH24G_Broadcom_Marvell_teardown

link to passing test on master from 2 weeks ago:
https://ftp.essensium.com/owncloud/index.php/apps/files/?dir=/prplmesh/certification/prpl%20controller%20tests/PASS/MAP-5.4.1_ETH_FH24G_setup_prplmesh_broadcom_marvell&fileid=423625

Steps to reproduce
build prplmesh
.../prplmesh_utils.sh restart
../beerocks_cli -u 5000

from UCC:
run test 5.4.1 24G

current behavior  (controller.log):  
INFO 16:09:52:785 <140154884115328> son_master_thread.cpp[734] --> AP_AUTOCONFIGURATION_WSC M1 al_mac=46:55:66:77:00:00 ruid=00:00:00:00:00:00
DEBUG 16:09:52:785 <140154884115328> son_master_thread.cpp[735] -->    device Intel Ubuntu prplMesh-agent prpl12345
DEBUG 16:09:52:785 <140154884115328> encryption.cpp[32] --> Generating DH keypair
DEBUG 16:09:52:787 <140154884115328> encryption.cpp[99] --> Computing DH shared key
DEBUG 16:09:52:789 <140154884115328> son_master_thread.cpp[636] --> WSC config_data: tear down

expected behavior
test pass

**Comment by arnout** [comment]
The problem is that we store the bss_info with a string key in the database. The UCC gives the MAC address with uppercase hex digits, but our network_utils::mac_to_string uses lowercase.

The solution is to use sMacAddress instead of string.
