### ISSUE TITLE
[TASK] Pass flow 4.3.1 Ethernet backhaul test in testbed

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#339]
# Description

Perform all steps necessary to pass the test associated with flow 4.3.1 with Ethernet backhaul in the certification testbed.

# Exit criteria

- Turris Omnia OpenWrt with firmware master branch
- Certification test passes
- Test results uploaded to https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ

**Comment by tomereli** [comment]
Passed, see https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ?path=%2Fprpl%20agent%20tests%2FPASS%2FMAP-4.3.1_ETH%202020-02-26_15-38-53
