### ISSUE TITLE
[TASK] Implement START_WPS_REGISTRATION_INTERFACE

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#342]
## Description

Implement the `START_WPS_REGISTRATION_INTERFACE` WFA CA command.

## Exit criteria

- `START_WPS_REGISTRATION_INTERFACE` is implemented for agent.
- Both Enrollee and Registrar modes are supported.
- With dummy bwl, it triggers a log message.
- A test script exists that validates this flow.
- With OpenWrt bwl/bpl, it triggers WPS.

**Comment by ghost** [comment]
See #1168
