### ISSUE TITLE
[TASK] Test flow for 4.2.1 Multi-AP Ethernet Onboarding and Initialization

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#343]
## Description

Implement a test flow script that can be executed in docker to validate 4.2.1 Multi-AP Ethernet Onboarding and Initialization.

Example PASS logs with prplMesh attached - [4.2.1_PASS.zip](https://github.com/prplfoundation/prplMesh/files/4281497/4.2.1_PASS.zip)

**Comment by arnout** [comment]
@tomereli wrote in https://github.com/prplfoundation/prplMesh/pull/533#discussion_r354843238

> Perhaps we can store the credentials in some class member, and use it in refresh_radio_info which is sent to the controller. This way even in Dummy mode in Linux containers we will see the credentials in bml_conn_map.
> Based on this, we can add/update the corresponding test flow to verify that the correct VAP credentials were applied.

**Comment by tomereli** [comment]
[4.2.1_PASS.zip](https://github.com/prplfoundation/prplMesh/files/4281497/4.2.1_PASS.zip)

**Comment by tomereli** [comment]
This is no longer needed since 4.2.1 test is covered by channel selection and autoconfig tests in test_flows.sh and test_flows.py, hence closing.
