### ISSUE TITLE
[TASK] AP configuration on Turris Omnia / RAX40 OpenWrt

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#346]
## Description

The agent parses the WSC M2 message, but it only logs the configuration. The configuration should also be applied to the system. bpl functions exist for this, but they probably need some refactoring.

## Exit criteria

- Agent WSC M2 handling calls bwl functions to add APs and set credentials.
- Dummy and OpenWrt implementations of these exist.
- `test_flows.sh` is updated to check for bpl call instead of arrival of M2.
- Manually validated on Turris Omnia / RAX40

**Comment by ghost** [comment]
@YuriyMasechko could you please evaluate what else needs to be done for this task?

**Comment by YuriyMasechko** [comment]
There is only dummy implementation of bwl.
So first of all need to implement bwl and then update test_flows.sh.

**Comment by tomereli** [comment]
Already done
