### ISSUE TITLE
[TASK] Test flow for 4.4.3 AP configuration BSS Tear Down

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#361]
## Description

Implement a test flow script that can be executed in docker to validate 4.4.3 AP configuration BSS Tear Down

**Comment by ghost** [comment]
4.4.3 is (mostly) passing in CI (e.g. https://ftp.essensium.com/owncloud/index.php/apps/files/?dir=/prplmesh/certification/Nightly/agent_certification/2020-03-25_20-30-29/PASS/MAP-4.4.3_ETH_FH5GH&fileid=713413)

Closing this issue.
