### ISSUE TITLE
[TASK] AP Radio Basic Capabilities and Channel Preference Report for nl80211

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#363]
## Description

When the controller does a Channel Preference Query, the agent should send a Channel Preference Report that corresponds to the actual behaviour of the AP. Similarly, the AP Radio Basic Capabilities TLV should contain the real operating classes and channels. Since these two go hand in hand, they're included in a single issue.

From Multi-AP specification:

> 
> 
> The Channel Preference Report message shall
> contain information regarding all the channels that a given radio of the Multi-AP Agent transmitting the report is
> temporarily unable to operate in, or prefers not to operate in, for each supported operating class as specified by the Multi-
> AP Agent (per Operating Classes field in the AP Radio Basic Capabilities TLV in section 17.2.7). Additionally, the Channel
> Preference Report message shall contain information regarding the channel separation (if any) that a given radio of the
> Multi-AP Agent requires between each of its own potential operating channels and the operating channel of another radio
> of the Multi-AP Agent, where the two radios may have one transmitting and the other receiving or transmitting
> simultaneously.
> Note: Channels for which the Multi-AP Agent’s radio is statically (permanently) unable to operate are reported in the AP
> Radio Basic Capabilities TLV. A Channel Preference Report message does not include information on operating classes
> that are not supported by the corresponding radio of the Multi-AP Agent per the AP Radio Basic Capabilities TLV.

Most likely, the statically inoperable channels list will always be empty, and the channel preference will be limited to DFS info, but this should be checked.

## Exit criteria

- Radio Basic Capabilities TLV contains actual operating classes and inoperable channels on OpenWrt, based on netlink information.
- Channel Preference Report TLV contains actual operating classes and channel preferences from netlink.
- This is validated manually on Turris Omnia.

**Comment by tomereli** [comment]
@CoralMalachi - please update which NL can be used to get the supported, unsupported, and radar affected channels like we found using `iw` command. @arnout I think that the inoperable channels should be taken from that list provided by the driver via NL, there is nothing in UCI radio configuration which mentions anything about inoperable channels (see https://openwrt.org/docs/guide-user/network/wifi/basic).

**Comment by CoralMalachi** [comment]
@YuriyMasechko 
Please look here https://godoc.org/github.com/remyoudompheng/go-netlink/nl80211.

- To get the channels, we need to use FREQUENCY_ATTR_FREQ and the "ieee80211_frequency_to_channel" method which is defined in util.c file  (https://github.com/Distrotech/iw/blob/distrotech-iw/util.c)

- To check if a current channel is disabled use FREQUENCY_ATTR_DISABLED.

- To get a radar detection channel use FREQUENCY_ATTR_RADAR.

- We can use the "print_phy_handler" method as a reference, which is defined in info.c file ----> https://github.com/Distrotech/iw/blob/distrotech-iw/info.c

**Comment by CoralMalachi** [comment]
The output of "iw list" command:
![image](https://user-images.githubusercontent.com/38204874/67864260-07d55680-fb2e-11e9-84ff-b6588ac4e627.png)

And the appropriate part In the code: 
![image](https://user-images.githubusercontent.com/38204874/67864123-ccd32300-fb2d-11e9-857b-5218965637fb.png)

**Comment by arnout** [comment]
> I think that the inoperable channels should be taken from that list provided by the driver via NL, there is nothing in UCI radio configuration which mentions anything about inoperable channels (see https://openwrt.org/docs/guide-user/network/wifi/basic).

The `channels` option allows to limit the channels that the radio is allowed to operate in. This is not visible in the netlink output.

Our original idea was to handle this by querying such information from hostapd instead of nl80211. That would allow the platform to set up hostapd as it likes, and then start prplMesh (after hostapd has been started) and let prplMesh get all of its information from hostapd. Obviously, such an approach requires relatively invasive surgery in hostapd.

I think it would still be useful to support such mode of operation, but keep a fallback to netlink if hostapd doesn't support the new commands. Thus, it's something that can be added later.

So for the time being, let's ignore the UCI stuff and just look at netlink info.
