### ISSUE TITLE
4.5.1 Channel Preference Query

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#365]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.5.1 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #363 AP Radio Basic Capabilities and Channel Preference Report for nl80211
- [x] #364 Pass flow 4.5.1 test in testbed

**Comment by ghost** [comment]
4.5.1 is passing, closing this issue
