### ISSUE TITLE
4.5.3 DFS Status update report

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#371]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.5.3 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #370 Pass flow 4.5.3 test in testbed

Note: this test does not really test anything on the agent, so it's not relevant to add it to the test flows.

**Comment by ghost** [comment]
4.5.3 is passing in certification testbed, closing issue
