### ISSUE TITLE
[TASK] Test flow for 4.6.1 AP capability report

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#372]
## Description

Implement a test flow script that can be executed in docker to validate 4.6.1

**Comment by mariomaz** [comment]
There is already a `test_ap_capability_query()` that sends an AP_CAPABILITY_QUERY_MESSAGE and waits for an AP_CAPABILITY_RESPONSE_MESSAGE. It doesn't test however the presence of any of the TLVs that can be included in response message (they are optional). 

See #707
