### ISSUE TITLE
[TASK] Create HT, VHT, HE Capability TLVs for nl80211

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#373]
## Description

The nl80211 bwl implementation should get the necessary information to construct HT, VHT and HE Capability TLVs, and the agent should include these TLVs in the AP Capability Report CMDU.

## Exit criteria

- All capabilities are queried from the radio
- HT, VHT and HE Capability TLVs are included in AP Capability Report CMDU.
- Manually tested on Turris Omnia.

## Detailed description

We need to find a good way to get this right. The problem is that nl80211 from the kernel reports what is supported in the hardware, but this may be different from the device configuration. In OpenWrt, the radio configuration in UCI further limits the capabilities of the radio. So perhaps it would be better to query this from hostapd instead of nl80211.

**Comment by mariomaz** [comment]
@arnout : Can we close this issue?
HT/VHT Capability TLVs have been included into AP Capabilities Report message in #1148 and HE Capability TLV is to be included in #1162. In both cases data is not fetch using hostapd but nl80211. Feature is available to both DWPAL and NL80211 flavors of the BWL.
