### ISSUE TITLE
4.7.7  Associated STA Link Metrics and Counters

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#395]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.7.7 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #387 Pass flow 4.7.7 test in testbed

**Comment by vitalii-komisarenko** [comment]
Test 4.7.7 is passing.
The only thing that is not implemented properly is MAC data rate computation.
It is described in https://github.com/prplfoundation/prplMesh/issues/1195 .

Since there is no other known issues with 4.7.7 it is OK to close this issue.
