### ISSUE TITLE
[TASK] Test flow for 4.7.9

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#398]
## Description

Implement a test flow script that can be executed in docker to validate 4.7.9

**Comment by RanRegev** [comment]
As far as I understand only the request may be validated, as there is no current way to simulate STA response.
Also noticed that there is no check_log that checks the `beerocks_monitor_wlanX.log`

**Comment by arnout** [comment]
> As far as I understand only the request may be validated, as there is no current way to simulate STA response.

As part of implementing the test, dummy bwl events should be extended to do exactly that.

**Comment by RanRegev** [comment]
> As part of implementing the test, dummy bwl events should be extended to do exactly that.

Maybe there should be an issue for this? (so we can set priorities)
Or this is part of this #398 issue?
