### ISSUE TITLE
[TASK] Client Association Event

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#421]
## Description

When a client associates or disassociates, the agent should send a Topology Notification with a Client Association Event TLV

## Exit criteria

- Topology Notification is sent on client association/disassociation.
- Client Association Event TLV is included.
- Test flow exists for this.
- Manually tested on Turris Omnia.

**Comment by arnout** [comment]
I believe this is in fact already implemented? @YuriyMasechko can you confirm? I think the client_steering_dummy flow also tests it implicitly?

**Comment by YuriyMasechko** [comment]
Yes, this one is done.
