### ISSUE TITLE
[TASK] Consistently use "radio" instead of "hostap"

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#436]
## Description

Beerocks terminology is sometimes different from what Multi-AP uses, which creates confusion. Currently, the code has a lot of references to "hostap". In most cases, this actually means "radio". Replace those references.

Similarly, the word "slave" is also often used to refer to a radio. Replace those references as well.

## Exit criteria

- No references to "hostap" or "slave" remain, except perhaps in specific cases where it really refers to hostap.
- If any "hostap" or "slave" references remain, a comment in this issue explains why.

## Detailed description

There are currently roughly 3800 references to "hostap" in the code. Replacing those with "radio" should be done in separate commits. E.g.:

- btlvf + its callers;
- bwl + its callers;
- bcl + its callers;
- remaining references in agent;
- bml + its callers;
- master db + its callers;
- beerocks_cli;
- remaining references in master.

**Comment by morantr** [comment]
There are a lot of references for "slave" in the controller which means the same thing.

**Comment by arnout** [comment]
> There are a lot of references for "slave" in the controller which means the same thing.

Updated description.
