### ISSUE TITLE
[TASK] Test for optimal path task

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#443]
## Description

In the demo at prpl Summit, we made sure that the controller's optimal path task is working properly. To make sure this keeps on working, we should have a test of it. The test should run in Docker, similar to test_flows.sh, but in a separate script.

## Exit criteria

A test script exists that runs a gateway and two repeaters and tests the following features:
- Optimal path task is started when a client connects.
- Check that 11k request is done and that its arguments are as expected.
- Test gives 11k response that shows best link quality for current BSS.
- Check that no steering is done.
- Check that after a while optimal path task runs again *TBD what should trigger this?*
- Give 11k response that shows best link quality in a different BSS.
- Check that steering is done.
- Connect a second station, check that optimal path task runs.
- Give error response to 11k request.
- Check that error response is handled correctly (no crashes, falls back to RSSI).

**Comment by morantr** [comment]
The optimal path is automatically being triggered when the Monitor report on a change of 6 dB (I think...) on client rx_rssi, or manually from CLI.
I guess you would want to change the client measurement on bwl to return each time a different value.
I will require to set a new data path to control dummy bwl in addition to the event data path.
