### ISSUE TITLE
[TASK] Bring up Wireless backhaul on RAX40

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#455]
## Description

Initial bring up of prplMesh Agent (repeater mode) on RAX40 with Wireless backhaul.

- [ ] Wireless backhaul link establishment in openwrt (no prplMesh)
- [ ] Run prplMesh with wired backhaul ifname set to the wireless backhaul ifname (hack to get wireless backhaul without code changes)

**Comment by arnout** [comment]
This is covered by different tasks now so closing this one.
