### ISSUE TITLE
[TASK] Extend BWL to get supported and disabled channels

### ISSUE THREAD

**Issue by CoralMalachi** [prplfoundation/prplMesh#457]
## Description
Currently, the BWL does not report about the following :

- Statically inoperable channels.

- Supported channels.

The task is to extend the BWL to get the info about operating classes and statically inoperable channels and to set the acs_report properly (in ap_wlan_hal::read_acs_report).

The following iw tool command can be used as a reference to how it can be done :

- iw list (which output the following info ...)
![image](https://user-images.githubusercontent.com/38204874/67870967-51c33a00-fb38-11e9-8d2a-6da5ed7bac75.png)

Also, we can use the iw implementation for this method:
![image](https://user-images.githubusercontent.com/38204874/67874487-a74e1580-fb3d-11e9-9fa7-0b80b5ab5870.png)

Please look here https://godoc.org/github.com/remyoudompheng/go-netlink/nl80211.

- To get the channels, we need to use FREQUENCY_ATTR_FREQ and the "ieee80211_frequency_to_channel" method which is defined in util.c file  (https://github.com/Distrotech/iw/blob/distrotech-iw/util.c)

- To check if a current channel is disabled use FREQUENCY_ATTR_DISABLED.

- To get a radar detection channel use FREQUENCY_ATTR_RADAR.

- We can use the "print_phy_handler" method as a reference, which is defined in info.c file ----> https://github.com/Distrotech/iw/blob/distrotech-iw/info.c

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BWL nl80211 implementation](https://trello.com/c/xocDS5qw/23-bwl-nl80211-implementation)
