### ISSUE TITLE
Add comments explaining each parameter (BPL)

### ISSUE THREAD

**Issue by vitalybu** [prplfoundation/prplMesh#460]
I think we should add comments explaining each parameter, like done in `BPL_WLAN_PARAMS` for example

_Originally posted by @tomereli in https://github.com/prplfoundation/prplMesh/pull/456_

**Comment by vitalybu** [comment]
Please also pay attention to the following comments:
https://github.com/prplfoundation/prplMesh/pull/456#discussion_r341105864
https://github.com/prplfoundation/prplMesh/pull/456#discussion_r341106229
https://github.com/prplfoundation/prplMesh/pull/456#discussion_r341106834
https://github.com/prplfoundation/prplMesh/pull/456#discussion_r341109554

**Comment by tomereli** [comment]
@kantera800 , @morantr - please take this task with high priority.
