### ISSUE TITLE
[TASK] Fix maptools.py config & deploy sub-commands

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#476]
## Description

`maptools.py` has support for deploying build artifacts to the target, but it is currently broken.
The `config` subcommand was used in Intel to set up the target parameters (IP address, username and password) which is later used by the `deploy` subcommand to pack the outputs into a `tar.gz` archive which is then `scp`ed to the target.

The `config` subcommand is broken - it used internal Intel JIRA which is no longer available (it might be in the future), but it has support to set the needed parameters manually.

This task is aimed to fix these commands so that we can easily deploy built prplMesh to any target.

## Exit criteria

maptools can be used to build  + deploy prplMesh to any openwrt platform.

**Comment by arnout** [comment]
This will be done in a slightly different way in #676
