### ISSUE TITLE
[TASK] Gitlab CI: Use prpmesh-builder:ubuntu-18.04 for building and top-level clang-format in tests 

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#515]
This issue groups the remaining comments from #513. 

- [x] We can use the top-level clang-format.sh script itself if we run it in the appropriate docker container. It would also be nice to put this in a separate job so it can be done in parallel (of course the git diff-index has to be included in the same job).
- [x] For building, it should be possible to use the prplmesh-builder:ubuntu-18.04 container directly. Of course we can't use the shell runner then, so remove the shell tag. We'd first have to remove the entrypoint from that container so we have full flexibility for running stuff in it.

**Comment by arnout** [comment]
Both things added in later PRs that have been merged.
