### ISSUE TITLE
[TASK] Get platform version information

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#517]
## Description

There used to be some way to get information from the platform, but this was removed (in #514 commit 124b1c99a9066ad3a2c4f61605018249f4f6fec8) because it only worked on UGW.

Since platform information can be useful, we want to revive this. To make proper abstraction of the platform, however, it should be done in bpl_cfg, in a function bpl_cfg_get_platform_version_string() that returns a (possibly multiline) string with the version information.

**Comment by tomereli** [comment]
@Galvien please implement for UGW and RDKB. Sync with David Gabay for doing it properly on UGW, and with Gur Sanikov for doing it properly on RDKB.
