### ISSUE TITLE
[REFACTOR] master database should have different classes for different nodes

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#524]
Currently, the master database only has a `node` class, with a type field to indicate if it is a gateway, repeater, bridge, radio or BSS. However, this doesn't fit very well with how 1905.1/EasyMesh works. In addition, each node contains a lot of redundant data that is not relevant for that particular type. Finally, each node requires a unique MAC address, while in reality it is possible that repeater and bridge and radio and BSS all have the same MAC address.

Instead, it would be nicer to have separate classes for different types, i.e. device (=repeater or gateway), bridge, radio, BSS, with containment relationships between the different classes.

**Comment by morantr** [comment]
I have an idea which I planned in my mind for a long time how to do it.
The most important thing IMO is to get rid of the hierarchy in the database which complexes things up.
As for the class separation, I think that the criteria for separation is if the entity can stand on its own with no dependency, meaning that the only nodes in the database will be "platform" and "station".
as for the fronthaul radio, vaps and backhaul, they will be internally inside the platform node.

I want to take this task.
