### ISSUE TITLE
[TASK] Construct topology response message

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#525]
## Description

When an agent receives a topology query, it should reply with a topology response.

## Exit criteria

- [X] Agent (or discovery, cfr. #300) replies to Topology Query with a Topology Response.
- [x] Response contains device information TLV
- [ ] Response contains device bridging capability TLV
- [x] Response contains Supported Service TLV
- [x] Response contains AP Operational BSS TLV
- [x] Response contains  Associated Clients TLV

## Detailed description

The certification test only checks that it contains a SupportedService TLV and an OperationalBSS TLV. Still, controllers may expect it to also contain the other TLVs mandated by IEEE1905.1, so these should be included as well.

Currently, the topology query is captured by the agent, but no response is sent. As part of #300, this functionality will move to the discovery; for now, however, it can still be implemented as part of the agent.

The device information TLV should contain a list of interfaces, and the bridging capability TLV should contain a list of bridges with a list of interfaces per bridge. Since we only support a single bridge at the moment, the bridging capability TLV will contain the same interfaces as the device information TLV.

The device information TLV should ideally contain an entry for every port on the switch. However, often a switch chip has only one MAC address for all ports on that chip. Therefore, we should probably only include a single interface for all wired ethernet ports (even if the ports are identified by a separate interface at the Linux level, and even if some of them have different MAC addresses).

AP Operational BSS info can be retrieved from hostapd with GET_CONFIG command for each interface. The list of interfaces (= BSSes) can be retrieved with INTERFACES. Note that this information must come from the slaves, while the TLV is to be constructed by the backhaul manager (or discovery after #300), so extra ACTIONs will be needed for it.

Some additional TLVs are specified as required by 1905.1 and 1905.1a, but we can probably get away with not implementing them for now:

- non-1905 neighbor device list TLVs
- 1905.1 neighbor device TLVs
- power off interface TLV (1905.1a)
- L2 neighbor device TLV (1905.1a)

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Discovery response basic support](https://trello.com/c/o0Td3SMb/5-discovery-response-basic-support)

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Discovery agent full support](https://trello.com/c/6sFxLvDl/18-discovery-agent-full-support)

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [construct topology response message](https://trello.com/c/FTytSvTM/83-construct-topology-response-message)

**Comment by arnout** [comment]
We report only a single interface for the time being. Therefore, we don't need the device bridging capability TLV:
>  If a 1905.1 device has more than one interface, then the 1905.1 management entity shall include one device bridging capability TLV.

So for the time being, we don't need it. Therefore, I'm closing this issue and moving #701 to M3.
