### ISSUE TITLE
[BUG] controller: statistics_polling_task timeouts

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#527]
**Describe the bug** -
When the statistics polling task is enabled, the controller log is filled with prints from the statistics_polling_task which mention timeouts for each of the known slaves.

```
WARNING 10:36:57:803 <139995241241472> statistics_polling_task.cpp[94] --> task statistics polling task id 1: timeout slave 46:55:66:77:00:10                                                              
WARNING 10:36:59:360 <139995241241472> statistics_polling_task.cpp[94] --> task statistics polling task id 1: timeout slave 46:55:66:77:00:20                                                              
WARNING 10:36:59:360 <139995241241472> statistics_polling_task.cpp[94] --> task statistics polling task id 1: timeout slave 46:55:66:77:00:10                                                              
WARNING 10:37:00:916 <139995241241472> statistics_polling_task.cpp[94] --> task statistics polling task id 1: timeout slave 46:55:66:77:00:20                                                              
WARNING 10:37:00:917 <139995241241472> statistics_polling_task.cpp[94] --> task statistics polling task id 1: timeout slave 46:55:66:77:00:10   
```

## Steps to reproduce

1. Build
2. Run controller & agent
3. See the controller log - `tail -F /tmp/beerocks/logs/beerocks_controller.log`

## Expected behavior

statistics polling task should not timeout.

**Comment by morantr** [comment]
@tomereli your solution is a bandaid that doesn't solve the root cause. The problem now is that the controller will not have rx_rssi updates.

**Comment by tomereli** [comment]
> @tomereli your solution is a bandaid that doesn't solve the root cause. The problem now is that the controller will not have rx_rssi updates.

This is a workaround for the fact that the logs are clattered with these prints, not a solution. Ofcourse we need to fix it - but currently it blocked us from agent certification testing which is why I disabled it.
Feel free to take and fix this bug.
