### ISSUE TITLE
Perform static analysis on the code

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#539]
Code quality would be improved with static analysis on the code. Ideally this is done in CI, so that no issue ever appears.

Suggested tools:

- CppCheck
- clang-tidy
- clazy

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [tlvList refactoring](https://trello.com/c/JHrwp6IN/19-tlvlist-refactoring)
