### ISSUE TITLE
Proper implementation of Socket

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#546]
There are several things wrong with the Socket and beerocks_socket implementations:

- In general, readBytes() should be called in a loop to fetch the entire message;
- If a message is bigger than the buffer size, the socket becomes unusable (no recv() is ever done on it);

Probably more as well. It needs review.

**Comment by mariomaz** [comment]
See all comments related to sockets and socket_thread at https://github.com/prplfoundation/prplMesh/pull/538/commits/e983a1908b17d106a8c0e8f044565a8459301efe

**Comment by mariomaz** [comment]
If thinking of a big refactoring and not only in bug fixing: 
- Currently, sockets are used by inheriting socket_thread. IMO, we should [“favor composition over inheritance”](https://en.wikipedia.org/wiki/Composition_over_inheritance) instead. 
- Consider using the [Reactor Design Pattern](https://www.dre.vanderbilt.edu/~schmidt/PDF/reactor-rules.pdf) here to handle both socket I/O and timer events.
- Code should be testable by programming to interfaces and using dependency injection.

**Comment by arnout** [comment]
The person who wrote this issue was an idiot. UDS is message-oriented, so none of the issues mentioned can actually occur. Only the UCC socket (which is TCP) has this issue.
