### ISSUE TITLE
[TASK] Initial BU Intel IP repeater - port existing Repeater functionality to prplMesh

### ISSUE THREAD

**Issue by adam1985d** [prplfoundation/prplMesh#556]
As part of porting RDKB code to prplMesh the Standalone Repeater functionality was broken due to:
1.  send_slaves_enable() implementation was changed to send bandwidth and center_channel, which are read from "radio_info" struct after a "refresh_radio_info()" was performed - but the refresh_radio_info() doesn't yet support STA radio info.
- [x] revert implementation change which was done as part of port of RDKB code to prplMesh
- [x] create tasks: 1) add STA support in refresh_radio_info(). 2) Extend send_slaves_enable() to provide bandwidth and center_frequency
2. Waver in RDKB could not have been ported to prplMesh.
In RDKB MESH is not yet supported and the check "reject join if GW haven't joined yet" done as part of slave_join in controller (and relevant for MESH only) was commented-out. The commenting-out was not ported but no other solution was provided. Need to encapsulate this check with not-standalone-repeater condition.
- [x] add not-standalone-repeater condition to "reject join if GW haven't joined yet" done as part of slave_join in controller

#581

**Comment by tomereli** [comment]
@adam1985d please also create a card in our Trello board for this - https://trello.com/b/LYqZPvqT/prplmesh-agile-board

**Comment by adam1985d** [comment]
> @adam1985d please also create a card in our Trello board for this - https://trello.com/b/LYqZPvqT/prplmesh-agile-board

done - please review it in Trello board

**Comment by adam1985d** [comment]
mistakenly closed
