### ISSUE TITLE
[BUG] agent: occasional slave reset after join attempt

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#560]
Occasionally, a slave resets when it receives M2 (i.e. during onboarding or after autoconfig renew).

## Steps to reproduce

Unfortunately, there is no reliable reproducer.

## Target

Ubuntu in docker with test_flows.sh.

## Analysis

During one reproduction, I was able to add some logging which led me to determine the following:

- slave reset is due to authentication failure of M2;
- It is the "authenticator" of the entire M2 that fails (so not the keywrap authenticator);
- M1 and M2 used to calculate the authenticator are the same.

That leaves the following possible reasons for authentication failure:

- authkey is different;
- M1 and M2 are the same but the buffer over which authenticator is calculated is not (i.e. something wrong when copying);
- length of the buffer is different;
- comparison is wrong;
- algorithm to compute authenticator is wrong.

**Comment by arnout** [comment]
Based on https://travis-ci.org/prplfoundation/prplMesh/builds/623684002 it turns out the key is wrong:

```
DEBUG 14:06:56:597 <140043240475520> son_master_thread.cpp[618] --> authenticator key: c4 57 6e 8f 5b ec 70 cf af ed 89 af 77 56 dd e5 
51 aa ca f1 a1 0f 18 3b e6 56 14 59 65 9d 44 4b 

DEBUG 14:06:56:601 <140130537585536> son_slave_thread.cpp[3594] --> authenticator key: 75 a4 19 31 de 36 de 3c 4d 85 08 bd 3b d4 5c 00 
42 ff 6b b0 99 2f 99 51 b4 ad 79 8e 37 31 c6 cd 
```

**Comment by rmelotte** [comment]
For reference: an archive with logs from when the issue occurs is available here: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/410244207/artifacts/file/glinet-b1300-1_logs.tar.gz .
