### ISSUE TITLE
[TASK] port Dynamic channel selection (DCS) feature from RDKB

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#562]
## Description

This task will be focused on porting Dynamic Channel Selection code from Intel repositories (RDKB) .

## Exit criteria

- run DCS feature on RDKB platform and pass attached unitest.

- pass all prplMesh CI checks.

## Detailed description

The DCS as a feature can provides information on the supported channels which can be utilized by the management system to provide better availability and user experience.

The feature is divided into two sub-features:
1. Channel Scan using NL & DWPAL
Uses the DWPAL to perform a netlink channel scan to find all neighboring APs
2. Dymanic Channel Selection & Analysis
Returns the Channel Scan results to provide the current status of the channels

The feature is presented in five segments each will have its own PR as follows:

- [x] Low Level Infastructure (DWPAL): NL support in BWL

- [feature/port-dynamic-channel-selection-from-rdkb-bwl](https://github.com/prplfoundation/prplMesh/tree/feature/port-dynamic-channel-selection-from-rdkb-bwl) > [PR #637](https://github.com/prplfoundation/prplMesh/pull/637) **Merged**
- bwl: cmake: add nl libs for dwpal
- bwl: Add NL support (with stubs)
- bwl: Add NL DWPAL base implementation
- bwl: Add NL DWPAL monitor implementation

- [x] High Level Infastructure (Controller & yaml): Support for Channel Scan & DCS

- [feature/port-dynamic-channel-selection-from-rdkb-infastructure](https://github.com/prplfoundation/prplMesh/tree/feature/port-dynamic-channel-selection-from-rdkb-infastructure) > [PR #643](https://github.com/prplfoundation/prplMesh/pull/643) **Merged**
- beerocks defines: enum definitions for Channel Scan & DCS
- yaml: beerocks_message_common: Add channel scan structures
- yaml: beerocks_message_control: Add channel scan & DCS CMDUs
- controller: node: Add channel scan structures
- controller: DB: Add channel scan DB methods

- [x] Dymanic Channel Selection Task

- [feature/port-dynamic-channel-selection-from-rdkb-task](https://github.com/prplfoundation/prplMesh/tree/feature/port-dynamic-channel-selection-from-rdkb-task) > [PR #644](https://github.com/prplfoundation/prplMesh/pull/644) **Merged**
- controller: task: add clear pending events
- controller: dymanic channel selection task intro
- controller: DCS task: FSM
- controller: DCS task: events
- controller: DCS task: node & DB

- [x] Flow (Controller & Agent)

- [feature/port-dynamic-channel-selection-from-rdkb-flow](https://github.com/prplfoundation/prplMesh/tree/feature/port-dynamic-channel-selection-from-rdkb-flow) > [PR #694](https://github.com/prplfoundation/prplMesh/pull/694) **Merged**
- agent: monitor_thread: proccess nl events
- agent: monitor_thread: handle channel scan events
- agent: monitor_thread: handle channel scan trigger CMDU
- controller & agent: master & slave: DCS channel scan
- controller: son_managment: DCS channel scan stubs
- controller: son_managment: DCS channel scan
- controller: bml: DCS channel scan setup
- controller: bml: DCS channel scan, set/get enable
- controller: bml: DCS channel scan, set/get params
- controller: bml: DCS channel scan, start single scan
- controller: bml: DCS channel scan, get results

- [x] Translate NL

- [feature/port-dynamic-channel-selection-from-rdkb-translation](https://github.com/prplfoundation/prplMesh/tree/feature/port-dynamic-channel-selection-from-rdkb-translation) > [PR #713](https://github.com/prplfoundation/prplMesh/pull/713) **Merged**
- bwl: dwpal: mon: fix clang
- bwl: add common channel scan result structures
- bwl: dwpal: add defines for nl scan dump message parser
- bwl: dwpal: translate message from netlink
- bwl: dwpal: process channel scan dump result
- agent: monitor_thread: add channel scan results translation

- [x] BML CLI

- [feature/add-bml-cli-commands-to-dynamic-channel-selection-bml-apis](https://github.com/prplfoundation/prplMesh/tree/feature/add-bml-cli-commands-to-dynamic-channel-selection-bml-apis) > [PR #699](https://github.com/prplfoundation/prplMesh/pull/699) **Merged**
_Add BML CLI to test and operate the feature by using the BML APIs_

- [x] validation  - [hotfix/fix-dcs-scan-flow-ugw] **in progress**

- [x] DCS cleanups - [PR #665](https://github.com/prplfoundation/prplMesh/issues/665)   **done**  PR https://github.com/prplfoundation/prplMesh/pull/1202

During the reviews some issues that came up were moved to a dedicated issue of unresolved review requests
After all branches are merged, any remaining issues in the task will be added as `bugfix` or `hotfix` PRs

[DCS_HAL API unitest - final.xlsx](https://github.com/prplfoundation/prplMesh/files/3950249/DCS_HAL.API.unitest.-.final.xlsx)

**Comment by arnout** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Port dynamic channel selection](https://trello.com/c/65NWF2dD/42-port-dynamic-channel-selection)

**Comment by kantera800** [comment]
@itayx we still have to do DCS cleanups - PR #665
