### ISSUE TITLE
[TASK] Add syslog support (instead or in addition to file logging)

### ISSUE THREAD

**Issue by vitalybu** [prplfoundation/prplMesh#573]
## Description

Add support for using syslog instead or in addition to the existing file logging mechanism.

## Exit criteria

All prplMesh components support syslog logging.

**Comment by arnout** [comment]
Note that his is already implemented by easlogging++, so you just need to define ELPP_SYSLOG and set to_syslog to true in the config file.

**Comment by vitalybu** [comment]
Yup. But I also want to add an option to disable the log files.
