### ISSUE TITLE
[TASK] run prplMesh from non-root user in UGW

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#591]
/etc/init.d/prplmesh - start prplmesh in init with nwk or other prplmesh user (non root)

**Comment by adam1985d** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support of PRPL in UGW](https://trello.com/c/iPT5XVhx/44-add-support-of-prpl-in-ugw)

**Comment by kantera800** [comment]
handled in UGW feed repo.
