### ISSUE TITLE
[TASK] change ownership to non root user in UGW Makefile

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#592]
Use  nwk  or create prplMesh its own user

branch:
https://github.com/prplfoundation/prplMesh/tree/feature/add-prpl-to-initd-and-run-as-nwk-user

**Comment by adam1985d** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support of PRPL in UGW](https://trello.com/c/iPT5XVhx/44-add-support-of-prpl-in-ugw)

**Comment by kantera800** [comment]
handled in UGW feed repo.
