### ISSUE TITLE
[TASK] add raw sockets permission to agent in UGW

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#593]
during install need to add nwk or other dedicated prplmesh user with relevant permissions (cap_net_raw)

**Comment by adam1985d** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support of PRPL in UGW](https://trello.com/c/iPT5XVhx/44-add-support-of-prpl-in-ugw)

**Comment by kantera800** [comment]
handled in UGW feed repo.
