### ISSUE TITLE
[TASK] DCS cleanups

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#665]
# Cleanups
> Fix all remaining review comments which were marked as such which can be cleaned up later.
> Each review comment should be tagged in this issue.
### common/beerocks/bwl/CMakeLists.txt:62
- `list(APPEND BWL_LIBS dwpal nl-3 nl-genl-3)`
- Perhaps it's better to create a FindNL cmake file and use the standard cmake find_package(). Here's an example: https://github.com/nasa/channel-emulator/blob/master/cmake/Modules/FindLibNL.cmake
- Fixed in #680 
### common/beerocks/bwl/dwpal/base_wlan_hal_dwpal.cpp:311
- ` if (!m_dwpal_nl_ctx) {`
- The dwpal netlink context is created in the Init state.
- On failure, we transition the FSM to the Detach state.
- In what scenario do we get to the Attach state without a valid context? this statement is redundant.
- RAX40 has a much older driver version at the moment so the attach will fail
- We mustn't fail the FSM on that! Just log an warning and proceed without NL. Similar to what we do when we lack permissions to open raw socket - we simply don't open it.
- Still, this should be removed
### Remove / Alter redundant logs
- common/beerocks/bwl/dwpal/mon_wlan_hal_dwpal.cpp:467
- common/beerocks/bwl/dwpal/base_wlan_hal_dwpal.cpp:594
- common/beerocks/bwl/dummy/base_wlan_hal_dummy.cpp:284
### Small patches
- common/beerocks/bwl/dwpal/base_wlan_hal_dwpal.cpp:311 This should be removed
- common/beerocks/bwl/dwpal/base_wlan_hal_dwpal.cpp:593 `if (!vendor_data) { ... }`
- common/beerocks/bwl/dwpal/base_wlan_hal_dwpal.cpp:616 `if (!out_buffer) { ... }`
- common/beerocks/bwl/dwpal/base_wlan_hal_dwpal.cpp:609 Function should return ssize_t (signed size_t).
- common/beerocks/bwl/dwpal/base_wlan_hal_dwpal.cpp:626 Either initialize data_size to -1, or simply return -1 here to indicate a failure.
### Remove USE_LIBSAFEC from other files
- common/beerocks/bwl/dwpal/base_wlan_hal_dwpal.h:23
### No additional comment
- common/beerocks/bwl/dwpal/base_wlan_hal_dwpal.cpp:675
- common/beerocks/bwl/dwpal/mon_wlan_hal_dwpal.cpp:73
### remove `dummy_return`
- controller/src/beerocks/master/db/db.cpp:2355
- controller/src/beerocks/master/db/db.cpp:2300
### controller/src/beerocks/master/db/db.h:400
- bool channel_scan_enabled(const std::string &mac) const; //get
- void channel_scan_enabled(const std::string &mac, bool enable); //set
### Enum refactoring
- common/beerocks/bcl/include/bcl/beerocks_defines.h:450
- common/beerocks/bcl/include/bcl/beerocks_defines.h:461
### `set_channel_scan_in_progress`, check if can read task fsm state instead
- controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp: 81
### enum -> class enum
- common/beerocks/bwl/include/bwl/mon_wlan_hal_types.h:351
- `enum class eChannelScanResultMode : uint8_t {NA, AdHoc, Infra};`
### Check with driver team to validate our flow for translation
- common/beerocks/bwl/include/bwl/mon_wlan_hal_types.h:411 `security_mode_enabled`
- common/beerocks/bwl/include/bwl/mon_wlan_hal_types.h:414 `encryption_mode`

issues check list:

- [ ] https://github.com/prplfoundation/prplMesh/pull/637#discussion_r363859957

**Comment by itayx** [comment]
### controller/src/beerocks/master/db/db.h:400
- bool channel_scan_enabled(const std::string &mac) const; //get
- void channel_scan_enabled(const std::string &mac, bool enable); //set

Changing this breaks the existing pattern of a "Get" & "Set" in the DB

**Comment by itayx** [comment]
### `set_channel_scan_in_progress`, check if can read task fsm state instead
- controller/src/beerocks/master/tasks/dynamic_channel_selection_task.cpp: 81

The `scan_in_progress` flag is access from outside the task, in the son_management.
Therefore using a flag variable in the DB is easier & cleaner then trying to access the FSM state which is a private variable within the DCS task.
