### ISSUE TITLE
[BUG] Certification test 5.6.2 fails

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#668]
Controller certification tests 5.6.2 (all variants) fail on fefec5fe1e32fa806f9aeab8d9ff947cc45b5d06.

Logs can be found here: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/401365002/artifacts/browse/logs/FAIL/

**Comment by arnout** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check controller certification test failures](https://trello.com/c/iJIjpQJp/68-check-controller-certification-test-failures)

**Comment by arnout** [comment]
This is a problem in the certification setup: the Marvell STA doesn't report the correct MAC address:

> 2020-01-13 18:18:23.993 - INFO - MarvellSTA (127.0.0.1:9000) ---> sta_get_mac_address,interface,mlan0
> 2020-01-13 18:18:33.042 - INFO - MarvellSTA (127.0.0.1:9000) <-- status,COMPLETE,mac,00:00:00:00:00:00

This is probably due to the PCI reset that we do to make sure the radio recovers from errors (it is pretty unstable...). @rmelotte will investigate further.

**Comment by rmelotte** [comment]
It should be fixed with the latest modifications in the easymesh_cert repo, waiting for [the pipeline](https://gitlab.com/prpl-foundation/prplMesh/-/jobs/402466750) to complete to confirm.

**Comment by rmelotte** [comment]
I believe it was fixed, although not all the tests were successful (they failed because the marvell sta agent randomly didn't start).
I'll try a quick fix to make the marvell agent fail less often, and run a new pipeline.

**Comment by rmelotte** [comment]
5.6.2 passes.
The marvell agent now fails less often. Other tests are still failing, but it looks like a completely different issue, so closing.
