### ISSUE TITLE
[BUG] Certification test MAP-5.8.1_ETH_FH24G fails

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#670]
Controller certification tests MAP-5.8.1_ETH_FH24G fail on fefec5f.

Logs can be found here: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/401365002/artifacts/browse/logs/FAIL/

**Comment by arnout** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check controller certification test failures](https://trello.com/c/iJIjpQJp/68-check-controller-certification-test-failures)

**Comment by rmelotte** [comment]
This one is most probably failing for the same reasons as #668 (problem with the certification setup itself, not prplMesh).
Will test it once again once #668 is fixed.

**Comment by rmelotte** [comment]
It has been fixed with commit `be7b8f4a7a30960edf2109e8127e120bf58eaebd` in [easymesh_certs/marvell_sta_ucc_agent](https://gitlab.com/prpl-foundation/easymesh_cert/marvell_sta_ucc_agent).
See this pipeline: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/402466750 .
