### ISSUE TITLE
[BUG] UGW: master doesn't build (linker issue)

### ISSUE THREAD

**Issue by adam1985d** [prplfoundation/prplMesh#679]
[prplMesh master 7e9a1da3+M]$ ./tools/maptools.sh build map -f 'MSGLIB=None'
[build:170] - INFO - ['make'] ['map']
[build:60] - INFO - /local/adovx/dev3/prplMesh/build/. already prepared, skip cmake .
[build:85] - INFO - building & installing .: cmake --build /local/adovx/dev3/prplMesh/build/. --target install -- -j 29
[  1%] Built target elpp
[  4%] Built target common
[ 38%] Built target tlvf
[ 45%] Built target bpl
[ 54%] Built target bcl
[ 58%] Built target bwl
[ 66%] Built target btlvf
[ 68%] Built target btl
[ 72%] Built target beerocks_monitor
[ 77%] Built target bml
[ 78%] Linking CXX executable ../../../../out/bin/beerocks_agent
[ 82%] Built target beerocks_cli
[ 96%] Built target beerocks_controller
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: CMakeFiles/beerocks_agent.dir/backhaul_manager/backhaul_manager_thread.cpp.o: in function `beerocks::backhaul_manager::handle_1905_discovery_query(ieee1905_1::CmduMessageRx&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
backhaul_manager_thread.cpp:(.text+0x8d84): undefined reference to `wfa_map::tlvApOperationalBSS::tlvApOperationalBSS(std::shared_ptr<BaseClass>, bool)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8d8c): undefined reference to `wfa_map::tlvApOperationalBSS::tlvApOperationalBSS(std::shared_ptr<BaseClass>, bool)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8ea8): undefined reference to `wfa_map::tlvApOperationalBSS::create_radio_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8eb0): undefined reference to `wfa_map::tlvApOperationalBSS::create_radio_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8ec0): undefined reference to `wfa_map::cRadioInfo::create_radio_bss_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8ec8): undefined reference to `wfa_map::cRadioInfo::create_radio_bss_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8f18): undefined reference to `wfa_map::cRadioBssInfo::set_ssid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8f20): undefined reference to `wfa_map::cRadioBssInfo::set_ssid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8f84): undefined reference to `wfa_map::cRadioInfo::add_radio_bss_list(std::shared_ptr<wfa_map::cRadioBssInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8f8c): undefined reference to `wfa_map::cRadioInfo::add_radio_bss_list(std::shared_ptr<wfa_map::cRadioBssInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8fc0): undefined reference to `wfa_map::cRadioInfo::create_radio_bss_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x8fc8): undefined reference to `wfa_map::cRadioInfo::create_radio_bss_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9064): undefined reference to `wfa_map::cRadioBssInfo::set_ssid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x906c): undefined reference to `wfa_map::cRadioBssInfo::set_ssid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x90d4): undefined reference to `wfa_map::cRadioInfo::add_radio_bss_list(std::shared_ptr<wfa_map::cRadioBssInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x90dc): undefined reference to `wfa_map::cRadioInfo::add_radio_bss_list(std::shared_ptr<wfa_map::cRadioBssInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x913c): undefined reference to `wfa_map::tlvApOperationalBSS::add_radio_list(std::shared_ptr<wfa_map::cRadioInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9144): undefined reference to `wfa_map::tlvApOperationalBSS::add_radio_list(std::shared_ptr<wfa_map::cRadioInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x927c): undefined reference to `wfa_map::tlvAssociatedClients::tlvAssociatedClients(std::shared_ptr<BaseClass>, bool)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9284): undefined reference to `wfa_map::tlvAssociatedClients::tlvAssociatedClients(std::shared_ptr<BaseClass>, bool)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9380): undefined reference to `wfa_map::tlvAssociatedClients::create_bss_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9388): undefined reference to `wfa_map::tlvAssociatedClients::create_bss_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9398): undefined reference to `wfa_map::cBssInfo::create_clients_associated_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x93a0): undefined reference to `wfa_map::cBssInfo::create_clients_associated_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x93b0): undefined reference to `wfa_map::cClientInfo::mac()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x93b8): undefined reference to `wfa_map::cClientInfo::mac()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9460): undefined reference to `wfa_map::cClientInfo::time_since_last_association_sec()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9468): undefined reference to `wfa_map::cClientInfo::time_since_last_association_sec()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x94b0): undefined reference to `wfa_map::cBssInfo::add_clients_associated_list(std::shared_ptr<wfa_map::cClientInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x94b8): undefined reference to `wfa_map::cBssInfo::add_clients_associated_list(std::shared_ptr<wfa_map::cClientInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x94ec): undefined reference to `wfa_map::cBssInfo::create_clients_associated_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x94f4): undefined reference to `wfa_map::cBssInfo::create_clients_associated_list()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9504): undefined reference to `wfa_map::cClientInfo::mac()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x950c): undefined reference to `wfa_map::cClientInfo::mac()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x95b0): undefined reference to `wfa_map::cClientInfo::time_since_last_association_sec()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x95b8): undefined reference to `wfa_map::cClientInfo::time_since_last_association_sec()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9600): undefined reference to `wfa_map::cBssInfo::add_clients_associated_list(std::shared_ptr<wfa_map::cClientInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9608): undefined reference to `wfa_map::cBssInfo::add_clients_associated_list(std::shared_ptr<wfa_map::cClientInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9668): undefined reference to `wfa_map::tlvAssociatedClients::add_bss_list(std::shared_ptr<wfa_map::cBssInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x9670): undefined reference to `wfa_map::tlvAssociatedClients::add_bss_list(std::shared_ptr<wfa_map::cBssInfo>)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x96a4): undefined reference to `wfa_map::cBssInfo::bssid()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0x96ac): undefined reference to `wfa_map::cBssInfo::bssid()'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0xa2cc): undefined reference to `wfa_map::tlvApOperationalBSS::tlvApOperationalBSS(unsigned char*, unsigned int, bool)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0xa2d4): undefined reference to `wfa_map::tlvApOperationalBSS::tlvApOperationalBSS(unsigned char*, unsigned int, bool)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0xa344): undefined reference to `wfa_map::tlvAssociatedClients::tlvAssociatedClients(unsigned char*, unsigned int, bool)'
/local/adovx/dev3/ugw_sw/openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-6.3.0_musl/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: backhaul_manager_thread.cpp:(.text+0xa34c): undefined reference to `wfa_map::tlvAssociatedClients::tlvAssociatedClients(unsigned char*, unsigned int, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [out/bin/beerocks_agent] Error 1
make[1]: *** [agent/src/beerocks/slave/CMakeFiles/beerocks_agent.dir/all] Error 2
make: *** [all] Error 2
ASSERT: Command '['cmake', '--build', '/local/adovx/dev3/prplMesh/build/.', '--target', 'install', '--', '-j', '29']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/local/adovx/dev3/prplMesh/tools/maptools.py", line 92, in <module>
    maptools().run()
  File "/local/adovx/dev3/prplMesh/tools/maptools.py", line 83, in run
    commands[self.args.cmd]()
  File "/local/adovx/dev3/prplMesh/tools/maptools.py", line 61, in __build__
    mapbuild(self.args)
  File "/local/adovx/dev3/prplMesh/tools/commands/build.py", line 208, in __init__
    self.run_command(builder, commands)
  File "/local/adovx/dev3/prplMesh/tools/commands/build.py", line 218, in run_command
    builder.make()
  File "/local/adovx/dev3/prplMesh/tools/commands/build.py", line 86, in make
    subprocess.check_call(cmd, env=self.env)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/local/adovx/dev3/prplMesh/build/.', '--target', 'install', '--', '-j', '29']' returned non-zero exit status 2

**Comment by adam1985d** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UGW build bug](https://trello.com/c/1Bkd7CRv/71-ugw-build-bug)

**Comment by tomereli** [comment]
Doesn't reproduce, closing
