### ISSUE TITLE
[BUG] Controller certification tests fail on master 

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#681]
19/23 tests failed on master (`556f54dc1feb5d7b7ba85f924b71436fbbd08393`).

The logs are available here: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/403667226 .

The first noticable thing is that beerocks_agent.log contains a lot of these:
```
ERROR 16:39:14:753 <139724723128064> tlvAssociatedClients.cpp[225] --> TLVF: Requested index is greater than the number of available entries
```

**Comment by rmelotte** [comment]
All the tests have been triggered a second time here, and it looks like the issue is the same:
https://gitlab.com/prpl-foundation/prplMesh/-/jobs/404057100

**Comment by arnout** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check controller certification test failures](https://trello.com/c/iJIjpQJp/68-check-controller-certification-test-failures)

**Comment by arnout** [comment]
There are a couple of different failure causes:

1. Marvell agent doesn't work (fails on dev_set_config).
   - MAP-5.10.1
   - MAP-5.4.3_ETH_FH24G
   - MAP-5.4.3_ETH_FH5GH
   - MAP-5.4.3_ETH_FH5GL
   - MAP-5.7.1
2. Broadcom agent fails on M2.
   - MAP-5.4.2_ETH_FH24G
   - MAP-5.4.2_ETH_FH5GH
   - MAP-5.4.2_ETH_FH5GL
   - MAP-5.8.2_ETH_FH24G
   - MAP-5.8.2_ETH_FH5GH
   - MAP-5.8.2_ETH_FH5GL
3. Sniffer doesn't find AP Radio ID TLV.
   - MAP-5.4.1_ETH_FH24G
   - MAP-5.4.1_ETH_FH5GH
   - MAP-5.4.1_ETH_FH5GL
4. Marvell STA fails to connect.
   - MAP-5.6.2_ETH_FH24G
   - MAP-5.6.2_ETH_FH5GH
   - MAP-5.6.2_ETH_FH5GL
5. Topology response from agent is missing AP Operational BSS TLV
   - MAP-5.8.1_ETH_FH24G
6. Sniffer doesn't see Qualcomm agent's beacons
   - MAP-5.8.3_ETH_FH5GL

I'll study each of these categories in more detail.

**Comment by arnout** [comment]
I haven't checked the details of all of them, but they might all be due to the same issue...

For some reason, our WSC M2 encrypted settings has become huge (> 1000 bytes), which causes the WSC message to be fragmented. As we know from the agent tests, the testbed devices don't necessarily work correctly with fragmented CMDUs. But also, if the encrypted settings are so large, it's possible there's something completely wrong in there which misconfigures the agents.

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [controller certification tests fail on master](https://trello.com/c/mgatEMfA/88-controller-certification-tests-fail-on-master)
