### ISSUE TITLE
[TASK] Completely remove radio UID from agent and controller

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#691]
## Description

Beerocks had the concept of a "Radio UID" and "Radio MAC" as two separate values. In EasyMesh, however, there is only a Radio UID. It's simpler to use the radio's MAC address as Radio UID, so let's do that everywhere.

#431 already partly did that in the agent - the Radio UID is only used in internal messages within the agent and in the Intel VS Slave Join message.

## Exit criteria

- No references remain to the "Radio UID" as used in beerocks.
- Radio MAC is used everywhere.

## Detailed description

See also
https://github.com/prplfoundation/prplMesh/pull/431#issuecomment-576239843

Reasons for preferring Radio MAC:

- No need to specify the ID in configuration file - the radio interface name is sufficient, we can get the MAC address from there.
- It is also possible for other tools (e.g. test_flows) to discover the radio ID with a simple `ip link show`. The radio ID from the configuration file would require parsing that file.
- Radio ID can be 00:00:00:00:00:00, which is not a valid MAC address. Some agents/controllers may have a problem with that.
- bml_conn_map prints Radio MAC; if we would use Radio UID, it wouldn't be able to print anything.

This issue will require at least three commits: one to remove it completely from the controller, a second one to remove it from the Slave Join message, and finally remove it completely from the agent.

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove radio UID from agent and controller](https://trello.com/c/vtAozqFq/86-remove-radio-uid-from-agent-and-controller)
