### ISSUE TITLE
[TASK] Implement EasyMesh channel selection

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#725]
## Description

In slave_thread::handle_channel_selection_request(), send a message to the ap manager to perform the actual channel switch.

## Exit criteria

-  slave_thread::handle_channel_selection_request() sends a message to ap manager thread.
- This message contains all information from the channel selection request, including the power limit.
- ap manager thread takes into account this information to perform channel selection.

## Detailed description

This is needed for certification. Certification sends a request with a single channel enabled (= all channels except one disabled). Certification also sends a power limit. Current Intel VS implementation doesn't have a power limit so that needs to be added.

After channel switch an operating channel report must be sent. This is part of #369.

**Comment by morantr** [comment]
https://github.com/prplfoundation/prplMesh/issues/62
