### ISSUE TITLE
[TASK] Add a tag in CI when certification tests pass

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#742]
## Description

It would be useful to have a moving tag which always has the certification tests passing.

Since certification tests still fail sporadically, it would be easier to have a separate tag for each target, so that if a test fail on one target but they all pass on another, it doesn't prevent the tag from being updated.

Note that the tag would not be effectively created until #669 is still closed (since it makes the certification job fail).

## Exit criteria

- [ ] CI runs scheduled controller certification tests on both rax40 and dummy bwl (separate job).

- [ ] CI adds/updates a tag when scheduled certification tests passed in CI.

- [ ] A separate tag is used for each target (rax40 and dummy).

**Comment by ghost** [comment]
Closing this issue because:
* It's not a priority
* It turns out to require a lot more work than initially planned

**Comment by rmelotte** [comment]
For reference, there there is very a relevant feature request on gitlab-org: https://gitlab.com/gitlab-org/gitlab/issues/16290
