### ISSUE TITLE
[TASK] Run agents tests nightly in CI

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#746]
## Description

As soon as a new agent test is passing on the rax40, it could already be added to the nigthly schedule to be able to spot any regression. 

This task depends on #741 .

## Exit criteria

- [ ] Test at least 4.4.1 with the rax40 manually.

- [ ] Once the test is passing, add a nightly schedule with agent tests, only 4.4.1 at first.

**Comment by ghost** [comment]
Blocked by #748 and #741

**Comment by rmelotte** [comment]
Done, the schedule name is `Nightly certification tests - agent - rax40`: https://gitlab.com/prpl-foundation/prplMesh/pipeline_schedules
