### ISSUE TITLE
[BUG] easylogging++: Observed SIGSEGV to beerocks_agent (due to easylogging++ access attempt to released memory)

### ISSUE THREAD

**Issue by adam1985d** [prplfoundation/prplMesh#750]
on UGW only beerocks_agent receives SIGSEGV when slave reset is performed for beerocks_agent_wlan0/2.
reproduced on UGW only - due to differences in GCC which lead to differences in the order of resource release (a statically initialize Class data member is released before the registered classes which hold a pointer to his data_member are released)

## Steps to reproduce
on Axe point:
1. get beerocks_agent wlan0/2 pid
ps | beerocks
2. kill the wlan0 or the wlan2 process (important to allow the orderly shutdown of the process and **not** use kill -9!)
kill <pid>

## Expected behavior
you will see a crash indicating the page_fault:
Caught signal 'Interrupt[ 8013.516064] do_page_fault(): sending SIGSEGV to beerocks_agent for invalid write access to 00000008
[ 8013.525069] epc = 77726e78 in libc.so[776fe000+98000]
[ 8013.529971] ra  = 777275a0 in libc.so[776fe000+98000]

**Comment by adam1985d** [comment]
root@ugwcpe:/tmp/deploy# ./beerocks_agent
unregister - uniqKey = default
registerNew - uniqKey = default, ptr = 0x771a9c70
unregister - uniqKey = syslog
registerNew - uniqKey = syslog, ptr = 0x77413c80
<INFO> Reconfiguring logger [syslog]
<INFO> Flushing logger [syslog] all levels
~TypedConfigurations - ENTER
m_logStreamsReference = 0x76fec774
~TypedConfigurations - EXIT
<INFO> Easylogging++ has been initialized
Hello World!

^C**Caught signal 'Interrupt[ 8013.516064] do_page_fault(): sending SIGSEGV to beerocks_agent for invalid write access to 00000008
[ 8013.525069] epc = 77726e78 in libc.so[776fe000+98000]
[ 8013.529971] ra  = 777275a0 in libc.so[776fe000+98000]**
' Exiting...m_registeredLoggers = 0x76fec6f0
1
<INFO> Destroying storage
2
<INFO> Destroying registeredHitCounters
3
m_registeredLoggers = 0x76fec6f0
<INFO> Destroying registeredLoggers
~RegisteredLoggers()
m_logStreamsReference.size() = 1
m_loggerRegistrationCallbacks.size() = 0
<INFO> Flushing all log files
~RegisteredLoggers() - END **<---"RegisteredLoggers object is destroyed and releases the object that m_logStreamsReference is pointing to"**
~Registry() - ENTER
this->list().size() = 2
curr.second = 0x77413c80
~Logger - ENTER
m_typedConfigurations = 0x76decbf0
~TypedConfigurations - ENTER
m_logStreamsReference = 0x76fec774 **<---"m_logStreamsReference is being released but already released by RegisterredLoggers class"**
~TypedConfigurations - EXIT
Segmentation fault

**Comment by tomereli** [comment]
Please also add links to Intel JIRAs so it will be easier for us to track

**Comment by adam1985d** [comment]
#751

**Comment by adam1985d** [comment]
Intel related Jiras:
https://jira-chd.intel.com/browse/WLANRTSYS-19243
https://jira-chd.intel.com/browse/WLANRTSYS-18546
https://jira-chd.intel.com/browse/WLANRTSYS-19405

**Comment by adam1985d** [comment]
> Please also add links to Intel JIRAs so it will be easier for us to track

done

**Comment by tomereli** [comment]
Fixed in #738
