### ISSUE TITLE
[BUG] Disable UCC Listener on Agent by UCI configuration

### ISSUE THREAD

**Issue by morantr** [prplfoundation/prplMesh#756]
## Description

UCC Listeners use port 8001 and 8002 to communicate between the UCC and prplMesh.
UGW uses these ports for internal operation and when the UCC listener tries to use this port as well, it causes bus errors.

To solve it, we need to disable certification mode on UGW on the UCI.
The problem is that certification mode defined in the UCI, is not used in order to run the UCC Listener on the Agent, what is used is the UCC Listener port which defined on the Controller/Agent configuration file.

## Solution Options
1. Remove "Certification mode" from the database, and replace it with UCC Listener Port.
2. Make the UCC Listener run on the Agent only if the  "Certification mode" is enabled on the UCI database.

Personally, I prefer solution 1, since "Certification mode" flag is redundant, and it is enough to read the Port number, so If the port is 0, then certification mode is off.

**Comment by tomereli** [comment]
Intel JIRA - https://jira-chd.intel.com/browse/LMTSYS-2688

**Comment by tomereli** [comment]
Solution is to do this in both controller and agent.

## Controller 
Create and start the UCC listener only after receiving platform settings *if* certification mode enabled

## Agent
Add platform settings to backhaul manager and start the listener only after receiving platform settings *if* certification mode enabled

Please split this issue to 2 PRs - one for the agent, one for the controller - start with the controller.

**Comment by tomereli** [comment]
Fixed.
