### ISSUE TITLE
[TASK] Reliable multicast

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#769]
## Description

Multi-AP has a "reliable multicast" feature (which is used only for Topology Notification). It re-sends a copy of the relayed multicast as a unicast (with the same MID) .

## Exit criteria

- Reliable multicast packets are identified (based on message type)
- A unicast copy is made after relaying
- Received duplicates are ignored (and not relayed)

## Notes

The transport mentions this feature in a comment, but it doesn't seem to be implemented. Ignoring duplicates seems to be implemented however.

A list of known neighbours is required to implement this. Only the topology discovery knows this, so a copy must be made to the transport.

**Comment by arnout** [comment]
The known neighbours list can be hacked by interpreting the topology notification messages that come in and build a up list of neighbours from that. Eventually we need to also remove neighbours from this list, but for certification just adding them should be sufficient.

**Comment by arnout** [comment]
For the "discovered devices", the agent now has m_1905_neighbor_devices with the devices from which it get a topology discovery message. Add the controller to that, and we have the list of devices we need.

The tricky part is to get the MID. The MID is normally assigned by the transport, not by the agent.  So we have a few options here:
1. Add a mechanism for the transport to respond to a cmdu_tx message with the MID it assigned. This is pretty tricky because it's asynchronous, and without MID we have no easy way to match the MID with the message that was sent.
2. Move assignment of MID from transport to agent. This is a problem for the controller, because it will also have to assign the MID itself, but then how do you make sure the MID is different from the ones generated by the agent?
3. Transport itself keeps track of known devices and transport does the reliable multicast. In this case, "known devices" will be built up based on all the incoming messages, not just topology discovery. It will need an expiry mechanism as well.
4. cmdu_tx message is extended with a list of destination addresses instead of a single one. This is slightly tricky but doable.

Since there is only one reliable multicast message (topology notification), I don't think it's worth developing a lot of infrastructural code for it (like extending cmdu_tx with multiple destinations or having a MID response). Therefore, I tend to prefer option 3.

**Comment by ghost** [comment]
Done in #1296
