### ISSUE TITLE
[TASK] prplmesh_utils.sh status enhancements

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#775]
Currently, `prplmesh_utils.sh status` returns success if prplmesh was operational. It doesn't cover the case where prplmesh restarted unexpectedly due to failure.
We want to capture these kinds of failures in CI.

**Proposed solution**
- [ ] Add BML to test operational status instead of grepping the logs
- [ ] Add BML to get number of failures which caused prplmesh restart
- [ ] Update prplmesh_utils.sh status to use `bml_is_operational()`
- [ ] Add `prplmesh_utils.sh status --num-failures` which returns the number of failures
- [ ] Add an endurance test to CI which waits for a configurable amount of time after prplmesh is operational, then runs `prplmesh_utils.sh status --num-failures` and fails if there was a failure.

**Comment by tomereli** [comment]
Reference PRs on how to add CLI support:
https://github.com/prplfoundation/prplMesh/pull/694 <- BML
https://github.com/prplfoundation/prplMesh/pull/699 <- CLI

**Comment by arnout** [comment]
> Add BML to test operational status instead of grepping the logs

Note that BML is only available on the controller at the moment, so this is not a simple thing.

Since this is relevant mostly for testing, maybe it's easier to do it with new UCC commands instead of with BML.

Another alternative is to let the controller keep track of the number of restarts of the agent. But then it will be difficult to get e.g. per-slave info, or info about the monitor.

> Add BML to get number of failures which caused prplmesh restart
> Update prplmesh_utils.sh status to use bml_is_operational()

If prplmesh_utils.sh just calls bml_cli, there is not much value of using prplmesh_utils.sh. bml_cli status would be nicer.


> Add prplmesh_utils.sh status --num-failures which returns the number of failures
> Add an endurance test to CI which waits for a configurable amount of time after prplmesh is operational, then runs prplmesh_utils.sh status --num-failures and fails if there was a failure.

That would be nice indeed, and it would be triggered nightly or weekly like the certification tests.

**Comment by tomereli** [comment]
> > Add BML to test operational status instead of grepping the logs
> 
> Note that BML is only available on the controller at the moment, so this is not a simple thing.
> 
> Since this is relevant mostly for testing, maybe it's easier to do it with new UCC commands instead of with BML.

I initially liked this approach, but the problem is that we don't have UCC in production mode (`prplmesh.config.certification_mode=0`) since prplMesh is not listening to the UCC port.

> 
> Another alternative is to let the controller keep track of the number of restarts of the agent. But then it will be difficult to get e.g. per-slave info, or info about the monitor.
> 
> > Add BML to get number of failures which caused prplmesh restart
> > Update prplmesh_utils.sh status to use bml_is_operational()
> 
> If prplmesh_utils.sh just calls bml_cli, there is not much value of using prplmesh_utils.sh. bml_cli status would be nicer.
> 

Agree, `bml_cli status` is more appropriate.
