### ISSUE TITLE
[BUG] rax40: prplmesh fails to be operational after some time

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#796]
When the rax40 has been running for some time, prplMesh fails to become operational.

Specifically, it fails here:
```
ERROR 06:07:22:550 <1999162640> base_wlan_hal_dwpal.cpp[756] --> Failed reading parsed parameter 2 ==> Abort
```

It then loops and retries over and over again.

## Steps to reproduce

Unfortunately, I don't know any reliable way to reproduce it.

It has caused a number of scheduled certification tests failures, so prplMesh logs are available here: 
https://gitlab.com/prpl-foundation/prplMesh/-/jobs/431162555/artifacts/browse/logs/FAIL/

**Comment by rmelotte** [comment]
For reference, here are hostapd's outputs when the device is in such a state:
```
root@OpenWrt:~# hostapd_cli -i wlan0 radio_info
Name=wlan0
HostapdEnabled=1
TxEnabled=1
Channel=0
BytesSent=1845
BytesReceived=39259285471
PacketsSent=12
PacketsReceived=80
ErrorsSent=0
ErrorsReceived=0
DiscardPacketsSent=0
DiscardPacketsReceived=0
PLCPErrorCount=UNKNOWN
FCSErrorCount=0
InvalidMACCount=UNKNOWN
PacketsOtherReceived=UNKNOWN
Noise=0
BSS load=99
TxPower=0.00
RxAntennas=2
TxAntennas=2
Freq=UNKNOWN
OperatingChannelBandwidt=UNKNOWN
Cf1=UNKNOWN
Dfs_chan=UNKNOWN
```

```
root@OpenWrt:~# hostapd_cli -i wlan2 radio_info
Name=wlan2
HostapdEnabled=1
TxEnabled=1
Channel=0
BytesSent=0
BytesReceived=12046173950
PacketsSent=0
PacketsReceived=14
ErrorsSent=0
ErrorsReceived=0
DiscardPacketsSent=0
DiscardPacketsReceived=0
PLCPErrorCount=UNKNOWN
FCSErrorCount=0
InvalidMACCount=UNKNOWN
PacketsOtherReceived=UNKNOWN
Noise=0
BSS load=0
TxPower=5788.00
RxAntennas=2
TxAntennas=2
Freq=UNKNOWN
OperatingChannelBandwidt=UNKNOWN
Cf1=UNKNOWN
Dfs_chan=UNKNOWN
```

**Comment by arnout** [comment]
That output is completely bogus, so hostapd seems to be in some bad state.

Next time, check syslog (I don't know where it is stored on rax40...) for any hostapd errors/warnings/...

Also, here are some other hostapd_cli commands that you could try:

- mib
- status
- list_sta
- get_config
