### ISSUE TITLE
[task] Add TLVF support in multiple dynamic lists

### ISSUE THREAD

**Issue by LiorAmram** [prplfoundation/prplMesh#8]
TLVF currently only supports a single dynamic length array, and it has to be the last member in the class (be placed last on the buffer).
The reason for that is all the members are written directly on the buffer (and the class itself holds pointers to their location on the buffer), 
so allocating new element on a list that's not in the end of the buffer requires relocating all the data that comes after it.
This limitation is currently preventing us from properly implementing some types of messages, such as M1 & M2 frames, since those frames require multiple dynamic-length strings.

Currently, the workaround is defining fixed-size string in these messages. 
However, this workaround is only for the short term, since it doesn't match the specs, so it can only work with 

General idea of implementation:

1. for each dynamic size list in a class:
	1.1. listing (in python, not in generated code) all the class members that come after the list.
	1.2. In 'alloc_' method (for basic type or struct lists) and 'add_' method (for class type lists):
		1.2.1. Move the data and update pointer values of all members in 1.1 before the new elements' allocation on the buffer.
		1.2.2. memset the new allocated space to 0 (in order to avoid garbage in the new allocated elements).
		1.2.3. initializing the new elements and updating the relevant pointers and variable (existing code).

**Comment by arnout** [comment]
For the specific case of ATTR_MANUFACTURER etc., I think it would make more sense to introduce a new type `template class fixstring<size_t>` that handles maximum-sized string storage. tlvf still needs special handling of this type to be able to use a dynamic length, of course.
