### ISSUE TITLE
[TASK] Move no_vendor_specific to UCI

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#809]
## Description

There is currently a setting in `beerocks_agent.conf` that allows to turn off the vendor specific messages in M1: `no_vendor_specific`.
The setting has to be turned on for agent tests, otherwise some devices from the testbed will ignore our M1 (see also the related PR: https://github.com/prplfoundation/prplMesh/pull/431).

For controller tests however, it has to be turned off, or autoconfig will fail.

Having the setting in UCI would make it easier to change, because we already change other UCI values based on the test type (management_mode, operating_mode, and so on).

## Exit criteria

- `no_vendor_specific` is stored and retrieved to/from UCI.
- `beerocks_agent.conf` does not contain `no_vendor_specific`

**Comment by vitalii-komisarenko** [comment]
Not longer needed due to removal of no_vendor_specific flag in https://github.com/prplfoundation/prplMesh/pull/932
