### ISSUE TITLE
[TASK] [ieee1905_transport] Map source address to AL-MAC address

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#81]
## Description

A CMDU's source address may not be the AL-MAC address of the transmitting device, but responses must be sent to the AL-MAC. Therefore, a mapping of source addresses to AL-MAC addresses is needed.

## Exit criteria

* Simulate a controller and/or agent that sets an interface address as the source address. After one of the CMDUs which contain the AL-MAC TLV has been sent to the prplMesh device, any subsequent CMDUs that are sent to the simulated device must have the AL-MAC as the destination address.
* Unicast and relayed multicast messages that are forwarded by the transport are not affected.

## Detailed description

The IEEE 1905.1 specification allows the source address of a CMDU to be one of the interface addresses instead of the AL-MAC address: see IEEE Std 1905.1-2013 Table 6-2 "macSa". However, (unicast) responses have to be sent to the AL-MAC address: see "macDa" in the same table.

Therefore, the system must maintain a mapping of source addresses to the corresponding AL-MAC address. Since most flows use the source address to determine where to send the response, the easiest is for the ieee1905_transport to maintain this mapping and to convert the source address of any packet it publishes. This allows all flows to use the source address as the AL-MAC address.

To discover this mapping, the CMDUs that contain an AL-MAC TLV have to be used: topology discovery, topology notification, AP autoconfig search, AP autoconfig renew, push button notification, push button join. Optionally, WSC M1 could also be used since it contains the AL-MAC address; however in practice it's not needed since the AP autoconfig search already contained it.

There are several choices for which component implements this. Currently, ieee1905_transport doesn't interpret CMDUs. So the component that interprets the CMDUs could be:

* the flows that do interpret them (e.g. topology discovery, controller, agent); then they must send a message to ieee1905_transport to update the mapping;
* ieee1905_transport itself, so it starts interpreting CMDUs instead of just forwarding them; 
* A new component can be added; this is possible because the broker supports Xsub.

Note that there is still a problem for the agent, because none of the above messages are sent by the controller to the agent before the WSC exchange is done, and the WSC M1 is a unicast message. This is unfortunately a shortcoming of the specification that can't be solved, except by waiting for the topology discovery message from the controller.

Note that EasyMesh certification does not test this, so this task is not strictly needed for certification.

**Comment by tomereli** [comment]
The transport should stay a simple forwarder. So that leaves us with option 1 or 2.
