### ISSUE TITLE
[BUG] agent: VAPs map is updated only if m_agent_ucc_listener is true

### ISSUE THREAD

**Issue by mariomaz** [prplfoundation/prplMesh#815]
## Description

In backhaul_manager_thread.cpp, method handle_slave_backhaul_message, case ACTION_BACKHAUL_HOSTAP_VAPS_LIST_UPDATE_NOTIFICATION, variable m_vaps_map is updated only if m_agent_ucc_listener is true.  

Moreover, log message in case addClass() fails contains wrong message name.

## Expected behavior

m_vaps_map should be updated in any case, not only if m_agent_ucc_listener is true.
Log message should include ACTION_BACKHAUL_HOSTAP_VAPS_LIST_UPDATE_NOTIFICATION and not ACTION_BACKHAUL_DL_RSSI_REPORT_NOTIFICATION

**Comment by arnout** [comment]
I believe this is solved by one of the commits in #806 which was merged minutes ago. Can you recheck on master?

**Comment by mariomaz** [comment]
Yes, it's already been solved. Closing this issue
