### ISSUE TITLE
[BUG] test_flows: check_error should be initialized to 0 on each test

### ISSUE THREAD

**Issue by mariomaz** [prplfoundation/prplMesh#821]
## Description
Some tests in test_flows.sh do not initialize check_error to 0.
Global variable check_error is increased on error and returned on each test as a result. If a given test does not initialize check_error to 0 at the beginning of its execution, a previous failing test would have as a side effect that such test would also fail.

## Expected behavior
Tests should be isolated. They should pass or fail the same way in suite or when run individually.

**Comment by ghost** [comment]
Will be done as part of the test flows refactoring (#738)

**Comment by arnout** [comment]
Let's leave it open to be sure that #738 is implemented correctly.

**Comment by arnout** [comment]
Implied by #968 and the conversion to Python.
