### ISSUE TITLE
[BUG] test_flows.sh: tests are not isolated

### ISSUE THREAD

**Issue by mariomaz** [prplfoundation/prplMesh#822]
## Description
Tests in test_flows.sh grep log files to decide if test succeeds or fails. All tests execute in a row, appending to the same log file. If one test searches for a particular text that has been written to log by a previous test, then such test would always succeed even if it should have failed.

## Expected behavior

Tests should be isolated. They should pass or fail the same way in suite or when run individually.

**Comment by ghost** [comment]
This will be fixed as part of the task flow refactoring (#738)
The test flows will be completely rewritten in python, in a test framework based on python unittest. It has setup/teardown methods for this explicit purpose (isolating the environment of one test from that of another)

**Comment by arnout** [comment]
Let's leave this open to be sure that #738 really fixes it.
