### ISSUE TITLE
Fix autoconfig with Broadcom controller

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#828]
Test 4.4.3 requires a Broadcom controller. The initial autoconfig (before the teardown) already fails.

**Comment by tomereli** [comment]
Not a bug - autoconfig with broadcom works fine, apparently it was a testbed issue, so the data interface in the broadcom ceased to work - once we factory reset the broadcom it came back to life and we can pass autoconfig with broadcom just fine.

**Comment by rmelotte** [comment]
For the record, we also had issues with the Broadcom device we have.
The bridge configuration was completely off.
I "solved" it by adding the wired interface we use in the bridge, and with that I could finally pass 4.4.3 in CI (at least one of them, the other 2 are still running as I type) https://gitlab.com/prpl-foundation/prplMesh/-/jobs/441334408
