### ISSUE TITLE
[BUG] framework: logging may open two files

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#832]
**Describe the bug** -

This was discovered in CI job https://gitlab.com/prpl-foundation/prplMesh/-/jobs/437812485

Apparently, for each debug level the log file name is calculated separately. Normally, it's always the same name, so the log file will be opened only once. However, if the second happens to tick by in the middle of the initialisation of the logging, we will have two different log files with 1 second difference, and half the log ends up in one log file, the other half in the other log file.

In the case of that CI job, it lead to a failure because we grep the log file to check the status of the agent, and we were grepping the wrong log file.

## Steps to reproduce

This is nearly impossible to reproduce...

For testing purposes it can probably be reproduced by adding a 1 second sleep at some point in the logging initialisation.

**Comment by arnout** [comment]
I took a deeper look and it seems unfixable...

The files (or at least, the file names) are created in easylogging++ in this loop:

```
  for (Configurations::const_iterator it = configurations->begin(); it != configurations->end(); ++it) {
    Configuration* conf = *it;
    if (conf->configurationType() == ConfigurationType::Filename) {
      insertFile(conf->level(), conf->value());
    }
  }
```

Since each log level has a separate Configuration object, it means that insertFile is called for each log level separately. And the %datetime specifier is expanded within insertFile.

So a couple of ways to fix this:

- within easylogging++, "freeze" time within the TypedConfigurations constructor, so that the same time value is used in all %datetime expansions;
- within easylogging++, refactor it so the different log levels use the same file conceptually;
- don't rely on %datetime expansion, instead use a fixed filename in beerocks_logging and generate a new filename ourselves when we cycle logs.

**Comment by RanRegev** [comment]
> don't rely on %datetime expansion, instead use a fixed filename in beerocks_logging and generate a new filename ourselves when we cycle logs

This is the preferred one by me.
How do we cycle the logs? Do we control the cycling process?
