### ISSUE TITLE
[tests] UTAF: Implement prplMesh product DCS test and documentation

### ISSUE THREAD

**Issue by adam1985d** [prplfoundation/prplMesh#835]
## Description

The Intel internal CI utilizes the UTAF to run platform tests.
The requirement is to design and add DCS APIs test

- [x] Add UTAF tests[s] Documentation

Add UTAF test[s] for DCS:
- [x] for RDKB platform 
- [x] for UGW platform

## Exit criteria

Each test setup successfully pass prplmesh operational test in UTAF

**Comment by adam1985d** [comment]
this task is related to Intel task: WLANRTSYS-19993

**Comment by ghost** [comment]
Seems this issue is done, so I'm closing it. Feel free to reopen if you disagree.
