### ISSUE TITLE
[BUG] certification: MAP-5.6.1 fails with No exact one AP HT Capabilities TLV

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#857]
logs are here: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/443453153/artifacts/browse/logs/FAIL/MAP-5.6.1

It looks like here we could have the opposite of issue [#850](https://github.com/prplfoundation/prplMesh/issues/850).

Here are the relevant lines:
```
2020-02-19 22:28:18.236 - INFO - SNIFFER (192.168.250.5:9999) <-- status,COMPLETE

2020-02-19 22:28:18.240 - INFO - Sleep... 2 seconds
2020-02-19 22:28:20.246 - INFO - 
        ~~~~~ Step 2 - Trigger MCUT to send AP Capability Query message to CTT Agent1 ~~~~~

2020-02-19 22:28:20.250 - INFO - DUT (192.168.250.140:8002) ---> dev_send_1905,DestALid,02:90:4C:29:E0:0D,MessageTypeValue,0x8001
2020-02-19 22:28:20.276 - INFO - DUT (192.168.250.140:8002) <-- status,COMPLETE,mid,0x8001

2020-02-19 22:28:24.286 - INFO - SNIFFER (192.168.250.5:9999) ---> sniffer_control_stop
2020-02-19 22:28:24.319 - INFO - SNIFFER (192.168.250.5:9999) <-- status,COMPLETE
```

The sniffer tells prplMesh to send an AP capability query, then stops the sniffer right after that.
The pcap file contains the query, but not the response, which seems to indicate the sniffer was stopped too soon (in the sense: before the agent had a chance to send the reply).

I don't think adding a sleep in the sniffer itself when it's asked to stop makes sense, so we might have no other option than adding a sleep before `sniffer_control_stop` for this specific test only.

@tomereli @Mila-Sh what do you think?

**Comment by rmelotte** [comment]
After looking at the logs again, I realized I missed the 4 seconds difference between the `status,COMPLETE,mid,0x8001` and the `sniffer_control_stop`, so the issue is probably somewhere else.
I'm going to run the test a few more times to see how often it happens, so that we can better decide if we should investigate on this with a high priority or not.

**Comment by rmelotte** [comment]
It failed one out of 10 times: https://gitlab.com/prpl-foundation/prplMesh/pipelines/119631590

**Comment by arnout** [comment]
I guess this is because the packet got lost. The controller should retransmit in that case, but that's not implemented yet -> #273

**Comment by rmelotte** [comment]
Although it doesn't happen a lot when running the test multiple times in a row, it happens more often in the nightly schedules.
Here is the lastest one for example: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/448403807

**Comment by rmelotte** [comment]
It happens with the dummy BWL as well as on the rax40: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/468644939
