### ISSUE TITLE
[TASK] Change interface names for linux platform

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#87]
## Description

Currently, prplMesh supports only wlan0 / wlan2 WLAN interface names, which are hard-coded throughout the code. This is not an issue in RDKB/UGW platforms but might cause issues when running prplMesh natively.

It is good practice to use somewhat unique interface names for the WLAN interfaces when running natively, so simply add `prplmesh-` prefix to the current names.

## Exit criteria

- Interface names are not hardcoded throughout the code - they are defined in CMAKE and passed as CMAKE flag to the source code
- DoD pass on host using prplmesh_utils.sh `../build/install/scripts/prplmesh_utils.sh start`
- DoD pass with containers `sudo ./tools/docker/run.sh -n cont -d -s start-controller-agent; sudo ./tools/docker/run.sh -n agent -d -s start-agent`
    - open bash shell to both (`sudo docker exec --it <agent/cont> bash` and verify that both are operational

**Comment by arnout** [comment]
prplmesh-wlan0 is too long, depending on the configuration Linux network device names can be only 11 characters.

There are quite a few places where `prplmesh` is just too long to be practical, it would be good to find an abbreviation for it.
