### ISSUE TITLE
[BUG] agent: Unitialized variable

### ISSUE THREAD

**Issue by juanschroeder** [prplfoundation/prplMesh#872]
**Describe the bug** -
The wired_link_state variable is used uninitialized in backhaul_manager_thread.cpp

## Additional context

This gave a compilation error on Econet when using GCC 5.5 and only in Release mode (-O3).

**Comment by ghost** [comment]
Hi @juanschroeder ,

Please make sure to always fill in the project and milestone for any issues you create (project should be automated now, but milestone is not).
Also, please fill in the assignee if you already know who is working on it (or who is going to be working on it).

Thanks :-)
Frederik
