### ISSUE TITLE
[BUG] 4.8.1: slave not operational after slave_reset when broadcom device is the controller

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#886]
The test plan specifies the Broadcom device should be used as the controller for the test`MAP-4.8.1_ETH_FH24G`.

When we run the test with the Broadcom controller, the slave for wlan0 does not become operational after the slave_reset, which causes the test to fail.

If we use the Marvell device as the controller for example, the problem does not occur.

Example of such a test using the Broadcom controller: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/445623302

**Comment by rmelotte** [comment]
For reference, here is the same test run with the Marvell controller: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/449752655

**Comment by rmelotte** [comment]
One noticeable difference is that with the Broadcom controller, we reach the operational state before getting the autoconfig response for the 2.4GHz band (wlan0, the one we need):
```
TRACE 15:25:49:577 <1995033872> backhaul_manager_thread.cpp[786] --> FSM: CONNECTED --> OPERATIONAL
DEBUG 15:25:49:578 <1995033872> backhaul_manager_thread.cpp[2174] --> received autoconfig response message
DEBUG 15:25:49:579 <1995033872> backhaul_manager_thread.cpp[2184] --> tlvSupportedRole->value()=0
INFO 15:25:49:579 <1995033872> backhaul_manager_thread.cpp[2195] --> update controller_bridge_mac=02:90:4c:29:e0:0d
DEBUG 15:25:49:580 <1995033872> backhaul_manager_thread.cpp[2199] --> tlvSupportedFreqBand->value()=0
DEBUG 15:25:49:581 <1995033872> backhaul_manager_thread.cpp[2202] --> received auto-config reply for 2.4GHz band
```

As a consequence, we never get this:
```
DEBUG 21:49:04:222 <1993526544> backhaul_manager_thread.cpp[506] --> Iterating on slave wlan0
DEBUG 21:49:04:222 <1993526544> backhaul_manager_thread.cpp[532] --> Sending CONNECTED notification to slave of '' - Mac: 10:0c:6b:a1:bd:6d, IP: 192.165.100.170, GW_IP: , Slave is Backhaul Manager: 0
```

And we instead get:
```
DEBUG 15:25:49:575 <1995033872> backhaul_manager_thread.cpp[506] --> Iterating on slave wlan0
DEBUG 15:25:49:576 <1995033872> backhaul_manager_thread.cpp[509] --> controller not discovered, skipping...
```

**Comment by arnout** [comment]
Right! It looks like the backhaul manager FSM sends out an autoconfig search for each band, but does not wait for an autoconfig response for each band...

We've got two options here: either we let the autoconfig search/response be handled by the slaves and immediately move to operational state (which will BTW allow us to simplify a few things in the slave socket structure as well), or we make sure that the backhaul manager doesn't move to operational state until a response is received for each band (requires an additional state variable similar to the local variable sent_for_2g/5g in the SEND_AUTOCONFIG_SEARCH_MESSAGE state).

The second option is the simplest, but I think the first one corresponds better with reality.

Note that with the first option, the backhaul manager still needs to handle the autoconfig response to be able to identify the controller, but it also needs to forward it to the slaves. Also note that the autoconfig response has no other per-radio identifier than the frequency band, so if you have two radios on the same band, you'll send out two autoconfig search messages but the first autoconfig response looks like it applies to both. Probably isn't a problem. Though we probably should use the MID to be sure it's the correct response.

**Comment by rmelotte** [comment]
@arnout thanks for the help.
From a comment in the code I was also wondering why always calling `finalize_slaves_connect_state` wouldn't work.
Apparently the slave can re-join the controller even if the backhaul was already operational when the slave was registered. Why wouldn't it be possible to use the same mechanism to make the second slave join the controller if the backhaul was changed to operational in-between? 
The comment I'm talking about is this one:
>                    // the backhaul was operational on slave registration.
>                    // This means that it was restarted and sending backhaul connected event
>                    // is required so that the slave will re-join the controller.

What if we called `finalize_slaves_connect_state(true, soc);` even if the state is already `OPERATIONAL`?

**Comment by rmelotte** [comment]
It looks like it works with this change (next line after the comment):
```
-                    if (soc->operational_on_registration) {
+                    if (soc->operational_on_registration || FSM_IS_IN_STATE(OPERATIONAL)) {
```
Though I've no idea if it's intended to work like that or if it's a coincidence.
At this point I also don't understand why `finalize_slaves_connect_state` couldn't be called unconditionally when receiving the autoconfig_reply.

Logs:
```
TRACE 19:41:56:723 <1993571600> backhaul_manager_thread.cpp[786] --> FSM: CONNECTED --> OPERATIONAL
DEBUG 19:41:56:724 <1993571600> backhaul_manager_thread.cpp[2174] --> received autoconfig response message
DEBUG 19:41:56:724 <1993571600> backhaul_manager_thread.cpp[2184] --> tlvSupportedRole->value()=0
INFO 19:41:56:725 <1993571600> backhaul_manager_thread.cpp[2195] --> update controller_bridge_mac=02:90:4c:29:e0:0d
DEBUG 19:41:56:725 <1993571600> backhaul_manager_thread.cpp[2199] --> tlvSupportedFreqBand->value()=1
DEBUG 19:41:56:726 <1993571600> backhaul_manager_thread.cpp[2218] --> received auto-config reply for 5GHz band
DEBUG 19:41:56:726 <1993571600> backhaul_manager_thread.cpp[2221] --> 5GHz band socket found, iface=wlan2
DEBUG 19:41:56:727 <1993571600> backhaul_manager_thread.cpp[2223] --> set controller_discovered to true for 5GHz band, iface=wlan2
DEBUG 19:41:56:741 <1993571600> backhaul_manager_thread.cpp[2225] --> OPERATIONAL
TRACE 19:41:56:741 <1993571600> backhaul_manager_thread.cpp[365] --> finalize_slaves_connect_state: fConnected=1, pSocket=0x56df08cc
DEBUG 19:41:56:744 <1993571600> network_utils.cpp[968] --> ip_item iface=lo
DEBUG 19:41:56:744 <1993571600> network_utils.cpp[968] --> ip_item iface=eth1
DEBUG 19:41:56:745 <1993571600> network_utils.cpp[968] --> ip_item iface=br-lan
DEBUG 19:41:56:745 <1993571600> network_utils.cpp[968] --> ip_item iface=eth0_4
WARNING 19:41:56:746 <1993571600> backhaul_manager_thread.cpp[494] --> backhaul_manager slave was not found, select first connected slave: hostap_iface=wlan0, sta_iface=wlan0
DEBUG 19:41:56:746 <1993571600> backhaul_manager_thread.cpp[506] --> Iterating on slave wlan0
DEBUG 19:41:56:747 <1993571600> backhaul_manager_thread.cpp[515] --> notification should be sent to slave wlan2 skipping wlan0
DEBUG 19:41:56:747 <1993571600> backhaul_manager_thread.cpp[506] --> Iterating on slave wlan2
DEBUG 19:41:56:747 <1993571600> backhaul_manager_thread.cpp[532] --> Sending CONNECTED notification to slave of '' - Mac: 10:0c:6b:a1:bd:6d, IP: 192.165.100.170, GW_IP: , Slave is Backhaul Manager: 0
```
https://gitlab.com/prpl-foundation/prplMesh/-/jobs/451069671/artifacts/browse/logs/PASS/MAP-4.8.1_ETH_FH24G/dut_netgear-rax40/
