### ISSUE TITLE
[BUG] certification: MAP-4.4.3_ETH_FH24G fails with MSG: No AP-Autoconfiguration WSC M1 message found

### ISSUE THREAD

**Issue by Mila-Sh** [prplfoundation/prplMesh#890]
Logs in : https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ?path=%2Fprpl%20agent%20tests%2FFAIL%2FMAP-4.4.3_ETH_FH24G%202020-02-26_16-03-33

**Comment by rmelotte** [comment]
From what I see the M1 is there, the MACs are correct, but this condition is not met: `wps.rf_bands == 0x01`

**Comment by tomereli** [comment]
@Mila-Sh Please verify this doesn't reproduce, reopen if it still happens?
