### ISSUE TITLE
[TASK] Refactor python test framework

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#896]
## Description

Subtask of #738 

The current python test framework (made in issue #894 , PR #859 ) is a simple transition from shell to python, which is a good first step.

The next step to improving the test framework is refactoring it into something sensible, based on python unittest, with each test in a separate file.

Another thing that needs to be done in this task is to implement the new architecture specified by arnout (TO DO: link to UML diagram)

This is needed for #893

**Comment by abelog** [comment]
Hi, @arnout can you please share location for new test architecture description/document?
