### ISSUE TITLE
[REFACTOR] Open a file from multiple locations

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#90]
There are quite a few places where a file is opened for reading, but there are several paths possible so we need to try all of them to find if one exists.

**Code example**:

```cpp
    std::ifstream in_conf_file;
    in_conf_file.open(PLATFORM_DB_PATH_TEMP);
    if (!in_conf_file.is_open()) {
        in_conf_file.open(PLATFORM_DB_PATH);
        if (!in_conf_file.is_open()) {
            MAPF_ERR("Failed oppening file " << PLATFORM_DB_PATH);
            return RETURN_ERR;
        } 
    }
```

**New code**:

```cpp
    std::ifstream in_conf_file mapf::find_input_file(PLATFORM_DB_PATH_TEMP, PLATFORM_DB_PATH);
    if (!in_conf_file.is_open()) {
        return RETURN_ERR;
    }
```

**Review comment reference**: https://github.com/prplfoundation/prplMesh/pull/85#discussion_r300661389

**Comment by ghost** [comment]
@arnout @tomereli  The associated PR for this (#85) has been merged. Is there any other work for this task or can it be closed?

**Comment by arnout** [comment]
This most certainly is not done yet.

The PR reference was actually supposed to be a reference to a review comment. I fixed that now.
