### ISSUE TITLE
[TASK] Detect Agent process/radio down by the Controller

### ISSUE THREAD

**Issue by morantr** [prplfoundation/prplMesh#906]
## Description

Implement a mechanism which detects on the controller side that an Agents Radio/BSSID went down.

## Problems
In the past, we used to have a TCP/IP socket between the Controller and the Agent.
When a radio went down, the son_slave perform reset and closed the socket to the controller.
When that happened, the socket on the controller side was closed too, and the controller removed the node of the son_slave from the database.

Nowadays, we have a BUS infrastructure that replaces the TCP/IP socket.  This means that if the son_slave perform reset,
No socket is closed and the controller doesn’t aware that and Agent radio is down.

## Topology flow brief
According to Topology notification message (8.2.2.3  IEEE1905.1-2013), If a 1905.1 management entity (Agent in our case) detects that any of the information has changed which was specified the last topology response message previously sent, then it shall Construct a topology notification message containing a new MID value and the following TLVs and send it to the controller:

_IEEE 1905.1-2013:_
- One **AL MAC address type** TLV
Implemented: No
Relevant: No

_MultiAP:_
- Zero or one **Client Association Event** TLV
Implemented: Yes

The topology response message contains the following TLVs:

_IEEE 1905.1-2013:_
- One **Device information type** TLV.
It contains the MAC address of the AL-MAC and every interface on it, which standard it supports, its BSSID, role (AP/STA) and channel & BW if it is a wireless interface.
Note: 1905.1a-2014 redefine the media type field on this TLV.
Implemented: Yes – partially. Include information only on the Ethernet interfaces.
Relevant: No

- Zero (One if the device has more that one interface) or more **Device bridging capability** TLVs.
It contains a list of interface mac addresses tuples that are on the same bridge.
Implemented: No
Relevant: No
- Zero or more **non-1905 neighbor device list** TLV.
Implemented: No
Relevant: No
- Zero or more **1905.1 neighbor device** TLVs.
Implemented: No
Relevant: No

_IEEE 1905.1a-2014:_
- Zero or more **Power off interface** TLVs.
It contains a list of MAC address that has “PWR_OFF” state and the device information data similar to on Device information type TLV.
**Implemented: No**
**Relevant: Yes**
- Zero or more **L2 neighbor device** TLVs (ethernet neighbors ?)
Implemented: No
Relevant: No

_MultiAP:_
- Zero or one **SupportedService** TLV.
It contains a list of entities runs on the AL-MAC - Agent/Controller.
Implemented: Yes
Relevant: No
- Zero or one **Associated Clients** TLV.
Implemented: Yes
Relevant: No
- One **AP Operational BSS** TLV.
It contains all BSSIDs (Vaps) information (RUID, MAC, SSID) on each radio.
**Implemented: Yes
Relevant: Yes**
- One **Multi-AP Profile** TLV.
It Describes on which revision of the standard we support (R1/R2).
Implemented: No
Relevant: No

## Solutions

- [ ] Radio interface which went down (HOSTAP-DISABLED)/son_slave is doing reset:
1. Upon receiving M1 on the controller, trigger **topology query message** to the Agent. This will end by receiving a topology response message which contains all relevant information to create an Agent node on the database.
2. Add **power off interface** TLV to the **topology response message** which describes the interfaces that went down (HOSTAP_DISABLED).
3. Create a parser for **power off interface** TLV and **AP operational BSS** TLV on the **topology response message** handler, and mark on the database Radio/BSSID that are not operational.
4. Whenever receiving a **topology notification message** with no TLVs, send a **topology query message** to the Agent.

- [ ] Note: It is optional to add to this sequence also sending and handling of **AP Operational BSS** TLV (only handler, sending it is already implemented) and **Device bridging capability** TLV which will use to fill the controller database according to the standard and not by VS messages.

- [ ] Radio agent (son_slave) or Hostapd silent crash:
Usually when a process is killed the operating system is closing an opened socket to it on other processes. But sometimes a process can be crashed and the socket will not be disconnected properly on other processes. In that case, there is a need to create an automatic ping mechanism to all the opened sockets, and notify the ping sender thread if the ping has not been answered.
1. Add a mechanism on beerocks_socket_thread that send ping to all thread clients, and call “socket_disconencted” if reached to reply timeout.
2. Create the same mechanism on BWL base class that sends “PING” to ctrl_iface, and call derived class “disconnect” function if reached timeout.
Note: Perhaps this feature will not be implemented since there is planning to create an external watchdog that will do the same. So for a while put it on hold.

- [ ] Agent process is down/crashed:
If the Agent process (backhaul_manager in our case) went down, it cannot send the **topology response message** and alert the controller about it.
The IEEE 1905.1-2013 standard defines that the Agent must send a topology discovery message every 60 seconds (implemented in the backhaul manager), it can be used to update the Agent bridge node “last_seen” field on the controller database and remove the node if the message has not been arrived for (60+ timeout_span).
1. Add an update to the bridge node “last_seen” on the **topology discovery message** handler.
2. Remove the Agent (bridge) node on network_health_check_task, if the agent “last_seen” has reached timeout.

## Code Removal
Implementing the solutions mentioned above will allow removing:

- [ ] 1. Controller/Agent PING mechanism between the son_master and the son_slaves which is not relevant anymore since it is not based on MultiAP standard (and also it is very ugly).

- [ ] 2. Monitor_thread keep_alive mechanism could be removed as well since it will be replaced by a more general mechanism that covers more cases.

- [ ] 3. Controllers son_slave node “last_seen” field updating and monitoring by network_health_check task since it is replaced by a standard-based solution.

## Detailed description

- **Components affected** - controller/agent/common
- **Build considerations** - None
- **Dependencies** - None

**Comment by arnout** [comment]
I don't think it's that complicated...

1. Whenever anything changes, the agent must send a topology notification (relayed multicast). This happens when:
- a STA connects or disconnects (already implemented);
- an interface is added (e.g. a VAP is configured);
- an interface changes state (e.g. ethernet link goes up or down);
- an interface is added (e.g. a VAP becomes operational).
2. When controller receives a topology notification that does not contain a Client Association Event TLV, it sends a topology query.
3. Agent gives topology response containing AP Operational BSS TLV (already implemented?).
4. Controller updates db based on AP Operational BSS TLV.
5. Existing VAP list is removed from Intel slave join message.

I believe the different cases of step 1 cover everything. Including when a repeater disappears: with wired backhaul, this will cause an ethernet link to go down; with wireless backhaul, it will cause a backhaul STA to disassociate.

**Comment by mariomaz** [comment]
My comments:
- I think this sentence is not true: "Note: 1905.1a-2014 redefine the media type field on this TLV.". Regarding DeviceInformation TLV, 1905.1a-2014 says that "local interfaces in power state PWR_OFF
shall not be listed in the 1905 device information type TLV as those interfaces are listed in the Power off interface TLV"
- Although not relevant in this context, SupportedService TLV is already implemented and included in TOPOLOGY_RESPONSE_MESSAGE
- What is "4. Whenever receiving a topology response message with no TLVs, send a topology query message to the Agent." intended for?
- I think the ping mechanism suggested is not necessary as one can tell that a socket is closed on the other end when `read()` returns 0
- Proposed solution relies on topology manager being part of the agent, it cannot be in a different process. This is something that had to be decided as part of the topology discovery design/architecture task.
- If controller and agent run in different devices, then controller should also implement the topology manager role. 
- Controller can send a Topology Query message to an agent, if no response is received, remove agent from its database. 
- Controller can send Topology Discovery messages and remove an agent from its database if that agent does not answer.

**Comment by morantr** [comment]
> I don't think it's that complicated...
> 
> 1. Whenever anything changes, the agent must send a topology notification (relayed multicast). This happens when:
> 
> * a STA connects or disconnects (already implemented);
> * an interface is added (e.g. a VAP is configured);
> * an interface changes state (e.g. ethernet link goes up or down);
> * an interface is added (e.g. a VAP becomes operational).
> 
> 1. When controller receives a topology notification that does not contain a Client Association Event TLV, it sends a topology query.
> 2. Agent gives topology response containing AP Operational BSS TLV (already implemented?).
> 3. Controller updates db based on AP Operational BSS TLV.
> 4. Existing VAP list is removed from Intel slave join message.
> 
> I believe the different cases of step 1 cover everything. Including when a repeater disappears: with wired backhaul, this will cause an ethernet link to go down; with wireless backhaul, it will cause a backhaul STA to disassociate.

What you have written here is sum up the thing I wrote under "Radio interface which went down (HOSTAP-DISABLED)/son_slave is doing reset" except it missing the power off interface TLV.
The AP Operational BSS TLV (which indeed implemented) covers only BSSID (VAPS) but not
refer to the radio interface. Therefore we need to add power off interface TLV to the topology response message.

What you wrote about the ethernet/wireless link is not related to this flow, since we could not send the response message when the backhaul link is disconnected, the Agent will not be able to send the CMDU to the controller.
To handle this see the solution in the paragraph "Agent process is down/crashed".

**Comment by morantr** [comment]
> My comments:
> 
> * I think this sentence is not true: "Note: 1905.1a-2014 redefine the media type field on this TLV.". 

It is true, 1905.1a-2014 redefine the media type field which previously defined on IEEE 1905.1-2013.

> Regarding DeviceInformation TLV, 1905.1a-2014 says that "local interfaces in power state PWR_OFF shall not be listed in the 1905 device information type TLV as those interfaces are listed in the Power off interface TLV"

Yes sure, good comment.
> * Although not relevant in this context, SupportedService TLV is already implemented and included in TOPOLOGY_RESPONSE_MESSAGE

Correct, my bad. I will update the description.
> * What is "4. Whenever receiving a topology response message with no TLVs, send a topology query message to the Agent." intended for?

My mistake, it should have been "topology notification". I will update the description.

> * I think the ping mechanism suggested is not necessary as one can tell that a socket is closed on the other end when `read()` returns 0

Basically you are right, but we do a `read()` call only when an event is received on the socket.
But when the process crash or brutally killed, the process might not close the socket and no event will be received on the peer thread.

> * Proposed solution relies on topology manager being part of the agent, it cannot be in a different process. This is something that had to be decided as part of the topology discovery design/architecture task.

I'm not familiar with any thought to manage the topology flow outside of the Agent.
If there is a plan to do it, then my design could go to the trash :(
**Edit: After further thinking, this will not be a problem. When discovery will be implemented it will have to take care to exchange the ap status with the agent.**


> * If controller and agent run in different devices, then controller should also implement the topology manager role.

I don't know about it. This whole task is basically meant to detect when an Agent/hostap is down on the controller side. I don't think this suggestion is relevant.

> * Controller can send a Topology Query message to an agent, if no response is received, remove agent from its database.

The Controller should send the Query only one time, after the Agent sends M1, and send it again only when receiving topology notification with no tlvs. I guess it could be an improvement to wait for the response, and if it is not being received, remove the Agent from the database, but it is not likely that just after receiving a message from the Agent (M1/topology notification) it would not reply.

> * Controller can send Topology Discovery messages and remove an agent from its database if that agent does not answer.

No need to, the Agent sends it every 60 seconds so if the controller have not received it, it can assume that the agent is down. See "Agent process is down/crashed".

**Comment by tomereli** [comment]
> 
> > * Proposed solution relies on topology manager being part of the agent, it cannot be in a different process. This is something that had to be decided as part of the topology discovery design/architecture task.
> 
> I'm not familiar with any thought to manage the topology flow outside of the Agent.
> If there is a plan to do it, then my design could go to the trash :(
> 

Please refer to https://github.com/prplfoundation/prplMesh/blob/master/documentation/BeeRocks_v1_4_Architecture.pdf

As you can see in section 4.2, the ieee1905_1 Topology & Discovery agent is indeed a separate process part of the Multi-AP Framework. So yes, if you rely on the discovery agent being part of the agent then you need to align your design to it, cause this was from the beginning the architecture and there is no plan to change it - the reason what we have currently regarding discovery resides in the agent is only due to the time schedule so we can pass certification.
![image](https://user-images.githubusercontent.com/13386849/75962412-62abff80-5ecc-11ea-9f0c-0d436a4080e3.png)

**Comment by arnout** [comment]
This will be the flow for when an indirectly connected agent goes down:

```C --- A1 -wired- S1 -wired- A2```

C = controller; A1, A2 = agents; S1 = switch

- A2 goes down
- A1 waits 60s
- A1 notices A2 is no longer there (no discovery message)
- A1 sends topology notification
- C queries A1
- A1 reports neighbours without A2
- C now knows that A2 is gone

**Comment by arnout** [comment]
I think these are the missing pieces:

- agent has to send Topology Discovery every 60s (already implemented)
- agent has to keep track of neighbours and last time seen (can this be refactored with the db in the controller?)
- agent has to report in Topology Response
- when new neighbour is discovered, or neighbour times out, or interface goes up or down, agent has to send Topology Notification without TLVs
- controller should *not* handle Topology Discovery message
- controller has to do Topology Query every time it gets Notification
- controller has to create nodes for every neighbour in Topology Response
- controller has to save neighbour information in db
- controller has to do Topology Query of every new node
- controller has to remove node if it has no neighbours any more

And of course still remove all the deprecated stuff.

**Comment by morantr** [comment]
Close and open a new task instead: #925
