### ISSUE TITLE
[TASK] Run flake8 on Python scripts

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#916]
Python has a standard for how Python scripts should be formatted: PEP 8. There's a tool, flake8, that checks compliance with PEP 8.

- [ ] Fix existing flake8 issues.
- [ ] Add .flake8 with our config options (e.g. max-line-length=100).
- [ ] Add python3-flake8 to the builder docker image.
- [ ] Run flake8 in gitlab CI.

**Comment by vitalii-komisarenko** [comment]
There is a tool called autopep8 that can produce patches to automatically fix PEP8 issues.
The only issue is that does not squeeze complex instructions into 100-characters limit and it makes flake8 unhappy.

**Comment by arnout** [comment]
This is done for everything under tests/. The other scripts are hardly used, and tlvf.py is too big a thing to fix unless someone works on it.

Therefore, there's a flake8-diff CI check that verifies that modified files comply, but doesn't require everything to comply.
