### ISSUE TITLE
[TASK] Test onboarding with all controllers

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#921]
## Description

It seems there was an issue with a test when using a Qualcomm controller, but not with Marvell.
To see if this is a problem with the hardware or with the test, we should really do an onboarding test with all possible configurations, to weed out the various issues.

**Comment by rmelotte** [comment]
There is a pipeline testing the onboarding with each certified controller here: https://gitlab.com/prpl-foundation/prplMesh/pipelines/124577107 .

**Comment by rmelotte** [comment]
It fails for the Mediatek and Qualcomm devices.

The M1 gets fragmented, and apparently those devices do not handle it well.

**Comment by rmelotte** [comment]
https://github.com/prplfoundation/prplMesh/pull/932 possibly fixes it: https://gitlab.com/prpl-foundation/prplMesh/pipelines/124600034
