### ISSUE TITLE
[TASK] Capture packets in test_flows.py using tshark

### ISSUE THREAD

**Issue by Galvien** [prplfoundation/prplMesh#942]
## Description

Currently, both `test_flows` implementations search the logs in order to confirm that messages were received properly.
However, this causes the logs to be flooded with unnecessary prints and doesn't provide good debugging information for the script, as sometimes it can find irrelevant prints, and the script's string expressions being searched for in the logs need to be identical to the cpp implementation, causing even more confusion.

A proposed improvement to this would be to analyze the raw packet data using the python script.
An attempt was made in PR #924, utilizing tshark to generate a json file from the tcpdump and later opening it in python, however, as suggested by @arnout and @tomereli, a more elegant solution would be to capture the packets directly using tshark, and handling them later as we desire, e.g. filter them or dump them into a file.

## Challenge

At the moment I'm attempting to implement this using [pyshark](https://github.com/KimiNewt/pyshark) however, after attempting to capture the packets in the background on a different thread, I ran into a bug with pyshark's implementation causing an issue when attempting to [run the sniffer in a different thread.](https://github.com/KimiNewt/pyshark/issues/353)
<img src="https://media.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif" title="WHY GOD WHY" height=50> 
So we need to think of a different approach.

**Comment by Galvien** [comment]
In addition, as it seems, it takes pyshark nearly 15 seconds to capture the first `IEEE1905` packet, so if we want to utilize it synchronously, It'll significantly lengthen the running time of the script.

**Comment by kantera800** [comment]
> In addition, as it seems, it takes pyshark nearly 15 seconds to capture the first `IEEE1905` packet, so if we want to utilize it synchronously, It'll significantly lengthen the running time of the script.

Pyshark parses xml files and not live packets, that can explain the delay.
i see there is an option for live capture did you try it ?

**Comment by Galvien** [comment]
I was referring to pyshark's LiveCapture feature.
