### ISSUE TITLE
[BUG] MAP-5.6.1 fails with "No Topology Response message found"

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#957]
Example of a job where it fails: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/468322587

This issue could be related or even the same as this one: https://github.com/prplfoundation/prplMesh/issues/956 (same job, both broadcom device, controller logs seems to both loop on receiving M1 and sending M2).

**Comment by arnout** [comment]
This looks exactly the same as #958 but then with broadcom instead of qualcomm.

It looks very different from #956 however.

**Comment by vitalii-komisarenko** [comment]
This test was run about 10 times in the last 10 days.
It passed all of them.
Probably OK to close the bug.
