### ISSUE TITLE
[BUG] MAP-5.6.2_ETH_FH5GL fails with No Topology Response message found

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#958]
Example of a job where it fails: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/468322587

This issue could be related or even the same as this one: #956 (same job, both Qualcomm device, controller logs seems to both loop on receiving M1 and sending M2).

**Comment by arnout** [comment]
As the title says: the CTT agent doesn't send a Topology Response, even though the controller *does* send a Topology Request (and it is captured by the sniffer).

This test has already passed before, and results are available on owncloud. The only difference that I can see in the pcap file is that in the failing test, the MCUT does send a Topology Discovery, while in the successful test it did not. So maybe that Topology Discovery causes an issue. I can think of two things:
- the MID of the topology discovery differs wildly from the MID of the topology query (0x0043 -> 0x8000) - maybe the CTT agent considers it as invalid or duplicate or something;
- maybe something is wrong with the topology discovery which causes the CTT agent to blacklist it.

And of course, something wildly different may still be wrong.
