### ISSUE TITLE
[BUG] agent: MAP-4.7.9_ETH fails with "No 1905 Ack message found"

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#963]
Job: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/469199545

Logs: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/469199545/artifacts/browse/logs/FAIL/MAP-4.7.9_ETH/

**Comment by tomereli** [comment]
Fails consistently on no ACK message found.
See - https://gitlab.com/prpl-foundation/prplMesh/-/jobs/468547961

Looks like beacon metrics handling not implemented at all - @mariomaz please confirm

**Comment by arnout** [comment]
Indeed, 11k is still done with VS messages instead of EasyMesh messages. tlvBeaconMetricsQuery and tlvBeaconMetricsResponse aren't even in tlvf_conf.yaml!

Created #972 as a task, this one can be considered resolved with that.
