### ISSUE TITLE
[BUG] MAP-5.7.1 fails with "No Tx Link Metrics TLV found" (dummy)

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#984]
job: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/475308333
logs: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/475308333/artifacts/browse/logs/FAIL/MAP-5.7.1/

Re-running here: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/475829513 (it passed)

**Comment by vitalii-komisarenko** [comment]
This test has been tested about 10 times in the last 10 days.
It passed all the times.
