### ISSUE TITLE
[BUG] MAP-4.7.9_ETH fails with "No 1905 Ack message found"

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#985]
job: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/475549425

logs: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/475549425/artifacts/browse/logs/FAIL/MAP-4.7.9_ETH/

new run on current master: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/475845799

**Comment by tomereli** [comment]
Fails since beacon metrics query is not supported in prplmesh. Will be fixed by #399 .

**Comment by ghost** [comment]
4.7.9 is passing consistently on the nightly certification testbed, so presumably this is fixed; closing the issue.
