### ISSUE TITLE
[BUG] MAP-4.5.2_ETH_FH5GL fails with MSG: The power diff is less than 5dBm

### ISSUE THREAD

**Issue by Mila-Sh** [prplfoundation/prplMesh#995]
job: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/480661759

logs: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/480661759/artifacts/browse/logs/FAIL/MAP-4.5.2_ETH_FH5GL/

**Comment by rmelotte** [comment]
This one is a duplicate of https://github.com/prplfoundation/prplMesh/issues/962
